### PR TITLE
Fix: Line-height breaks line break mode (iOS)

### PR DESCRIPTION
**Pull request by hettiger**
When setting line-height using a stylesheet, line break mode will stop working.

__Working line break mode:__
https://play.nativescript.org/?template=play-ng&id=3HPeu8

__Now adding a style to home.component.css:__

```css
Label {
    line-height: 1;
}
```

__Results in broken line break mode:__
https://play.nativescript.org/?template=play-ng&id=3HPeu8&v=5

My Pull Request fixes this behavior.

### CODE REVIEW

**Comment by hettiger** [comment]
Just signed the CLA

**Comment by SvetoslavTsenov** [comment]
uitests

**Comment by SvetoslavTsenov** [comment]
cuteness

**Comment by SvetoslavTsenov** [comment]
testsappng

**Comment by hettiger** [comment]
@SvetoslavTsenov I see one of the checks failed. Can you provide further information or are you taking this over? A click on Details gives me an `ERR_NAME_NOT_RESOLVED` error. As far as I remember all checks passed before I updated my PR.

**Comment by SvetoslavTsenov** [comment]
Hey @hettiger, thank you for your contribution. All checks are fine but we still need some time to review the PR.

**Comment by hettiger** [comment]
@SvetoslavTsenov Sorry for me asking again but it's almost been a month since your last comment and theres still one pending check. Just a friendly reminder :-)

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
run ci

**Comment by manoldonev** [comment]
@hettiger I had to cherry-pick your fix and open [a new PR](https://github.com/NativeScript/NativeScript/pull/5544) (your authorship of the contribution is intact) as after some recent CI changes on our side we had some infrastructure issues with running our CI automated tests on the original PR.

Sorry for this!

**Comment by hettiger** [comment]
Thank you @manoldonev

**Pull request closed without merging**
