### PR TITLE
Fix utils/types class name resolution regex.

### PR DESCRIPTION
**Pull request by hdeshev**
Breaks when uglifying code.

### CODE REVIEW

**Comment by hdeshev** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by hdeshev** [comment]
Fixes #3347

**Comment by hdeshev** [comment]
Related to #3347

**Comment by vchimev** [comment]
run ci

Fix build script, re-run job.

**Comment by vchimev** [comment]
run ci

Fix build script, re-run job.

**Comment by vchimev** [comment]
run ci

Fix build script, re-run job.

**Pull request merged**
