### PR TITLE
Sibling css selector

### PR DESCRIPTION
**Pull request by PanayotCankov**
Merging @SBats sibling css selector PR.
Satisfied tslint. Rebased onto master. Sqashed.

### CODE REVIEW

**Comment by PanayotCankov** [comment]
ui-tests

**Comment by PanayotCankov** [comment]
uitests

**Comment by vakrilov** [comment]
Please connect to and Issue in github.
@NickIliev and @tsonevn - Can you update [the supported-selectors section styling article in docs](https://docs.nativescript.org/ui/styling#supported-selectors) when this is merged.

**Comment by tsonevn** [comment]
Docs PR [#769](https://github.com/NativeScript/docs/pull/769)

**Pull request merged**
