### PR TITLE
disable recycling on specific button

### PR DESCRIPTION
**Pull request by hshristov**
add more thorough test for view recycling
fix memory leak with android ActionBar
improve padding reset when view is recycled
improve reset of several controls

### CODE REVIEW

**Comment by NathanaelA** [comment]
@hshristov - One question I have been meaning to ask; is there a way to disable the reuse of components easily (i.e. like if there isn't a resetNativeView function?)    I did a custom component that must be destroyed and re-initialized on each use; so I want to make sure there is a way that when all this recycling lands; there is an easy way to disable it per-component type...

**Comment by hshristov** [comment]
@NathanaelA - Yes, there is `recycleNativeView` property on `ViewBase`.
But due to the native of this feature we don't enable it but default for all controls. As a plugin author you can choose to enable it if you know that this control will work correctly. But by default it is disabled.

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
animation

**Comment by hshristov** [comment]
run animations

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
run ci

**Comment by hshristov** [comment]
untests

**Comment by hshristov** [comment]
@NathanaelA Yes, there is a property `recycleNativeView: boolean` on `ViewBase` type.
But due to the nature of the feature we don't enable it for all controls. Every plugin author should test extensively and then enable it if it makes sense (meaning if it gives performance improvements).

In some synthetic tests `Label` doesn't bring much improvements when its nativeView is reused. But `Button` yields around 40% less time when nativeView is reused.

**Comment by SvetoslavTsenov** [comment]
run animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
uitests

**Comment by SvetoslavTsenov** [comment]
uitests

**Comment by SvetoslavTsenov** [comment]
run uitests android

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
run ci

**Pull request merged**
