### PR TITLE
fix: roll back CopyWebpackPlugin to v4.6.0

### LINKED ISSUE #8849: Nativescript 7 HMR issue, update on every change in code
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.8
 - Cross-platform modules:
 - Android Runtime: 7.0.
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
Whenever you type to change the code even if you press the spacebar, HMR is fired and the app is restarted.
**To Reproduce**
tns run android

**Expected behavior**
HMR is fired only after you save the changes and the app should not restart.
**Sample project**
-none

**Additional context**
-none

### PR DESCRIPTION
**Pull request by shirakaba**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md

## What is the current behavior?
HMR non-functional

## What is the new behavior?
HMR functional

Fixes/Implements/Closes #[Issue Number].

Closes https://github.com/shirakaba/react-nativescript/issues/65
Closes #8849

Not aware of any breaking changes; this is fixing a regression more than anything.

### CODE REVIEW

**Comment by shirakaba** [comment]
Note: All the links in the PR checklist are broken, so I can't read up on those.

**Comment by shirakaba** [comment]
See https://github.com/NativeScript/nativescript-dev-webpack/pull/700/files for an earlier commit showing what the CopyWebpackPlugin configuration looked like back when we were using v4.6.0.

**Review by rigor789 — APPROVED** [review]
LGTM - I tested locally and it's working. 

However, I'm a bit unsure on the release path:
* Should not be an in-range update (ie a patch/minor version) - it would break projects unless they revert the options syntax in their configs
* Should not be a major bump - it's a downgrade, doesn't really make sense as a major imo
* Should be opt-in by projects

My idea:
Publish under `3.1.0-hmr.0` and the `hmr` tag on npm.

Another issue: do we merge it? Do we keep it around as a PR, or perhaps a new branch? Since it's going to be tagged as `hmr` and not `latest` - it shouldn't really live on `master`.

**EDIT:**
Published as `@nativescript/webpack@3.1.0-hmr.0` (tagged as `hmr`) - we will keep the source in this PR without merging it (may merge it down to a new branch if necessary in the future). A short guide to use will be posted early next week, but a quick overview:
```bash
npm i --save-dev @nativescript/webpack@3.1.0-hmr.0
rm -rf webpack.config.js node_modules
npm i
```

This should re-create the `webpack.config.js` with the downgraded CopyWebpackPlugin syntax.

---
Converted PR to draft to avoid accidental merging.

**Comment by shirakaba** [comment]
@rigor789 Thanks so much for testing this out.

I agree that versioning it in-range would be problematic for existing projects.

I think major would actually be acceptable, though – we’re not aware of any merit that was gained by updating the plugin (so I wouldn’t consider it an upgrade), and yet we are sorely aware of some functionality having been lost (HMR). I can guarantee that users will continue to come asking why HMR isn’t working and I don’t think they should have to opt-in to a special version name to restore it – it should be considered a stable and desired part of NativeScript functionality, not a “nice to have”. By marking it simply as a major version update, we’d keep things correct by semver, easy to explain, and most importantly, easy to maintain (by virtue of not having to maintain a separate branch with this commit).

**Comment by rigor789** [comment]
@shirakaba you are absolutely right - will get this merged and bumped as 4.0! 🎉

**Pull request merged**
