### PR TITLE
Enable BITCODE

### PR DESCRIPTION
**Pull request by mapo80**
This change permit to enable Bitcode on apps that use NS.

### CODE REVIEW

**Review by NathanaelA — APPROVED** [review]
Looks good.

**Comment by NathanaelA** [comment]
However, Matteo, @mapo80  -- -we still need your CLA to merge this. --   Please sign this  http://www.nativescript.org/cla

**Comment by mapo80** [comment]
@cla-bot check

**Comment by mapo80** [comment]
> However, Matteo, @mapo80 -- -we still need your CLA to merge this. -- Please sign this http://www.nativescript.org/cla

@NathanaelA I’ve yet signed cla for a previous PR.

**Comment by NathanaelA** [comment]
Did you perhaps use a different email address to push this PR?   Because Github also thinks this is your first PR (see the first time contributor), and if so can you sign the CLA with that email address also?    You should be able to do a git log on your local repo to see who your commit was committed as...

**Comment by mapo80** [comment]
@cla-bot check

**Comment by mapo80** [comment]
@cla-bot check

**Comment by mapo80** [comment]
@NathanaelA cla fixed

**Pull request merged**
