### PR TITLE
feat(visionos): ui-mobile-base supporting xros plus improvements to window handling

### PR DESCRIPTION
**Pull request by NathanWalker**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/DevelopmentWorkflow.md#running-unit-tests-application.
- [x] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/tools/notes/WritingUnitTests.md.

### CODE REVIEW

**Comment by farfromrefug** [comment]
I dont think you should commit xcframeworks. they should be built locally

**Comment by NathanWalker** [comment]
Completely agree @farfromrefug your PR here will help as well which we need to finish testing with:
https://github.com/NativeScript/NativeScript/pull/10387/files

The hardest debate on that topic is ability to contribute to core quickly/easily. If each contributor has to build an .xcframework just to run core locally to fix something and post a PR? Likely not great (maybe they encounter an issue with the .xcframework build and they become blocked to help fix something?)

**Comment by farfromrefug** [comment]
I dont sée any issue with people having to build something to test. every single android, iOS, c++... requires the user to build and have a dev env. I even think it is good thing .
still I understand what you mean.
I am on my phone right now but that xcframework is the widget one? if so WR could either publish on cocoapod but er could also put the sources directly in platforms/iOS/src. it would make the build a bit slower but I would still tend for this solution :
* it allow anyone to test changing sources directly in their app and then create a PR without even having to clone N
* users could patch sources (advanced usage) for their own need.
* useful for contributors to work directly on widget sources in production apps using XCode. (same thing would be awesome for android).

but if it is not the widgets xcframework my point is useless :p

**Review by triniwiz — APPROVED** [review]
LGTM

**Pull request merged**
