### PR TITLE
Dialog action fix

### PR DESCRIPTION
**Pull request by PeterStaev**
If the user wants to display only action sheet buttons w/o any text and
he sends null as message, the empty string causes an empty title to be
shown above the buttons. Having null instead, completely eliminates the
empty space.

### CODE REVIEW

**Comment by hshristov** [comment]
@PeterStaev 
You are absolutely correct. The problem I see is that there should be another parameter for title and we should call the native api with the correct parameters. Right now we pass the message as Title in both platforms and we pass "" as message.

**Comment by PeterStaev** [comment]
@hshristov  I agree this is a much better idea!

**Comment by PeterStaev** [comment]
Added the title option. In order to not cause much problems for existing code using the dialog.action:
For **iOS7** - Continue to send the message as the title of the UIActionSheet since there is no message there. 
For **iOS8+** - Send both title and message to the UIAlertController
For **Android** - If there is a title sent, pass both title and message to the AlertDialog. If there is no title, pass the message as title for the AlertDialog

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
:+1:

**Pull request merged**
