### PR TITLE
fix-next(android): popExit fragment animation

### PR DESCRIPTION
**Pull request by manoldonev**
Fix issues with "popExit" fragment animation when FragmentTransaction.setCustomAnimations(...) are used.
Also reworked fix from https://github.com/NativeScript/NativeScript/pull/6339 

Kudos to @MartoYankov for the assistance! 👍

### CODE REVIEW

**Comment by manoldonev** [comment]
test tests_app_transitions animations

**Comment by manoldonev** [comment]
test tests_app_transitions animations

**Comment by SvetoslavTsenov** [comment]
test --ignore tests_app_transitions animations api19 api 21 api23

**Comment by SvetoslavTsenov** [comment]
test --ignore tests_app_transitions animations api19 api21 api22 api23

**Pull request merged**
