### PR TITLE
webpack  improvements

### PR DESCRIPTION
**Pull request by hdeshev**
Fix several issues I encountered while bundling modules code.

The biggest one being that webpack can't handle dynamic `require` calls at compile time and needs a hint.

The way to make this work is to expose an API that registers well-known modules such as:

```typescript
global.registerModule("ui/dialogs", () => require("ui/dialogs"));
```

The latter `require` gets changed by webpack to its own require function, and we can easily resolve it at runtime.

### CODE REVIEW

**Comment by hdeshev** [comment]
Ping @enchev -- I changed the globals lazy loading code to use `utils/module-loader` too.

**Comment by enchev** [comment]
:+1:

**Comment by hdeshev** [comment]
run ci

**Comment by hdeshev** [comment]
Killed the utils/module-loader module and moved the 3 functions to globals.

**Pull request merged**
