### PR TITLE
fix(connectivity): making startMonitoring() behave on iOS as on Android

### LINKED ISSUE #4579: Connectivity's startMonitoring behaviour is different between platforms
When I use `connectivity.startMonitoring` on Android it implicitly triggers the callback with the current state of the connectivity when I call `startMonitoring`.

On iOS, it will trigger the callback only when the connectivity changes.

I like the Android behaviour, but that being said iOS sounds more like how it should work.

Anyhow, shouldn't the behaviour be the same in between the two platforms ?

PS: both scenarios are tested on real devices, not simulators.

```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.1.2           │ 3.1.2          │ Up to date  │
│ tns-core-modules │ 3.1.0           │ 3.1.0          │ Up to date  │
│ tns-android      │ 3.1.1           │ 3.1.1          │ Up to date  │
│ tns-ios          │ 3.1.0           │ 3.1.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

### PR DESCRIPTION
**Pull request by surdu**
On Android, when calling startMonitor it will immediately fire the callback with the current state. Now it does the same on iOS.
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md. 

## What is the current behavior?
When calling `connectivity. startMonitoring()` on Android, the callback will fire immediately with the current state. This behaviour is not present on iOS.

## What is the new behavior?
Calling `connectivity. startMonitoring()` on iOS will also fire the callback immediately with the current state.

Fixes #4579 .

Please note that I didn't write any tests for this as I didn't know how to. The tests for this component seem just a stub for documentation purpose. If anyone can please point me in the right direction with the tests, I'll gladly write them.

Also didn't manage to test with my own app, as I'm blocked by #6372 😢

### CODE REVIEW

**Comment by vakrilov** [comment]
test

**Comment by vakrilov** [comment]
test

**Comment by vakrilov** [comment]
test

**Comment by vakrilov** [comment]
test

**Comment by surdu** [comment]
Any idea in what version of NS will this be released? It will be a nice addition to simplify a little the code in our projects 😅

**Pull request merged**
