### PR TITLE
Fix: setting text in Span to number/null/undefined

### PR DESCRIPTION
**Pull request by vakrilov**
Resolves NativeScript/nativescript-angular#180

### CODE REVIEW

**Comment by vakrilov** [comment]
run ci

**Comment by vakrilov** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by enchev** [comment]
:+1:

**Pull request merged**
