### PR TITLE
refactor(animations): export declarations parser

### PR DESCRIPTION
**Pull request by sis0k0**

### CODE REVIEW

**Comment by SvetoslavTsenov** [comment]
run animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
run animations

**Comment by SvetoslavTsenov** [comment]
run animations

**Comment by SvetoslavTsenov** [comment]
run animations

**Comment by SvetoslavTsenov** [comment]
run animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by vchimev** [comment]
animation

**Comment by vchimev** [comment]
animation

**Comment by SvetoslavTsenov** [comment]
run animations

**Comment by SvetoslavTsenov** [comment]
run animations

**Comment by SvetoslavTsenov** [comment]
run animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
run animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
👍

**Pull request merged**
