### PR TITLE
placeholder creatingView event fixed + tests

### LINKED ISSUE #772: Placeholder with an id attribute doesn't call creatingView handler
I have the following main-page.xml
```xml
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
  <StackLayout>
    <Placeholder id="chartView" creatingView="creatingView"  />
  </StackLayout>
</Page>
```

and the following main-page.js
```js
var vmModule = require("./main-view-model");
function pageLoaded(args) {
    var page = args.object;
    page.bindingContext = vmModule.mainViewModel;
}

function creatingView(args) {
    console.log("creatingView is called");

    var nativeView = new UILabel();
    nativeView.text = "Native";
    args.view = nativeView;
}

exports.creatingView = creatingView;
exports.pageLoaded = pageLoaded;
```

When the id attribute is before the creatingView the handler is never called. If I switch them like that 
```  <Placeholder creatingView="creatingView"  id="chartView"  /> ``` the handler is called.

### PR DESCRIPTION
**Pull request by enchev**
Fixed #772

### CODE REVIEW

**Comment by hshristov** [comment]
:+1:

**Comment by dtopuzov** [comment]
run ci

**Comment by atanasovg** [comment]
I remember @hamorphis changed this on purpose (it actually was a requested fix). Here is [his fix](https://github.com/NativeScript/NativeScript/commit/07138182b43673d457c56db1b0a6cd7fe9eb5371).

**Comment by enchev** [comment]
Actually @hshristov resolved the crash with measure in other place and now we can remove this safely in my opinion.

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
We've decided to measure views in ios no matter if they have native view
or not.

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by hamorphis** [comment]
:+1:

**Pull request merged**
