### PR TITLE
[Do not merge] Allow more flexible nesting of elements (TabView->Frame->Page)

### PR DESCRIPTION
**Pull request by hshristov**
- iOS Frame, Page and TabView measure/layout methods no longer used. We now rely on the iOS to position these controls. As a result `width, height, minWidth, minHeight, margins` won't be respected on these controls
- iOS layouts for ViewContollers now implemented with UILayoutGuild (requires iOS 9)
- iOS layout positioning now respects native properties like automaticallyAdjustsScrollViewInsets, edgesForExtendedLayout, extendedLayoutIncludesOpaqueBars, navigationBar.translucent, tabBar.translucent
- iOS 11 safeAreas layout support
- Page parents layout updated after page is layout so that inner layout flags are correct set
- View now expose ios namespace with layoutView method and UILayoutViewController used by page, tab-view and application module
- ViewBase now expose viewController property that should be set from all widgets that are using viewcontroller internally (like Page, Frame, TabView)
- ViewBase now sets ios property to either the view returned from createNativeView or to nativeViewProtected
- Removed frame-tests.ios.ts - those tests are now invalid
- Added new layout tests inside page-tests.ios.ts
- Commented few asserts in scroll-view-tests
- fragment.transitions now use animation/transition start to add fragments to waitingQueue. Before we did it manually in navigate/goBack. This way we can reuse the fragment.transition when calling showDialog.
- Builder expose new loadViewFromEntry method (to load a view from URI)
- Frame navigation happens once frame is loaded and when attached to window (for android)
- Frame now supports Page as a child in XML (under consideration)
- Fixed GridLayout row, rowSpan, column, columnSpan properties type
- Fixed bug in GridLayout where add/remove of columns/rows won't update the internal state of the grid (backport from android when GridLayout is recycled)
- ListView will no longer invalidate layout when cells are added/removed
- Fixed bug in ScrollView ios where effectiveMinWidth/Height was multiplied by density (it is already in device pixels so no need to multiply)
- Core refactoring
- Update tests & apps runtime version
- Fixed broken unit-tests

### CODE REVIEW

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
run ci

**Comment by hshristov** [comment]
unittests

**Comment by hshristov** [comment]
uitests

**Comment by SvetoslavTsenov** [comment]
uitests

**Comment by SvetoslavTsenov** [comment]
run uitests

**Comment by hshristov** [comment]
run ci

**Comment by hshristov** [comment]
unittests

**Comment by hshristov** [comment]
run animations

**Comment by hshristov** [comment]
run unittests

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
run ci
unittests
animations

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
run ci

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
animation

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
run ci

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
run ci

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
uitests

**Comment by SvetoslavTsenov** [comment]
tests-app-ng

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
testsappng

**Comment by SvetoslavTsenov** [comment]
cuteness

**Comment by SvetoslavTsenov** [comment]
run uitests

**Comment by SvetoslavTsenov** [comment]
testsappng-ios

**Comment by SvetoslavTsenov** [comment]
testsappng

**Comment by hshristov** [comment]
testsappng-ios

**Comment by hshristov** [comment]
testsappng-ios

**Comment by SvetoslavTsenov** [comment]
testsappng

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
testappng

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
testsappng

**Comment by SvetoslavTsenov** [comment]
testsappng

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
uitests

**Comment by SvetoslavTsenov** [comment]
uitests-ios

**Comment by SvetoslavTsenov** [comment]
uitests-ios-gestures

**Comment by SvetoslavTsenov** [comment]
uitests-ios-textbase

**Comment by SvetoslavTsenov** [comment]
ios-v2

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
ios-v10

**Comment by hshristov** [comment]
cuteness

**Comment by sitefinitysteve** [comment]
GREAT STUFF!

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
all

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
uitests

**Comment by NathanWalker** [comment]
@hshristov @vakrilov will this make it into `3.4.0`?

**Comment by hshristov** [comment]
@NathanWalker Nope, this will be 4.0 but I will backport some of the fixes (frame crashes) for 3.4.1

**Comment by hshristov** [comment]
uitests, cuteness, testsappng

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
run ci

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
run ci

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
unit-tests-android

**Comment by hshristov** [comment]
run ci

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
testsappng

**Comment by SvetoslavTsenov** [comment]
testsappng

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
cuteness

**Comment by SvetoslavTsenov** [comment]
uitests

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
uitests

**Comment by SvetoslavTsenov** [comment]
testsappng

**Comment by SvetoslavTsenov** [comment]
cuteness

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
testappng

**Comment by hshristov** [comment]
testsappng

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
uitests

**Comment by SvetoslavTsenov** [comment]
testsappng

**Comment by SvetoslavTsenov** [comment]
cuteness

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
testappng

**Comment by hshristov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
uitests

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
cuteness

**Comment by SvetoslavTsenov** [comment]
testsappng

**Comment by hshristov** [comment]
uitests

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
cuteness

**Comment by SvetoslavTsenov** [comment]
uitests

**Comment by SvetoslavTsenov** [comment]
uitests

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
cuteness

**Comment by SvetoslavTsenov** [comment]
testsappng

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by hshristov** [comment]
testsappng

**Comment by hshristov** [comment]
cuteness

**Comment by hshristov** [comment]
animations

**Comment by hshristov** [comment]
uitests

**Pull request merged**
