### PR TITLE
Use AppCompat SearchView

### PR DESCRIPTION
**Pull request by vakrilov**
Related to #4272

### CODE REVIEW

**Comment by vakrilov** [comment]
uitests

**Comment by vakrilov** [comment]
run ci

**Comment by vakrilov** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
run uitests

**Comment by SvetoslavTsenov** [comment]
run uitests

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
run uitests ios

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by vakrilov** [comment]
uitests

**Pull request merged**
