### PR TITLE
feat(dialogs): Setting the size of popup dialog thru dialog options

### PR DESCRIPTION
**Pull request by slolam**
## PR Checklist

- [X] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [X] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [X] You have signed the [CLA](http://www.nativescript.org/cla).
- [X] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [X] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
There is no way to set the size of the popup dialog on iOS

## What is the new behavior?
This will allow to size the popup dialogs in iOS (primarily iPad based apps, for iPhone apps iOS ignores these properties). Here is the playground project to test https://play.nativescript.org/?template=play-ng&id=GeR8Q4&v=3

### CODE REVIEW

**Comment by vakrilov** [comment]
test

**Comment by slolam** [comment]
@vakrilov, how do I get to see the logs/details of the tests failed?  By clicking on details, it is looking for *nsbuild01.telerik.com* which seems to be a internal DNS entry.

**Comment by vakrilov** [comment]
Hey @slolam 
Can you please run `npm run api-extractor` in the root of the repo and then commit the changes in the `NativeScript.api.md` file. This is needed because this PR is changing the public API of the framework.

This should make the travis build green.

**Comment by slolam** [comment]
Hey @vakrilov,

**sh: api-extractor: command not found**  it looks like I am missing some dependencies

**Comment by slolam** [comment]
@vakrilov, never mind I did not update the npm packages. I have committed the NativeScript.api.md

**Comment by vakrilov** [comment]
test

**Comment by vakrilov** [comment]
Hey @slolam 
Seems that the CLA bot is not satisfied any more (this might happen if you have changed you git config settings or if you have pushed a commit from another machine). Can you try signing the CLA again?

**Comment by slolam** [comment]
@vakrilov, yes, I have committed from a different machine earlier. I committed again from the previous machine but still the CLA bot has hung up previous commit that had issue. Not sure how you want me to undo my previous commit. Could you please help me with this?

**Comment by vtrifonov** [comment]
test

**Comment by vtrifonov** [comment]
test

**Comment by dtopuzov** [comment]
test

**Comment by vakrilov** [comment]
Tests are green. I've checked the CLA seems to be OK.
Merging.

**Comment by slolam** [comment]
Thanks @vakrilov for your help !

**Pull request merged**
