### PR TITLE
test(platform): add missing properties to platform module documentation

### LINKED ISSUE #5707: PlatformModule Cookbook Docs need updating
The platform module cookbook documentation is missing a few other properties that are now available. https://docs.nativescript.org/cookbook/platform

I would like to update this documentation to include the following additional properties:

- `platformModule.device.language`
- `platformModule.device.manufacturer`
- `platformModule.device.region`
- `platformModule.device.uuid`
- `platformModule.screen.mainScreen.heightDIPs`
- `platformModule.screen.mainScreen.heightDIPs`

### PR DESCRIPTION
**Pull request by codethebeard**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [x] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
The platformModule cookbook documentation is missing a few properties
that are now available. https://docs.nativescript.org/cookbook/platform

## What is the new behavior?
Missing properties have been added to the platformModule cookbook documentation via the tests.

Fixes #5707

### CODE REVIEW

**Comment by manoldonev** [comment]
test

**Comment by vakrilov** [comment]
test

**Comment by janpapenbrock** [comment]
@codethebeard this has an error here:

`console.log("Screen width (DIPs): " + platformModule.screen.mainScreen.heightDIPs);`

Should be `.widthDIPs);`.

**Comment by codethebeard** [comment]
Thank you for the feedback. I apologize I had missed that. I'll make changes and resubmit.

**Pull request merged**
