### PR TITLE
WebViewClientClass exported

### LINKED ISSUE #1196: onReceivedSslError is not exposed via the WebViewClientClass
On Android (not sure about iOS) You are missing the following class function.
```
WebViewClientClass.prototype.onReceivedSslError = function(webView, handler, error) {
       // Code should call a user callback obviously; and if that callback returns true you proceed
       // otherwise  you do cancel (the default)
      //  handler.cancel() or  handler.proceed();
};
```
And since WebViewClientClass is NOT exposed via an export; you can't monkey patch it in; leaving the worst possible choice of having to manually modify a runtime class.   :angry:

### PR DESCRIPTION
**Pull request by enchev**
Fixed #1196

### CODE REVIEW

**Comment by enchev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by vakrilov** [comment]
:+1:

**Pull request merged**
