### PR TITLE
 fix: label text wrapping inside flexbox layout

### PR DESCRIPTION
**Pull request by manoldonev**
Fixes https://github.com/NativeScript/NativeScript/issues/4834
Fixes https://github.com/NativeScript/NativeScript/issues/3834

Should be tested with https://github.com/NativeScript/tns-core-modules-widgets/pull/121

@SvetoslavTsenov added new test page for the ui tests app:  https://github.com/NativeScript/NativeScript/commit/6400e11d4bd99fa288e789d6cac16952695f7b6e

### CODE REVIEW

**Comment by manoldonev** [comment]
test branch_widgets#mdonev/tnslabel-layout-fix

**Comment by dtopuzov** [comment]
test branch_widgets#mdonev/tnslabel-layout-fix

**Comment by dtopuzov** [comment]
test branch_widgets#mdonev/tnslabel-layout-fix

**Comment by SvetoslavTsenov** [comment]
test branch_widgets#mdonev/tnslabel-layout-fix

**Pull request merged**
