### PR TITLE
feat(application-settings): implemented allKeys method

### LINKED ISSUE #6210: application-settings: access all keys
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes: [https://stackoverflow.com/questions/39582576/in-application-settings-iterate-the-key-values](https://stackoverflow.com/questions/39582576/in-application-settings-iterate-the-key-values)

### Tell us about the problem
Right now there seems to be no way to get a representation of all key-value pairs that are currently stored in the application-settings. So it is not possible to say "delete all data for keys that starts with 'data-2018-08-21-...' " because we do not know which keys are stored and we like to iterate through all the keys to check which ones should be removed.

On native side, there seems to be a way to achieve this:
[https://developer.android.com/reference/android/content/SharedPreferences#getAll()](https://developer.android.com/reference/android/content/SharedPreferences#getAll())
[https://developer.apple.com/documentation/foundation/nsuserdefaults/1415919-dictionaryrepresentation?language=objc](https://developer.apple.com/documentation/foundation/nsuserdefaults/1415919-dictionaryrepresentation?language=objc)

### Which platform(s) does your issue occur on?
Both

### PR DESCRIPTION
**Pull request by surdu**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [x] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
There is no way to get all key from application-settings.

## What is the new behavior?
There is a method `.allKeys()` that returns all the keys from application-settings.

Fixes #6210.

### CODE REVIEW

**Comment by vakrilov** [comment]
test

**Comment by vakrilov** [comment]
test

**Comment by vakrilov** [comment]
test

**Comment by radeva** [comment]
Hi @surdu ,

Congratulations on being one of the winners in the {N} First-time contributors contest! 

You can claim your prize by contacting us at nativescriptwinners[at]progress.com not later than Nov 30th 2018 . Make sure you send us the following info: 
👉Your full name 
👉Your email 
👉Your country or residence 

Best regards,
The NativeScript Team

**Comment by surdu** [comment]
O, wow! That's awesome! Thank you 😁

**Pull request merged**
