### PR TITLE
Fixed getting object properties too many times.

### PR DESCRIPTION
**Pull request by nsndeck**

### CODE REVIEW

**Comment by hdeshev** [comment]
We can probably add a test for this using a property getter that raises an exception when called more than once.

**Comment by nsndeck** [comment]
run ci

**Comment by hshristov** [comment]
:+1: for adding test

**Comment by dtopuzov** [comment]
run ci

**Comment by vakrilov** [comment]
:+1:

**Comment by ErjanGavalji** [comment]
:+1: After adding a test as @hdeshev suggested

**Pull request merged**
