### PR TITLE
android 6 support

### LINKED ISSUE #990: Android 6 Webview onReceivedError
When the method onReceivedError is call it crash the app on Android 6 devices. The official documentation say
This method was deprecated in API level 23. Use onReceivedError(WebView, WebResourceRequest, WebResourceError) instead.

```
JNI ERROR (app bug): attempt to pass an instance of com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl
 as argument 3 to void android.webkit.WebViewClient.onReceivedError(android.webkit.WebView, int, java.lang.String, java.lang.String)
```

### PR DESCRIPTION
**Pull request by enchev**
Fixed #990

### CODE REVIEW

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by ErjanGavalji** [comment]
:+1:

**Pull request merged**
