### PR TITLE
feat(textview): added maxLines property

### LINKED ISSUE #4315: TextView Support For maxLines and minLines
Does TextView have support for ```minLines``` and ```maxLines``` attributes? This would be a really useful feature for multi-line text.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/45908414-textview-support-for-maxlines-and-minlines?utm_campaign=plugin&utm_content=tracker%2F12908224&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F12908224&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by surdu**
## PR Checklist

- [X] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [X] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [X] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [X] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
TextView doesn't have a way to limit the maximum number of lines

## What is the new behavior?
TextView has a way to limit the maximum number of lines by specifying the `maxLines` property.

Fixes #4315

### CODE REVIEW

**Comment by surdu** [comment]
Didn't managed to test this on a device because my dev environment is not working due to #7942

**Comment by MartoYankov** [comment]
@surdu The `EditableTextBase` class is a base class for both the `TextView` and the `TextField`. The `TextField` component is a single line editable component, so it doesn't make much sense to have this property. Further, on iOS the `UITextField` doesn't have a `textContainer` property, so trying to set the property on `TextField` for iOS will cause a crash.

I think you should move this property to the `TextView` component specifically.

**Comment by surdu** [comment]
@MartoYankov done

**Comment by MartoYankov** [comment]
Hi, @surdu , sorry for the delayed response. This looks good, however I see that the feature behaves differently on iOS and Android right now.

* On iOS the values -1 and 0 work and reset the value allowing infinite lines.
* On Android -1 crashes the app and 0 doesn't allow even one line.

The -1 value on Android is also the default one, so it's important to not crash when resetting CSS rules for example.

Also the 0 value should reset to the default behavior. I see that on Android they are doing this by [setting it to integer max value](https://stackoverflow.com/questions/5413394/reset-android-textview-maxlines).

**Comment by MartoYankov** [comment]
Also, the `tns-core-modules-package/bundle-entry-points.js` shouldn't be under source control. We have missed to add it to the git ignore. You can remove it from this PR.

**Comment by vakrilov** [comment]
Hey @surdu 
Do you think you can exclude the `tns-core-modules-package/bundle-entry-points.js` from the PR as Marto suggested.
Also as this PR is changing the Public API of the package - can you run `npm run api-extractor` and commit the changes in the `api-reports/NativeScript.api.md` file

**Comment by surdu** [comment]
@vakrilov I did the 2 changes you asked for, but I don't have time right now to look over the default value issue mentioned by Martin Yankov. I'll do my best to also fix that problem by Monday. 

Sorry, I was really busy these past weeks 😞

**Comment by surdu** [comment]
@MartoYankov Now when you set the value to 0 or -1 works the same on android as well. [Here is the commit](https://github.com/NativeScript/NativeScript/pull/7943/commits/ca7e6c4d6333419a35933b6383a8c01d864782f5) that changed the behavior on Android.

**Comment by vtrifonov** [comment]
test

**Comment by vtrifonov** [comment]
test

**Comment by dtopuzov** [comment]
test

**Comment by dtopuzov** [comment]
test --ignore

**Pull request merged**
