### PR TITLE
present and dismiss modal animated

### PR DESCRIPTION
**Pull request by enchev**
Fix for #1129

### CODE REVIEW

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
:+1:

**Comment by PanayotCankov** [comment]
:+1: Better animated than not. :)

**Comment by vchimev** [comment]
There is a problematic unit test:
```
CONSOLE INFO file:///app/tns_modules/trace/trace.js:144:29: Test: --- [PAGE.test_WhenPageIsNavigatedToItCanShowAnotherPageAsModal] OK, duration: 801.7631909996271
2016-02-09 09:16:01.282 TNSApp[9036:257231] Warning: Attempt to present <UIViewControllerImpl: 0x7fc96b663f20> on <UIViewControllerImpl: 0x7fc96de53ea0> while a presentation is in progress! 
```

**Comment by enchev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
:+1: OK to merge

**Pull request merged**
