### PR TITLE
Added Support for WebView Navigation Types

### PR DESCRIPTION
**Pull request by vbresults**
### Does your commit message include the wording below to reference a specific issue in this repo?
Fixes/Implements #1666 .

### Does your pull request have [unit tests](https://github.com/NativeScript/NativeScript/blob/master/running-tests.md)?
Yes.

### CODE REVIEW

**Comment by vbresults** [comment]
Why is the CI build failing with errors about the enums?  UIWebViewNavigationTypeLinkClicked and the similar enums are valid :?

**Comment by atanasovg** [comment]
Hey @vbresults, thanks for contributing! I think the problem here is with outdated `ios.d.ts` definitions. There we have

```
declare enum UIWebViewNavigationType {
	UIWebViewNavigationTypeLinkClicked,
	UIWebViewNavigationTypeFormSubmitted,
	UIWebViewNavigationTypeBackForward,
	UIWebViewNavigationTypeReload,
	UIWebViewNavigationTypeFormResubmitted,
	UIWebViewNavigationTypeOther
}
```

while the Runtime now understands of (see https://github.com/NativeScript/ios-runtime/issues/318)

```
declare enum UIWebViewNavigationType {
	LinkClicked,
	FormSubmitted,
	BackForward,
	Reload,
	Resubmitted,
	Other
}
```

Could you please update the `ios.d.ts` file with the correct declaration? This should fix the problem. Additionally, we will generate new file with the latest changes reflected.

**Comment by vbresults** [comment]
@atanasovg I did change the definitions to the format you mentioned in another request and it Travis said the properties don't exist: #1690

**Comment by vbresults** [comment]
@atanasovg Done

**Comment by enchev** [comment]
Great addition! Just a small suggestion. In my opinion it will be better if the definition of the enum is part of the web-view module itself instead of ui/enums. You can place the definition in the `web-view.d.ts` file and the implementation in the `web-view-common.ts`
Can you please squash your commits also?

**Comment by vbresults** [comment]
@enchev

**Comment by enchev** [comment]
run ci

**Comment by vbresults** [comment]
@enchev https://travis-ci.org/NativeScript/NativeScript/builds/114318825

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
@vbresults, this is the failure:

iOS.WEB-VIEW.testLoadStartedNavigationType (from NativeScript Tests)

Stacktrace

args.navigationType Actual: \<other\>(string). Expected: \<linkClicked\>(string)

**Comment by vbresults** [comment]
@vchimev Thanks, fixed

@enchev I would've preferred to use an enum instead of a string array in this iteration, but enums don't have a simple "contains" function and I have to write 5 lines just to check if something exists.

**Comment by enchev** [comment]
:+1:

**Pull request merged**
