### PR TITLE
Android activity events

### PR DESCRIPTION
**Pull request by enchev**

### CODE REVIEW

**Comment by hshristov** [comment]
Are we going to deprecate callback methods?

**Comment by enchev** [comment]
@hshristov  Good idea! maybe we can write in the console from the callbacks that they are deprecated?

**Comment by ligaz** [comment]
When you switch to a newer version of TypeScript compiler you can create a `@Depricated` decorator that can write to the console whenever the method is called.

**Comment by enchev** [comment]
@ligaz We use already TypeScript 1.5 and we can definitely use decorators. I'll make different pull request later.

**Comment by nsndeck** [comment]
:+1:

**Comment by ErjanGavalji** [comment]
:+1:

**Comment by enchev** [comment]
Implemented https://github.com/NativeScript/NativeScript/issues/363

**Pull request merged**
