### PR TITLE
fix(iOS): viewhierarchy stability with modals

### PR DESCRIPTION
**Pull request by NathanWalker**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?

Apps can get a "white screen of death" due to invalid and improper viewController handling on iOS related to modals.

## What is the new behavior?

Ensures that a viewController is properly closed in the case one needs to be before opening to avoid app error.

The issue here relates to {N} + Angular however it's tied to this problem in core modules ultimately.
closes https://github.com/NativeScript/nativescript-angular/issues/1546

### CODE REVIEW

**Comment by NathanWalker** [comment]
This PR is not cleanest solution however intended to provide suggestion on fix which core team may can address in best way possible. This modification has been tested pretty rigorously and has been found to be the type of fix needed to solve the issue mentioned.

**Comment by NathanWalker** [comment]
Ideally we could use https://developer.apple.com/documentation/uikit/uiviewcontroller/1621505-dismissviewcontrolleranimated with the completion handler to ensure it's fully closed in that particular condition. Not sure if worth the trouble since usually this particular condition just needs to fully close (with **no** animation) before opening again but perhaps the completion handler's could be used to tighten all this up and avoid race conditions here.

**Comment by MartoYankov** [comment]
@NathanWalker Indeed this fix doesn't look clean. It's not clear how the problem of a `viewController` not having a `view` is fixed by closing a modal view on the same `viewController`. Perhaps this fixes a certain scenario, but it's not immediately clear what it is.

My guess is that you are trying to open a modal view on a target that already opened a modal view. The iOS framework doesn't allow this by default and we are currently not supporting this. If indeed this is the case, we can discuss further if this is indeed a desirable behavior.

**Comment by vakrilov** [comment]
Hey @NathanWalker 

I have done some tests and managed to reproduce the `"Close the current modal page before showing another one!"` error consistently in 2 scenarios:

### 1. Open a modal page in the `closeCallback` of another modal page
The issue here is that we fire the `closeCallback` *before* the closing animation is completed. As you suggested - I tried using the [`dismissViewControllerAnimatedCompletion`](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621505-dismissviewcontrolleranimated) and fire the callback in the completion handler. This seems to resolve the issue. 🎉 
Also related to #5744

### 2. Open a modal page while another one is opened
The issue here is the same as before - there is already modally presented view controller, so we cannot present another one. The solution might be to have a parameter `forceCloseOpenedModal` in the `showModal()` method. The implementation should trigger a close on the current modal and use the completion callback (as in the previous case) to show the new modal. The value of this "force" param can also be true by default, which will make it behave much like what you are aiming with this PR.

[Here](https://github.com/NativeScript/NativeScript/tree/async-modals) is the branch that I have been experimenting with:
- Problem 1 is resolved thanks to [`dismissViewControllerAnimatedCompletion`](https://github.com/NativeScript/NativeScript/commit/b28837cde73897e2347e1b6d3aec385230c2351a#diff-2775a71872c1630de8108bf058a1628eR438)
- There are repro of both problems 1. and 2. in [the test-app](https://github.com/NativeScript/NativeScript/commit/b28837cde73897e2347e1b6d3aec385230c2351a#diff-930d331ce60f8ce090318a4b2f1fb5efR26).

## Next Steps
This PR triggered a good discussion. One thing is sure - `setTimeout(openNow(), 300);` is not the right approach here - that's why I'm closing this PR.
What's next:
1. Work on a PR based on [`dismissViewControllerAnimatedCompletion`](https://github.com/NativeScript/NativeScript/tree/async-modals) to resolve #5744 (problem 1)
2. Work on on the `forceClose` option (problem 2). We can set it to `true` by default or make angular always pass true when showing modals. 
3. Once the above are done. Let's see if there are more "view-hierarchy stability" issues that developers can easily hit.

Your help is much appreciated if you want to contribute on this plan.

**Comment by NathanWalker** [comment]
@vakrilov hooray! this is great news thank you so much for digging into this one 🤗 
Love your proposal 1 & 2 in `next steps` - I'll definitely try to help on those when I can.

**Pull request closed without merging**
