### PR TITLE
fix(frame-android): IllegalStateException: The specified child already has a parent

### PR DESCRIPTION
**Pull request by manoldonev**
Fixes: https://github.com/NativeScript/NativeScript/issues/7901

However, note that while this change fixes this specific issue we have only verified NativeScript works with androidx@1.0.0 package versions at this point.

### CODE REVIEW

**Comment by manoldonev** [comment]
test tsapps ngapps

**Comment by manoldonev** [comment]
test tsapps ngapps

**Comment by manoldonev** [comment]
test --ignore tsapps ngapps api23 api28

**Comment by SvetoslavTsenov** [comment]
test --ignore tsapps#release api23 api28

**Comment by SvetoslavTsenov** [comment]
test --ignore tsapps#release api23 api28

**Comment by SvetoslavTsenov** [comment]
test --ignore uitests#release api23 api28

**Pull request merged**
