### PR TITLE
removed unneeded check and make it strict-mode compliant

### PR DESCRIPTION
**Pull request by hshristov**

### CODE REVIEW

**Comment by nsndeck** [comment]
:+1:

**Comment by ErjanGavalji** [comment]
:+1:

**Comment by vchimev** [comment]
run ci

**Comment by slavchev** [comment]
:+1:

**Comment by enchev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by PanayotCankov** [comment]
run ci

**Comment by PanayotCankov** [comment]
:+1:

**Pull request merged**
