### PR TITLE
Ensure parent directory when creating a new file

### LINKED ISSUE #1887: Parent directory not created by file-system.File.fromPath()
On Android calling `file-system.File.fromPath()` with a path which is under a non-existing directory throws an IOException

### PR DESCRIPTION
**Pull request by mbektchiev**
createNewFile throws an exception if the parent directory doesn't exist

Fixes #1887

### CODE REVIEW

**Comment by atanasovg** [comment]
:+1:

**Comment by hshristov** [comment]
:+1: after adding test @mbektchiev

**Comment by enchev** [comment]
Hey @mbektchiev,

Please sign our CLA and add small test [here](https://github.com/NativeScript/NativeScript/blob/master/apps/tests/file-system-tests.ts).

Thanks

**Comment by mbektchiev** [comment]
Done.

**Comment by enchev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Pull request merged**
