### PR TITLE
fix: #8567

### LINKED ISSUE #8567: App crash with isPassThroughParentEnabled="true" set on a FlexboxLayout
**Environment**
 - CLI: 6.5
 - Cross-platform modules: `@nativescript/core": "^6.5.1"`
 - Android Runtime: 8.0.0
 - iOS Runtime: haven't tested
 - Plugin(s): n/a
`tns info`:
```
√ Getting NativeScript components versions information...
√ Component nativescript has 6.5.0 version and is up to date.
√ Component @nativescript/core has 6.5.1 version and is up to date.
√ Component tns-android has 6.5.0 version and is up to date.
× Component tns-ios is not installed.
```

**Describe the bug**

If you put `isPassThroughParentEnabled="true"` on a `FlexboxLayout`, the app will crash with the following exception:

<details>

```
Calling js method onCreateView failed
TypeError: this.nativeViewProtected.setPassThroughParent is not a function

StackTrace:
LayoutBase.<computed>(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/layouts/layout-base.js:19:34)
at applyAllNativeSetters(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/properties/properties.js:1048:28)
at initNativeView(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/properties/properties.js:992:9)
at ViewBase.onResumeNativeUpdates(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:647:22)
at ViewBase._resumeNativeUpdates(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:278:18)
at ViewBase.onLoaded(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:232:14)
at View.onLoaded(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view/view.js:249:35)
at (file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:317:90)
at ViewBase.callFunctionWithSuper(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:310:9)
at ViewBase.callLoaded(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:317:14)
at ViewBase.loadView(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:456:18)
at (file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:234:19)
at LayoutBaseCommon.eachChildView(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:26)
at ViewCommon.eachChild(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view/view-common.js:925:14)
at ViewBase.onLoaded(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:233:14)
at View.onLoaded(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view/view.js:249:35)
at (file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:317:90)
at ViewBase.callFunctionWithSuper(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:310:9)
at ViewBase.callLoaded(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:317:14)
at ViewBase.loadView(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:456:18)
at (file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:234:19)
at ContentView.eachChildView(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/content-view/content-view.js:70:13)
at PageBase.eachChildView(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/page/page-common.js:126:40)
at ViewCommon.eachChild(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view/view-common.js:925:14)
at ViewBase.onLoaded(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:233:14)
at View.onLoaded(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view/view.js:249:35)
at Page.onLoaded(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/page/page.js:43:35)
at (file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:317:90)
at ViewBase.callFunctionWithSuper(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:310:9)
at ViewBase.callLoaded(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:317:14)
at ViewBase.loadView(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:456:18)
at ViewBase._addViewCore(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:451:18)
at ViewBase._addView(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:437:14)
at FragmentCallbacksImplementation.onCreateView(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/frame/frame.js:700:19)
at FragmentClass.onCreateView(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/frame/fragment.js:29:38)
at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
at com.tns.Runtime.callJSMethod(Runtime.java:1160)
at com.tns.Runtime.callJSMethod(Runtime.java:1138)
at com.tns.Runtime.callJSMethod(Runtime.java:1134)
at com.tns.FragmentClass.onCreateView(FragmentClass.java:54)
at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
</details>

Additionally, it appears that button taps propagate to parent containers. If you run the playground (https://play.nativescript.org/?template=play-tsc&id=iixpoJ&v=2) from the documentation https://docs.nativescript.org/ui/gestures (added here), at least on android, a single tap of the button will trigger the onWrapLayoutTapped function. If I'm reading [this](https://medium.com/@NativeNick/nativescript-event-bubbling-a-short-story-of-propagating-tap-f0c1ccec2752) correctly, this does not appear to be the intended behavior (`So if you tap on our button, you will notice that no event will be propagated to its parents`). Note that there's an issue [here](https://github.com/NativeScript/NativeScript/issues/8467) but it was auto closed and not responded to. I was hoping to find out if this is a bug or if it is now intended behavior (I posted there as well as the slack channel but did not get a response).

**To Reproduce**

See this playground.
https://play.nativescript.org/?template=play-tsc&id=cc97of

For the app crash - put `isPassThroughParentEnabled="true"` on a `FlexboxLayout`. Remove that or switch to a different layout and the app will function normally.

For the button tap propagation - tap the buttons in the [playground](https://play.nativescript.org/?template=play-tsc&id=iixpoJ&v=2) from the [gestures documentation](https://docs.nativescript.org/ui/gestures), see the background color change and the console log.

**Expected behavior**
App should not crash when using `isPassThroughParentEnabled="true"` on a `FlexboxLayout`.
Button taps should not propagate to parent container(s). (Or should they?)

**Additional context**
https://github.com/NativeScript/NativeScript/issues/8467

### PR DESCRIPTION
**Pull request by dimitrisdnr**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
When setting 'isPassThroughParentEnabled' property to FlexboxLayout, a exception is thrown.

## What is the new behavior?
Property 'isPassThroughParentEnabled' will work for FlexboxLayout.

Fixes/Closes #8567 .

### CODE REVIEW

**Comment by NathanWalker** [comment]
@dimitrisdnr on this one, like you've done for others, possible to add a sample in here https://github.com/NativeScript/NativeScript/tree/master/e2e/ui-tests-app/app/flexbox which uses  `isPassThroughParentEnabled` to lock in the expected behavior 👍

**Comment by dimitrisdnr** [comment]
@NathanWalker Done. Thanks a lot for guiding me, I'll try to include samples from now on.

**Comment by NathanWalker** [comment]
Excellent work @dimitrisdnr thank you! We'll queue this up with some others we're aiming for 👍

**Comment by NathanaelA** [comment]
@dimitrisdnr - Can you retarget this to the new master repo.   Sorry we did some major refactoring and we would love to get these changes...

**Comment by DimitrisRK** [comment]
> @dimitrisdnr - Can you retarget this to the new master repo. Sorry we did some major refactoring and we would love to get these changes...

@NathanaelA I created a new PR for this one here: #8798 . This PR can now be closed.

**Pull request closed without merging**
