### PR TITLE
Fixed Android back navigation error

### LINKED ISSUE #9912: Calling js method onTransitionEnd failed TypeError: Cannot read property 'frame' of null
### Issue Description

During back navigation on Android the app crashes with ```Calling js method onTransitionEnd failed TypeError: Cannot read property 'frame' of null```. It happens also if the back navigation happens after the app send to background then opened again.

### Reproduction

_No response_

### Relevant log output (if applicable)

_No response_

### Environment

```yaml
OS: macOS 11.6.5
CPU: (4) x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
Shell: /bin/zsh
node: 18.0.0
npm: 8.7.0
nativescript: 8.2.3

# android
java: 11.0.15
ndk: Not Found
apis: 22, 28, 30, 31
build_tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2, 30.0.3, 31.0.0
system_images:
  - android-29 | Google APIs Intel x86 Atom

# ios
xcode: 13.2.1/13C100
cocoapods: 1.11.3
python: 2.7.16
python3: 3.9.12
ruby: 2.6.3
platforms:
  - DriverKit 21.2
  - iOS 15.2
  - macOS 12.1
  - tvOS 15.2
  - watchOS 8.3
```

### Dependencies

```json
"dependencies": {
    "@klippa/nativescript-http": "^3.0.2",
    "@master.technology/permissions": "^2.0.1",
    "@nativescript-community/geocoding": "^3.1.0",
    "@nativescript-community/insomnia": "^2.0.2",
    "@nativescript-community/ui-collectionview": "^4.0.48",
    "@nativescript-community/ui-image": "^4.1.6",
    "@nativescript-community/ui-mapbox": "^6.2.15",
    "@nativescript-community/ui-pulltorefresh": "^2.5.0",
    "@nativescript-community/universal-links": "^2.0.7",
    "@nativescript/appversion": "^2.0.0",
    "@nativescript/background-http": "^6.0.0",
    "@nativescript/core": "^8.2.2",
    "@nativescript/datetimepicker": "^2.1.10",
    "@nativescript/firebase": "^11.1.3",
    "@nativescript/geolocation": "^8.0.2",
    "@nativescript/imagepicker": "^1.0.6",
    "@nativescript/iqkeyboardmanager": "^2.0.0",
    "@nativescript/localize": "^5.0.4",
    "@nativescript/secure-storage": "^3.0.0",
    "@nativescript/theme": "^3.0.2",
    "@nstudio/nativescript-cardview": "^2.0.1",
    "@oliverphaser/nativescript-bitmap-factory": "^1.0.8",
    "@triniwiz/nativescript-image-zoom": "^4.1.1",
    "@yoonit/nativescript-camera": "^3.2.1",
    "d3-ease": "^3.0.1",
    "decode-google-map-polyline": "^1.0.1",
    "haversine-distance": "^1.2.1",
    "moment": "^2.29.2",
    "nativescript-effects": "^3.0.0",
    "nativescript-phone": "^3.0.3",
    "nativescript-soft-keyboard": "^2.2.0",
    "nativescript-vue": "^2.9.1",
    "rxjs": "^7.5.5",
    "vuex": "^3.6.2"
  },
  "devDependencies": {
    "@nativescript/android": "8.2.2",
    "@nativescript/ios": "8.2.3",
    "@nativescript/webpack": "~5.0.6",
    "nativescript-vue-template-compiler": "~2.9.0"
  }
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

### PR DESCRIPTION
**Pull request by oliverphaser**
Calling js method onTransitionEnd failed TypeError: Cannot read property 'frame' of null

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/DevelopmentWorkflow.md#running-unit-tests-application.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/tools/notes/WritingUnitTests.md.

## What is the current behavior?

During back navigation on Android the app crashes with "Calling js method onTransitionEnd failed TypeError: Cannot read property 'frame' of null". It happens also if the back navigation happens after the app send to background then opened again.

## What is the new behavior?
No error anymore.

Fixes #9912.

### CODE REVIEW

**Comment by oliverphaser** [comment]
@cla-bot check

**Review by oliverphaser — COMMENTED** [review]
I had the https://github.com/NativeScript/NativeScript/issues/9096 (similar error but on Android) during back navigation. The following changes solved my issue.

**Comment by farfromrefug** [comment]
@oliverphaser may i ask you to try a different fix? The thing is that your issue might actually be the issue here https://github.com/NativeScript/NativeScript/blob/e9015f4fe37eebbbe57334d66fa584f2569363d3/packages/core/ui/frame/fragment.transitions.android.ts#L666 but the test to ignore it might not be good.
Could you try to:
* remove your fix
* change on line 669:
```ts
if (!entries) {
    return;
}
```
with 
```ts
if (!entries || entries.size === 0) {
    return;
}
```

If it fixes it, then it is a better fix because we wrap all those "fixes" in the same `if` test

**Comment by oliverphaser** [comment]
Thanks @farfromrefug, I just saw that there is already a fix for this issue.

**Pull request closed without merging**
