### PR TITLE
chore(apps): add modal-navigation-app for ui testing

### PR DESCRIPTION
**Pull request by manoldonev**
Add new app for ui test automation of modal navigation scenarios. [Properly formated] scenario listing can be found here: https://gist.github.com/manoldonev/277f136556d0ec80cdf8194b3dad6f0b but I'm pasting them below as well:

1. Show modal dialog with frame
	1.1. Navigate to modal second page within modal dialog
		1.1.1. Go back
	1.2. Show nested modal dialog
		1.2.1. Close nested modal dialog
	1.3. Show nested modal dialog with frame
		1.3.1. Close nested modal dialog
	1.4. Close modal dialog
2. Show modal dialog
	2.1. Show nested modal dialog
		2.1.1. Close nested modal dialog
	2.2. Show nested modal dialog with frame
		2.2.1. Close nested modal dialog
	2.3. Close modal dialog
3. Show modal tabview
	3.1. Navigate to second page within tab item frame
		3.1.1. Go back
	3.2. Show nested modal dialog
		3.2.1. Close nested modal dialog
	3.3. Show nested modal dialog with frame
		3.3.1. Close nested modal dialog
	3.4. Close modal dialog
4. Navigate to second page within root frame
	4.1. Show modal dialog with frame
		4.1.1. Navigate to second page within modal dialog
			4.1.1.1. Go back
		4.1.2. Show nested modal dialog
			4.1.2.1. Close nested modal dialog
		4.1.3. Show nested modal dialog with frame
			4.1.3.1. Close nested modal dialog
		4.1.4. Close modal dialog
	4.2. Show modal dialog
		4.2.1. Show nested modal dialog
			4.2.1.1. Close nested modal dialog
		4.2.2. Show nested modal dialog with frame
			4.2.2.1. Close nested modal dialog
		4.2.3. Close modal dialog
	4.3. Go back

	
ROOT TABVIEW SCENARIOS (change root modulename to tab-root/tab-root in app.ts):

[Same as above]

### CODE REVIEW

**Comment by manoldonev** [comment]
run ci

**Comment by vchimev** [comment]
How about an `e2e` folder to store this and similar apps, for example: https://github.com/NativeScript/nativescript-angular/tree/master/e2e.
This way we could add the tests along with the application.

**Comment by manoldonev** [comment]
Removed references to frame.topmost in the app and logged new feature item https://github.com/NativeScript/NativeScript/issues/5407

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
test

**Comment by MartoYankov** [comment]
We can remove the README and LICENSE and rename modal-tab-page to modal-tab-root for consistency.

**Comment by manoldonev** [comment]
👍 for latest changes @vchimev

**Comment by manoldonev** [comment]
test

**Comment by vchimev** [comment]
Thanks, Guys! :)

**Pull request merged**
