### PR TITLE
refactor(android): no transition duration to 1ms

### PR DESCRIPTION
**Pull request by manoldonev**
Fixes: https://github.com/NativeScript/NativeScript/issues/7481

### CODE REVIEW

**Comment by manoldonev** [comment]
test tsapps ngapps nested_frame_navigation api23 ios12

**Comment by dtopuzov** [comment]
test tsapps ngapps nested_frame_navigation api23 ios12

**Comment by SvetoslavTsenov** [comment]
test --ignore tsapps nested_frame_navigation api23 ios12

**Comment by SvetoslavTsenov** [comment]
test --ignore tsapps nested_frame_navigation api23 ios12

**Comment by SvetoslavTsenov** [comment]
test --ignore tests_app_transitions_android api23

**Pull request merged**
