### PR TITLE
feat(animation): support animating width/height properties (WIP)

### PR DESCRIPTION
**Pull request by justindujardin**
Add support for animating width/height View properties.

Implements #1764

- [x] Supports animating PercentageLength properties
- [x] Works with Angular component animations
- [x] Works on Android
- [x] Works on iOS
- [x] Add example to examples app
  - [x] basic height animation
  - [x] height animation in stack layout
  - [x] animation curves tester
  - [x] details disclosure effect
- [x] Verify works as expected with "auto" height
- [x] Verify works with all built-in animation curves
- [ ] Verify keyframe animation support
- [x] Add unit tests
  - [x] PercentLength.parse tests to verify input/output expectations
  - [x] View.animate resolves percentage width/height relative to parent
  - [x] View.animate works with pixel value strings
  - [x] View.animate works with number dip inputs
  - [x] View.animate works with number dip inputs
  - [ ] Keyframe animation tests
  - [ ] Spring curve tests (iOS has separate codepaths for spring)

## Use with View.animate

```typescript
view.animate({
  width:'40%', 
  height: '400px',
  duration: 300
});
```

## Use with Angular

```typescript
@Component({
  moduleId: module.id,
  selector: 'cool-component',
  template: `
      <Button (tap)="details = !details" text="Toggle"></Button>
      <Image backgroundColor="blue" height="100%"
             [@sizingImage]="details == true ? 'details' : 'summary'"></Image>
  `,
  animations: [
    trigger('sizingImage', [
      state('details', style({height: '55%'})),
      state('summary', style({height: '100%'})),
      transition('summary => details', animate('200ms ease-out')),
      transition('details => summary', animate('200ms ease-in')),
    ]),
  ]
})
export class CoolComponent {
  details = true;
}
```

**Unfinished thoughts**

There are a few limitations that could be lifted, but need input:

- Layout values are not interpolated for Views on iOS. StackLayout height animations will "jump" a little. Would need to add some kind of periodic JS callback during the animation to do this.
- View originX/Y values are different on iOS/Android by default. This means that height/width animations will act differently by default if the user does not specify origins explicitly on the View being animated.

### CODE REVIEW

**Comment by justindujardin** [comment]
I added a few UI tests. With `StackLayout` there is a difference between how the animation looks on iOS and Android.

# Android
A time update function is required to animate `height` on a view, so the layout updates smoothly as you would expect.
animate-height-stack-layout-android

# iOS
There is no time update callback in Javascript, so the value isn't animated as far as the {N} Layout is concerned.
animate-height-stack-layout-ios

## What to do?
It looks like there are some options to add a javascript callback that could update the Layout value over time on iOS, but it would almost certainly slow things down and add complexity.

It's not clear to me if it's worth slowing down all height animations to satisfy a particular layout constraint. e.g. this poor animation would have to pay for a feature it doesn't need. 😭 
animate-height-disclosure-ios

Thoughts?

**Comment by justindujardin** [comment]
Added a few more examples to test corner cases:

**Scrolling text view with animated header**
> animate-transition-height-ios

**Animation curves**
> animate-height-curves-android

**Comment by jogboms** [comment]
This really awesome work @justindujardin. Amazing feat in progress!! 🔥🔥🔥

**Comment by justindujardin** [comment]
This PR is ready for review now. 👍

**Comment by jogboms** [comment]
@hshristov @vakrilov @tsonevn someone show really give this a review. 😄

**Comment by jogboms** [comment]
Yay!! All checks have passed. @justindujardin the awesome. 👍 💯

**Comment by justindujardin** [comment]
I missed testing a few things, so I put this back in WIP, but I still welcome reviews/feedback.

**Comment by SvetoslavTsenov** [comment]
Hey @justindujardin, thank you for your contribution. We are going to execute some tests and review the PR.

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
uitests

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by jogboms** [comment]
@justindujardin 🥇🥇🥇

**Comment by davecoffin** [comment]
is this scheduled for release?

**Comment by RoyiNamir** [comment]
How can I know if this already available and on which version?

**Comment by vchimev** [comment]
Hello All,

Great work on this pull-request! You can follow the progress on it [here](https://github.com/NativeScript/NativeScript/pull/5147).

Our main concerns with this implementation are related to performance. I am afraid that we have not had the time to measure and investigate it due to higher priority tasks. However, we are aware of its importance and wide demand, that is why we would like to invest further efforts and improve this feature as well as the animations, in general.

This has not been scheduled for release yet. Currently, we are working on the 4.1 roadmap, so I hope we could get it there. Please follow the [issue](https://github.com/NativeScript/NativeScript/issues/1764) and this [pull-request](https://github.com/NativeScript/NativeScript/pull/5147) for any comments and updates.

**Pull request merged**
