### PR TITLE
feat(animation): support animating width/height properties

### PR DESCRIPTION
**Pull request by vchimev**
Original PR https://github.com/NativeScript/NativeScript/pull/4917 by @justindujardin that implements https://github.com/NativeScript/NativeScript/issues/1764.

### CODE REVIEW

**Comment by vchimev** [comment]
Hello All,

Great work on this pull-request!

Our main concerns with this implementation are related to performance. I am afraid that we have not had the time to measure and investigate it due to higher priority tasks. However, we are aware of its importance and wide demand, that is why we would like to invest further efforts and improve this feature as well as the animations at all.

This has not been scheduled for release yet. Currently, we are working on the 4.1 roadmap, so I hope we could get it there. Please follow the [issue](https://github.com/NativeScript/NativeScript/issues/1764) and this [pull-request](https://github.com/NativeScript/NativeScript/pull/5147) for any comments and updates.

**Comment by MisterBrownRSA** [comment]
When are you planning on giving this Pull Request some daylight?

**Comment by farfromrefug** [comment]
@vchimev i have read through the PR and I dont really see anything that would impact performances if not using width or height in into animations. I understand you want to improve the whole animation system but in the meantime it would still be very useful to get that PR in.
And it would allow us not to use tricks like rxjs or tweenjs  which might have worst performance consequences.

**Comment by Jonarod** [comment]
Hey !!
What is to be done for this to be released ???
I can see some UI tests were not successful, however seems like the page hosting details is down... so it is not possible to check where it fails.

@vchimev could you bring some details back ?

Also, I agree with @farfromrefug here, as of today we use funky workarounds like Tween.js to animate width and height, for what I understand from @justindujardin 's code is that it should not be worse than todays hacks... Maybe you could release that PR with some beta warnings like **to use with caution - still in beta** or whatever: the community will surely help to stabilize it.

I can totally understand concerns (plus I can't see why tests fail...) but the PR is over 1 year old now :sweat_smile: 

Thanks !!

**Comment by elvticc** [comment]
Hello! Thank you very much for your improvements to NativeScript. This feature is essential for many developers, could you implement it please? Would you have a planned date?

**Comment by jbarnabe** [comment]
Thanks @MartoYankov and @SvetoslavTsenov for this improvement! Looking forward to use it.

**Comment by danielnitu** [comment]
Is this scheduled for future releases? I'm not able to use it in 5.4.3 and couldn't find more details elsewhere

**Comment by MartoYankov** [comment]
@danielnitu Sorry for the late reply. This will be available in the 6.0 release.

**Pull request merged**
