### PR TITLE
chore(travis): do not run unit tests app in Travis

### PR DESCRIPTION
**Pull request by vchimev**
The {N} team's having a hard time maintaining the unit tests app execution in Travis CI.
The main problem is that PROFILING, HTTP, WEB-VIEW tests fail randomly due to timeouts, caused by the unstable environment.
The unit tests app execution remains by default on PRs in {N} Jenkins CI.

### CODE REVIEW

**Comment by NathanaelA** [comment]
Rather than disable the entire set of unit tests in Travis, why not just disable those three tests in Travis so the rest of the unit testing continues on the Android emulator?

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
Thanks for the comment, @NathanaelA! Yes, this is an option.

Let me step into more details why we decide to stop executing unit tests in Travis than my initial description.

The [Travis CI](https://travis-ci.org/NativeScript/NativeScript/branches) build for the [NativeScript/NativeScript](https://github.com/NativeScript/NativeScript) repository executes the unit test application only for Android, however, in our Jenkins CI we execute the unit test application for both Android and iOS.
- As seen, there is a duplication of what we execute (for Android) and we think it will be better to stick to Jenkins as it is our primarily CI system and as a single source of truth.
- This duplication causes us double time and efforts to maintain similar builds in two different CIs. We want to use these time and efforts for tasks bringing more value to the framework.
- The Travis CI build (only Android) takes ~25 (in the best case) mins and the Jenkins CI build (both Android and iOS) takes ~10 min. Basically, it does not bring any value to wait 25 min for something we already know in 10 min.

I would like to mention once again that Jenkins CI build triggers by default on each pull request and we trigger it explicitly for external contribution. Also that it is expected the tests to be executed prior any pull request following our [development workflow](https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#tests).

**Comment by NathanaelA** [comment]
Awesome, thanks for filling me in!    Yeah in this case you are correct; no reason to maintain something that gives you no benefits and just eats developer time.

**Pull request merged**
