### PR TITLE
Update index.ts

### PR DESCRIPTION
**Pull request by facetious**
Adding `g` to this RE allows different `Worker` targets within the same file.

### CODE REVIEW

**Comment by facetious** [comment]
@cla-bot check

**Comment by facetious** [comment]
What on earth. How did I end up no longer on the "CLA signed" list? 😂

**Comment by edusperoni** [comment]
@facetious the cla has changed since {N} joined OpenJS. If you haven't contributed since then, that might be the case.

**Comment by facetious** [comment]
@edusperoni Thanks, I guess that makes sense. Summon bot again, go!

@cla-bot check

**Review by rigor789 — APPROVED** [review]

**Comment by rigor789** [comment]
Nice catch @facetious !

**Pull request merged**
