### PR TITLE
original string restored from text property

### PR DESCRIPTION
**Pull request by enchev**

### CODE REVIEW

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vakrilov** [comment]
:+1:

**Comment by guliashki** [comment]
Tested with QSF. Works as expected.

**Comment by vchimev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by ginev** [comment]
Looks better. Aren't you using the "originalString" property somewhere else?

**Pull request merged**
