### PR TITLE
Ios10 switch

### PR DESCRIPTION
**Pull request by PanayotCankov**
Add checks if some key iOS methods has been promoted to properties in the iOS 10 SDK.

### CODE REVIEW

**Comment by dtopuzov** [comment]
💯

**Comment by jasssonpet** [comment]
How would this work with a property that returns a function?

**Comment by PanayotCankov** [comment]
It won't. It is mentioned in the "getter" docs it won't work with delegate type properties.
:"(

**Comment by jasssonpet** [comment]
Can we check the Xcode version or the iOS SDK version being used and make that the condition for branching? I think it should be possible.

**Comment by PanayotCankov** [comment]
I am not sure. We can't use the iOS version nor the Xcode, but if we have the SDK version it should be ok.

**Pull request merged**
