### PR TITLE
Exclude generated d.ts files from initial file list generation.

### PR DESCRIPTION
**Pull request by hdeshev**
A tiny build script bugfix...

### CODE REVIEW

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by PanayotCankov** [comment]
:+1:

**Comment by dtopuzov** [comment]
run ci

**Comment by hdeshev** [comment]
run ci

**Comment by hdeshev** [comment]
run ci

**Pull request merged**
