### PR TITLE
Slider CSS color and background-color support fixed

### LINKED ISSUE #1010: Slider CSS color/background-color support
Slider color and background-color not working properly. For example:
```CSS
Slider {
 color: red;
 background-color: red;
}
```

### PR DESCRIPTION
**Pull request by enchev**
Fixed #1010

### CODE REVIEW

**Comment by dtopuzov** [comment]
run ci

**Comment by vakrilov** [comment]
:+1:

**Comment by nsndeck** [comment]
:+1:

**Comment by enchev** [comment]
run ci

**Pull request merged**
