### PR TITLE
Change from "classic" TS 1.6 imports to the default resolution scheme.

### PR DESCRIPTION
**Pull request by hdeshev**
- Use relative imports in place of most of our absolute ones.
- Add "private" ambient modules for modules that we need to import using
an absolute path (e.g. when app/.../test-something.ts needs to import
ui/styling/style-scope)

### CODE REVIEW

**Comment by ErjanGavalji** [comment]
:+1:

**Comment by hshristov** [comment]
:+1:

**Comment by hdeshev** [comment]
run ci

**Comment by hdeshev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Pull request merged**
