### PR TITLE
#4349: support accessibility escape gesture for going back or dismissing modal

### PR DESCRIPTION
**Pull request by m-abs**
Implements #4349 

This adds the function **accessibiliityPerformEscape()** to UINavigationControllerImpl on iOS.

When VoiceOver is enabled on an iOS device, this function is called by the platform when the escape gesture (two finger Z) is performed.
If the frame can go back, frame.goBack() is called.
If the current page have an modal, that modal is closed.

### CODE REVIEW

**Comment by m-abs** [comment]
Question:
Android triggers the `activityBackPressedEvent` which can be cancelled, when the back button is pressed, should this do something similar?

Maybe `accessibilityPerformEscapeEvent`?

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
run uitests

**Comment by SvetoslavTsenov** [comment]
run uitests ios

**Comment by SvetoslavTsenov** [comment]
Hey @m-abs .Thanks for the contribution!
We are going to run some e2e test on this PR and we will review it in a few days

**Comment by hshristov** [comment]
@m-abs 
Why do you need to implement this method 'accessibilityPerformEscape'?
According to documentation it will do the default action if no responder in the chain handles it. So we don't have any view that handle this method it will fallback to dismiss modal page or going back.

And in my opinion it should be first close modal page if any and if not then `frame.goBack()`

**Comment by m-abs** [comment]
Hi @hshristov,

I'm closing this PR, as it is a result of a misunderstanding and misidentification of a problem in our app.

For some reason, which I've yet to identify, the escape gesture doesn't trigger the default behavior in our {N}-2.5 + ng project..
A locally applied patch like this in 2.5.5, solved the problem for us.

I should of cause have tested unpatched {N} in a demo project before making this PR.

I did after your reply and it works as expected without patching, if I just create a project with `tns create hello --ng`.

**Pull request closed without merging**
