### PR TITLE
test(modal-navigation): add close modal, modal layout and root layout tests

### PR DESCRIPTION
**Pull request by vchimev**
This issue has occurred: https://github.com/NativeScript/NativeScript/issues/5703.

### CODE REVIEW

**Comment by vchimev** [comment]
branch_modal_navigation#djenkov/modal-navigation-tests

**Comment by vchimev** [comment]
branch_modal_navigation#djenkov/modal-navigation-tests

**Comment by SvetoslavTsenov** [comment]
test branch_modal_navigation#djenkov/modal-navigation-tests

**Comment by vchimev** [comment]
test branch_modal_navigation#djenkov/modal-navigation-tests

**Comment by vchimev** [comment]
test branch_modal_navigation#djenkov/modal-navigation-tests

**Comment by vchimev** [comment]
Ping @manoldonev, @MartoYankov, @SvetoslavTsenov.

**Comment by vchimev** [comment]
test branch_modal_navigation#djenkov/modal-navigation-tests

**Comment by vchimev** [comment]
test branch_modal_navigation#djenkov/modal-navigation-tests

**Pull request merged**
