### PR TITLE
Correct TabView icon rendering mode

### LINKED ISSUE #1148: iOS TabView Icon rendering mode set wrong
`renderingMode` on `UIImage` is a read-only property: https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIImage_Class/#//apple_ref/occ/instp/UIImage/renderingMode

As a result of this the icon will always be gray on the tab view on iOS.

You guys are trying to set it here, but it doesn't work: https://github.com/NativeScript/NativeScript/blob/79f009fb383c5f933e62e1768d3930fd090371ac/ui/tab-view/tab-view.ios.ts#L246

The correct way is to use `imageWithRenderingMode`.

### PR DESCRIPTION
**Pull request by rclai**
Fixes #1148.

### CODE REVIEW

**Comment by enchev** [comment]
run ci

**Comment by rclai** [comment]
Is there something I need to do about the failed test of @ns-bot? I can't see the details.

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
Hey @rclai,

We have a problem with random failing tests for Android. No need to do anything extra.

**Comment by enchev** [comment]
run ci

**Comment by hamorphis** [comment]
:+1:

**Comment by ErjanGavalji** [comment]
:+1:

**Comment by hshristov** [comment]
:+1:

**Comment by vakrilov** [comment]
:+1:

**Pull request merged**
