### PR TITLE
Remove ListView cell highlight in iOS.

### PR DESCRIPTION
**Pull request by kvelikov**

### CODE REVIEW

**Comment by dtopuzov** [comment]
run ci

**Comment by hamorphis** [comment]
:+1:

**Comment by ErjanGavalji** [comment]
:+1:

**Comment by rclai** [comment]
Why didn't this make it to 1.5?

**Comment by gverschuur** [comment]
Yeah, the same here. It appears the cell is autohighlighted with no way to turn it off?

**Pull request closed without merging**
