### PR TITLE
Fix hint color in iOS

### PR DESCRIPTION
**Pull request by PanayotCankov**
the attributedPlaceholder and placeholder was set following two very distinct paths.

### CODE REVIEW

**Comment by vakrilov** [comment]
run ci

**Comment by vakrilov** [comment]
run ci

**Comment by vchimev** [comment]
android

**Comment by vchimev** [comment]
ci android

**Comment by vchimev** [comment]
ci android

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
ci android

**Comment by vchimev** [comment]
The tests app crashes on iOS.

**Comment by PanayotCankov** [comment]
run ci

**Comment by PanayotCankov** [comment]
@vchimev I figured it out, NSMutableAttributedString was returning null at "" string in one test and was given a number in another. Let's see how the builds will go now.

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
run ci

**Pull request merged**
