### PR TITLE
Search bar hint color

### PR DESCRIPTION
**Pull request by Nathanaela**
This commit should be pushed under the proper email address.

### CODE REVIEW

**Comment by ErjanGavalji** [comment]
@Nathanaela, perfect!

Would you cover these with tests as well?

I'll try to describe the testing mechanism we use in NativeScript shortly below.

These are not pure unit tests as we are dealing with UI components here, which to a great extent dependent on the underlying platform and do not have very much logic in them. Hence, we actually have an application that gets run on real devices, emulator/simulators to verify the functionality written. This application is maintained in the [apps/tests]
(https://github.com/NativeScript/NativeScript/tree/master/apps/tests) folder. To verify, its results get parsed through the platform-specific output readers.

When the source built via the `grunt` command, several npm packages get created in the `bin/dist` folder of the NativeScript repo. These are (skipping version parts of the names):

1. tns-core - has the JavaScript cross-platform modules of the NativeScript framework
2. tns-sample-* contain some test/demo applications the team use internally for testing
3. ths-template-* have templates that will get used once we have the [template-selection functionality](https://github.com/NativeScript/nativescript-cli/issues/374) implemented in the command-line interface
4. tns-definitions - contains the TypeScript definition files for use when writing a TypeScript application

The tns-core and the tns-samples-tests packages are the ones, related to the topic of running tests in NativeScript. Unpacking them over a newly created NativeScript application and running it would run the tests application.

Here is a sample command-line aiding with the extraction. Set the proper paths and run it from within the folder of your NativeScript application:

`repodir=~/github/nativescript/nativescript && version=1.0.0 && app=tests && rm -rf app && mkdir app && cd app && tar -xzvf $repodir/Modules/tns-template-$app\-$version.tgz && mv package/* . && rmdir package && tar -xzvf $repodir/Modules/tns-core-$version.tgz && mv package tns_modules`

A tests file must be listed in array in the [testRunner.ts file](https://github.com/NativeScript/NativeScript/blob/master/apps/tests/testRunner.ts). A tests file must include the TKUnit module (a custom built unit-testing engine). TKUnit is very much similar to the other unit testing frameworks.

**Comment by Nathanaela** [comment]
I have no issue creating a test; if I can figure out how.        I looked at the existing SearchBar test   **/tests/ui/search-bar/search-bar-tests.ts** and I don't see any test for the searchbar "hint" property, how exactly are you testing for "visual" changes.     I've looked through a handful of the tests and I don't see anything that tests for a actual visual changed.      All this patch does is allow you to change the color of the search hint text.    Can you point me to a test that deals with a purely visual change; and I'll model a test after that...

**Comment by Nathanaela** [comment]
The command line
```repodir=~/github/nativescript/nativescript && version=1.0.0 && app=tests && rm -rf app && mkdir app && cd app && tar -xzvf $repodir/Modules/tns-template-$app\-$version.tgz && mv package/* . && rmdir package && tar -xzvf $repodir/Modules/tns-core-$version.tgz && mv package tns_modules```

Appears to be out of date; No **Modules** folder, and no tns-template-test.x.x.x.tgz, it is now tns-sample-test.x.x.x.tgz

On my windows box this is the batch file I use to do the above:
```
@echo off
set VERSION=1.0.0

rd /Q /S app
7z x ..\repos\NativeScript\bin\dist\tns-samples-tests-%VERSION%.tgz 
7z x .\tns-samples-tests-%VERSION%.tar 
del /q tns-samples-tests-%VERSION%.tar
ren package app

7z x ..\repos\NativeScript\bin\dist\tns-core-%VERSION%.tgz
7z x tns-core-%VERSION%.tar
del /q tns-core-%VERSION%.tar
ren package tns_modules
move tns_modules app

mkdir app\App_Resources
xcopy /S /E App_Resources app\App_Resources
```

   Makes sure after you do the ```TNS create test``` you MOVE the ```APP_Resources``` folder up to the parent folder of the app so that it continues to exist for each time you run the update as this update batch file deletes the "app" folder, and recreates it each time and the APP_Resources is needed to compile the android version...   

----

Directly relating to this have you figured out a way to test visual components visually -- or is a test for this pull request not possible at the time.

**Comment by Nathanaela** [comment]
I created a test for the other pull request I did recently; so I understand now how to make & run the tests.  But my question still stands; is their a way to test for purely visual design.  i.e. this pull request only allows you to change the "color" of the hint text; so unless their is a way to test the difference in the test runner; I'm still not seeing a way to make a test currently for this pull request.

**Comment by ErjanGavalji** [comment]
@Nathanaela, (sorry for the delay with the reply), one approach is to check whether it got applied in the native side (check the [SegmentedBar tests](https://github.com/NativeScript/NativeScript/tree/master/apps/tests/ui/segmented-bar) for an example)

**Comment by Nathanaela** [comment]
Thanks -- I'll take a look at that test and see if I can get a test for this...

**Comment by Nathanaela** [comment]
@ErjanGavalji test has been added and is passing.  I assume the conflict must be in the testrunner.ts file as I had to add the search-bar test to my test runner on my branch...

**Comment by dtopuzov** [comment]
bot, please run CI

**Comment by ErjanGavalji** [comment]
run ci

**Comment by ErjanGavalji** [comment]
Accepting the result, for the build fails due to an internal breaking change in the android runtime.

@Nathanaela, that was a great patience to help clear the contribution process! Thanks for that and for the input as well!

One last step, can you please, rebase onto master and force-push towards the branch?

Thanks,
Erjan Gavalji

**Comment by Nathanaela** [comment]
I've rebased my changes into one commit; and then rebased it onto master.

**Comment by ErjanGavalji** [comment]
run ci

**Pull request merged**
