### PR TITLE
Add a dts for color/known-colors.

### LINKED ISSUE #815: d.ts  for known-colors.js
There is only a `color.d.ts` and d.ts for `known-colors.js` is missing.

### PR DESCRIPTION
**Pull request by hdeshev**
Fixes #815

### CODE REVIEW

**Comment by hdeshev** [comment]
run ci

**Comment by hdeshev** [comment]
run ci

wtf

**Comment by hdeshev** [comment]
run ci

**Comment by hdeshev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by enchev** [comment]
:+1:

**Pull request merged**
