### PR TITLE
Fixed issue #814.

### PR DESCRIPTION
**Pull request by nsndeck**

### CODE REVIEW

**Comment by enchev** [comment]
:+1:

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by nsndeck** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
iOS - === ALL TESTS COMPLETE === 915 OK, 0 failed
android - === ALL TESTS COMPLETE === 927 OK, 2 
```
FAILED: scrollView.horizontalOffset Numbers are not close enough. Actual: 0 Expected: 100 Delta: 0.1 --- [SCROLL-VIEW.test_scrollToVerticalOffset_with_animation] FAILED: scrollView.verticalOffset Numbers are not close enough. Actual: 0 Expected: 100 Delta: 0.1 
```

**Comment by enchev** [comment]
run ci

**Pull request merged**
