### PR TITLE
Add support for snapshot

### PR DESCRIPTION
**Pull request by hshristov**
Fix Layout class getMeasuredWidth & getMeasuredHeight methods
Move some classes to widgets
Fix API17 tests

### CODE REVIEW

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
tns-core-modules/ui/core/view-common.ts[918, 37]: block is empty

**Comment by vchimev** [comment]
widgets

**Comment by vchimev** [comment]
widgets

**Comment by vchimev** [comment]
```
tns-core-modules/ui/transition/transition.d.ts(24,144): error TS2503: Cannot find namespace 'android'.
tns-core-modules/ui/transition/transition.d.ts(24,179): error TS2503: Cannot find namespace 'android'.
tns-core-modules/ui/transition/transition.d.ts(24,222): error TS2503: Cannot find namespace 'android'.
```

**Comment by hshristov** [comment]
widgets

**Comment by vchimev** [comment]
widgets

**Comment by hshristov** [comment]
run ci

**Comment by vchimev** [comment]
widgets

**Comment by vchimev** [comment]
widgets

**Pull request merged**
