### PR TITLE
BindingContext set two times on adding item to ListView. Fixed issue #410.

### PR DESCRIPTION
**Pull request by nsndeck**

### CODE REVIEW

**Comment by hamorphis** [comment]
:+1:

**Comment by hdeshev** [comment]
:+1:

**Comment by hdeshev** [comment]
run ci

**Comment by vakrilov** [comment]
:+1:

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Pull request merged**
