### PR TITLE
fix(android-textfield): returnPress fired twice for GO/SEARCH/SEND actions

### PR DESCRIPTION
**Pull request by manoldonev**
Fixes https://github.com/NativeScript/NativeScript/issues/4461

It seems Android fires a complementary IME_ACTION_UNSPECIFIED action each time IME_ACTION_GO, IME_ACTION_SEARCH, or IME_ACTION_SEND is fired. As we need the IME_ACTION_UNSPECIFIED logic for a different fix (https://github.com/NativeScript/NativeScript/issues/5121) the proposal is to remove the explicit GO/SEARCH/SEND checks and handle them through the IME_ACTION_UNSPECIFIED.

Tested this change on physical Google Pixel and Samsung S8 phone, as well as on emulators with API levels 22, 23, and 25.

### CODE REVIEW

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
test

**Comment by dtopuzov** [comment]
test

**Comment by dtopuzov** [comment]
test

**Comment by dtopuzov** [comment]
test

**Comment by dtopuzov** [comment]
test

**Pull request merged**
