### PR TITLE
Exposed UIApplicationDelegate and removed default implementation

### PR DESCRIPTION
**Pull request by enchev**

### CODE REVIEW

**Comment by vakrilov** [comment]
:+1:

**Comment by dtopuzov** [comment]
:+1:

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
Implemented https://github.com/NativeScript/NativeScript/issues/432

**Pull request merged**
