### PR TITLE
Fixed: jumping action bar reported in #2941

### LINKED ISSUE #2941: Using IconFonts in ActionBar + navigation leeds to displaced icons
Related to [this comment](https://github.com/NativeScript/NativeScript/issues/2256#issuecomment-254712715)

Code to reproduce [here ](https://github.com/tskweres/tinder-clone)

Description: 
- Create two pages with ActionBarItem that are using **IconFonts**
- Navigate from pageA to pageB with action-bar set

```
<ActionItem ios.position="right" (tap)="goBack()"> 
    <Button #backicon text="&#xE87D;" class="material-icons backicon"></Button> 
</ActionItem>
```

result: Icon is loaded at one place at the initial moment - then the icon is displaced by x (where x is the icon size)

### PR DESCRIPTION
**Pull request by tzraikov**
Fixes #2941

### CODE REVIEW

**Comment by vakrilov** [comment]
@tzraikov Will this fix NativeScript/nativescript-angular#504 as well?

**Comment by tzraikov** [comment]
@vakrilov It could :). Will check.

**Comment by tzraikov** [comment]
run ci

**Comment by tskweres** [comment]
is this in the latest 2.4 release from a few days ago or will it be in 2.5?

**Comment by tzraikov** [comment]
@tskweres The fix is not included in 2.4. It will be included in our upcoming 2.5 release. You can get the fix by using our @next release. Just update your project with `tns update next`.

**Comment by kinggolf** [comment]
This appears to be fixed with NS 2.5 release based on some quick testing.

**Comment by tskweres** [comment]
When is the 2.5 announcement / rollout expected? Just curious

**Comment by kinggolf** [comment]
@tskweres 2.5 was released just today. I downloaded it only about one hour ago.

**Pull request merged**
