### PR TITLE
feat: bundle workflow support

### PR DESCRIPTION
**Pull request by manoldonev**
Related to: https://github.com/NativeScript/NativeScript/issues/7320

### CODE REVIEW

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#bundle-workflow nested_frame_navigation_api23 nested_frame_navigation_ios12 modal_navigation#bundle-workflow modal_navigation_api23 modal_navigation_ios12 animation#bundle-workflow animation_api23 animation_ios12

**Comment by SvetoslavTsenov** [comment]
We need to fix  `npm run tsc` command since it will try to transpile files in tests app and since we have changed the references.d.ts to point in modules for d.ts the job is failing to package modules.

**Comment by manoldonev** [comment]
@vchimev can you look into https://github.com/NativeScript/NativeScript/pull/7337#issuecomment-500306409?

**Comment by vchimev** [comment]
test

**Comment by vchimev** [comment]
test

**Comment by vchimev** [comment]
test

**Comment by vchimev** [comment]
test

**Comment by vchimev** [comment]
test

**Comment by vchimev** [comment]
test

**Comment by vchimev** [comment]
test

**Comment by vchimev** [comment]
test

**Comment by vchimev** [comment]
test

**Comment by vchimev** [comment]
test

**Comment by dtopuzov** [comment]
test

**Comment by dtopuzov** [comment]
test

**Comment by dtopuzov** [comment]
test --ignore uitestsapp#${sha1} cuteness#${sha1} api23 ios12

**Comment by dtopuzov** [comment]
test

**Comment by dtopuzov** [comment]
test

**Comment by SvetoslavTsenov** [comment]
test --ignore uitests#${sha1} cuteness#${sha1} api23 ios12

**Comment by dtopuzov** [comment]
test --ignore uitests#${sha1} cuteness#${sha1} api23 ios12

**Comment by dtopuzov** [comment]
test --ignore uitests#${sha1} cuteness#${sha1} api23 ios12

**Comment by dtopuzov** [comment]
test --ignore uitests#${sha1} cuteness#${sha1} api23 ios12

**Comment by dtopuzov** [comment]
test --ignore uitests#${sha1} cuteness#${sha1} api23 ios12 nativescript-dev-webpack#latest

**Comment by dtopuzov** [comment]
test nativescript-dev-webpack#latest nativescript_dev_webpack#latest

**Comment by dtopuzov** [comment]
test --ignore uitests#${sha1} cuteness#${sha1} api23 ios12

**Pull request merged**
