### PR TITLE
Changes to layout and grid-layout

### PR DESCRIPTION
**Pull request by nemephx**
Add void return statements to existing functions and definitions for TypeScript completeness
Add new APIs
Fix comment typos

Changes are for #288

### CODE REVIEW

**Comment by ErjanGavalji** [comment]
:+1:

**Comment by enchev** [comment]
:+1:

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by enchev** [comment]
Changes will be merged in https://github.com/NativeScript/NativeScript/pull/863

**Pull request closed without merging**
