### PR TITLE
[Do not merge - WIP] feat(android): Add a 'profiling: lifecycle' to track startup times

### PR DESCRIPTION
**Pull request by PanayotCankov**
Consider this a very light-weight mode of 'profiling: timline'.
By adding in the `app/package.json` a:
```
{
  "profiling": "lifecycle"
}
```
The app will print out the time it takes to launch the app.
In future, we can add times for navigation, time to respond user interaction, etc.

### CODE REVIEW

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
testsappng

**Comment by vchimev** [comment]
test branch_modal_navigation#profiling-lifecycle

**Comment by vchimev** [comment]
test branch_modal_navigation#profiling-lifecycle

**Comment by vchimev** [comment]
test branch_modal_navigation#profiling-lifecycle

**Comment by vchimev** [comment]
Closing this pull request as it tries to hack, but not to resolve the problems:

- *What exactly do we want to measure on launch of Android application?"* - the pull request doesn't give an answer to this question. It moves raising of `displayedEvent` later, but this does not guarantee that it will include the drawing of all elements in the application. For example, the ListView draws its elements async, so some of them take part of the `displayedEvent`, but not all. In order to count on the `displayEvenet` approach, we would need to draw all the native elements sync.

- `rootView._onAttachedToWindow()` is hijacked only for the case when the root of the application is `Frame`. We would need a more general approach for all the scenarios.

Attached timeline-view times, please remove the `.log` extension in order to preview:
[template-hello-world-ng@4.0.0.html.log](https://github.com/NativeScript/NativeScript/files/1942915/template-hello-world-ng.4.0.0.html.log)
[template-hello-world-ng@pr.html.log](https://github.com/NativeScript/NativeScript/files/1942916/template-hello-world-ng.pr.html.log)

**Pull request closed without merging**
