### PR TITLE
feat(config): cli.additionalPathsToClean to clean other paths with 'ns clean'

### PR DESCRIPTION
**Pull request by Archez**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/DevelopmentWorkflow.md#running-unit-tests-application.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/tools/notes/WritingUnitTests.md.

## What is the new behavior?

Add typing info for the existing `additionalPathsToClean` property that `ns clean` reads from.

### CODE REVIEW

**Comment by rigor789** [comment]
Thanks @Archez! I do wonder if we should add this under the `cli` key (and update cli to match)?

**Comment by Archez** [comment]
@rigor789 I was thinking the same when adding it. Wasn't sure if that would be considered a breaking change, but I can make an update so the top level config isn't bloated.

**Comment by rigor789** [comment]
@Archez it would be fine - this was never a documented feature (I added it experimentally, but we can totally move it to the `cli` key)

**Comment by NathanWalker** [comment]
@rigor789 @Archez I moved it under `cli` key as completely agree makes sense there and super useful! Needed something like this recently. Will merge to include with 8.2 and @rigor789 we can adjust this is cli to look for it in the `cli` key prior to release.

**Pull request merged**
