### PR TITLE
refactor(e2e): rename modal-layout to modal-layout-root

### PR DESCRIPTION
**Pull request by vchimev**
`nativescript-dev-webpack@0.12.0` registers default application modules: https://github.com/NativeScript/nativescript-dev-webpack/blob/f9bbea94929d780c0d4aa12c620b91495a015c0f/register-modules.js

This is to add a non-default module to registered webpack modules.

### CODE REVIEW

**Comment by MartoYankov** [comment]
Isn't it better to just rename the files to modal-layout-root.ext?

**Comment by vchimev** [comment]
Yes, it is - similar to [`modal-tab-root`](https://github.com/NativeScript/NativeScript/tree/4.0.0/e2e/modal-navigation/app/modal-tab).

**Comment by SvetoslavTsenov** [comment]
tests modal_navigation android@latest

**Comment by SvetoslavTsenov** [comment]
test modal_navigation#vchimev/e2e/modal-navigation/bundle android@latest

**Comment by SvetoslavTsenov** [comment]
test modal_navigation#vchimev/e2e/modal-navigation/bundle android@rc

**Comment by SvetoslavTsenov** [comment]
test modal_navigation#vchimev/e2e/modal-navigation/bundle

**Comment by SvetoslavTsenov** [comment]
test modal_navigation#vchimev/e2e/modal-navigation/bundle

**Comment by SvetoslavTsenov** [comment]
test modal_navigation#vchimev/e2e/modal-navigation/bundle

**Pull request merged**
