### PR TITLE
Fixed jumpy navigation between pages in iOS.

### PR DESCRIPTION
**Pull request by hshristov**
Fixed after application suspend/resume the UI was not restored.
Fixed modal-views page

### CODE REVIEW

**Comment by enchev** [comment]
:+1:

**Comment by vakrilov** [comment]
:+1:

**Comment by dtopuzov** [comment]
:+1:

**Comment by alejandro-heredia-coderoad-com** [comment]
I can't yet see the fix. Page still jumps after navigation between pages.

**Pull request merged**
