### PR TITLE
feat(android): androidX support

### PR DESCRIPTION
**Pull request by ADjenkov**
Migrate tns-core-modules to support androidX:
 - Migrate tns-core-module
 - Migrate test apps (_**package.json update needed to target proper widgets and platform declarations**_)
 - Migrate tns-platform-declarations

Part of https://github.com/NativeScript/NativeScript/issues/7027

### CODE REVIEW

**Comment by SvetoslavTsenov** [comment]
test tns-core-modules-widgets#androidx

**Comment by SvetoslavTsenov** [comment]
test tns-core-modules-widgets#androidx

**Comment by SvetoslavTsenov** [comment]
test branch-tns-core-modules-widgets#androidx

**Comment by ADjenkov** [comment]
test package_version#androidx

**Comment by ADjenkov** [comment]
test tns-core-modules-widgets@androidx tns-android@androidx

**Comment by SvetoslavTsenov** [comment]
test tns-core-modules-widgets@androidx tns-android@androidx android@ androidx --ignore 
branch-modal-navigation_android#androidx  branch_uitests_android#android branch-nested-frame-navigation_android#androidx

**Comment by SvetoslavTsenov** [comment]
test tns-core-modules-widgets@androidx tns-android@androidx android@androidx --ignore
branch-modal-navigation_android#androidx branch_uitests_android#android branch-nested-frame-navigation_android#androidx

**Comment by SvetoslavTsenov** [comment]
test tns-core-modules-widgets#androidx tns-android#androidx android#androidx --ignore
branch-modal-navigation_android#androidx branch_uitests_android#android branch-nested-frame-navigation_android#androidx

**Comment by SvetoslavTsenov** [comment]
test tns-core-modules-widgets#androidx tns-android#androidx android#androidx --ignore
branch-modal-navigation_android#androidx branch_uitests_android#android branch-nested-frame-navigation_android#androidx api17 api23 api28

**Comment by SvetoslavTsenov** [comment]
test tns-core-modules-widgets#androidx tns-android#androidx android#androidx --ignore
branch-modal-navigation_android#androidx branch_uitests_android#androidx branch-nested-frame-navigation_android#androidx api17 api23 api28

**Comment by ADjenkov** [comment]
test tns-core-modules-widgets#androidx tns-android#androidx android#androidx --ignore
branch-modal-navigation_android#androidx branch_uitests_android#androidx branch-nested-frame-navigation_android#androidx api17 api23 api28

**Comment by SvetoslavTsenov** [comment]
test --ignore tns-core-modules-widgets#androidx tns-android#androidx android#androidx 
branch-modal-navigation_android#androidx branch_uitests_android#androidx branch-nested-frame-navigation_android#androidx api17 api23 api28

**Comment by SvetoslavTsenov** [comment]
test --ignore tns-core-modules-widgets#androidx tns-android#androidx android#androidx
branch-modal-navigation_android#androidx branch_uitests_android#androidx branch-nested-frame-navigation_android#androidx api17 api23 api28

**Comment by SvetoslavTsenov** [comment]
test --ignore tns-core-modules-widgets#androidx tns-android#androidx android#androidx branch-modal-navigation_android#androidx branch_uitests_android#androidx branch-nested-frame-navigation_android#androidx api17 api23 api28

**Comment by SvetoslavTsenov** [comment]
test --ignore tns-core-modules-widgets#androidx tns-android#androidx android#androidx branch-modal-navigation_android#androidx branch_uitests_android#androidx branch-nested-frame-navigation_android#androidx api17 api23 api28 tns_platform_declaration#androidx

**Comment by SvetoslavTsenov** [comment]
test --ignore tns-core-modules-widgets#androidx tns-android#androidx android#androidx branch-modal-navigation_android#androidx branch_uitests_android#androidx branch-nested-frame-navigation_android#androidx api17 api23 api28 tns_platform_declarations#androidx

**Comment by SvetoslavTsenov** [comment]
test --ignore tns-core-modules-widgets#androidx tns-android#androidx android#androidx  branch_uitests_android#androidx api17 api23 api28 tns_platform_declarations#androidx

**Comment by dtopuzov** [comment]
test --ignore tns-core-modules-widgets#androidx tns-android#androidx android#androidx branch_uitests_android#androidx api17 api23 api28 tns_platform_declarations#androidx

**Comment by SvetoslavTsenov** [comment]
test --ignore tns-core-modules-widgets#androidx tns-android#androidx android#androidx branch_uitests_android#androidx api17 api23 api28 build_tns_platform_declarations

**Comment by SvetoslavTsenov** [comment]
test tns-core-modules-widgets#androidx tns-android#androidx android#androidx  api17 api23 api28 tns_platform_declarations@androidx

**Comment by SvetoslavTsenov** [comment]
test tns-core-modules-widgets#androidx tns-android#androidx android#androidx api17 api23 api28 tns_platform_declarations@androidx

**Comment by SvetoslavTsenov** [comment]
test tns-core-modules-widgets#androidx tns_android#androidx tns_android#androidx android#androidx api17 api23 api28 tns_platform_declarations@androidx

**Comment by ADjenkov** [comment]
test tns-core-modules-widgets#androidx tns_android#androidx tns_android#androidx android#androidx api17 api23 api28 tns_platform_declarations@androidx

**Comment by SvetoslavTsenov** [comment]
test tns-core-modules-widgets#androidx tns_android#androidx tns_android#androidx android#androidx api17 api23 api28 tns_platform_declarations@androidx

**Comment by ADjenkov** [comment]
test tns-core-modules-widgets#androidx tns_android#androidx tns_android#androidx android#androidx api17 api23 api28 tns_platform_declarations@androidx

**Comment by ADjenkov** [comment]
test tns-core-modules-widgets#androidx tns_android#androidx tns_android#androidx android#androidx api17 api23 api28 tns_platform_declarations@androidx

**Comment by SvetoslavTsenov** [comment]
test tns-core-modules-widgets#androidx tns_android#androidx tns_android#androidx android#androidx api17 api23 api28 tns_platform_declarations@androidx

**Comment by SvetoslavTsenov** [comment]
test

**Comment by SvetoslavTsenov** [comment]
test tns_android#androidx tns_android#androidx android#androidx api17 api23 api28 tns_platform_declarations@androidx upload_test_reports

**Comment by SvetoslavTsenov** [comment]
test tns_android#androidx tns_android#androidx android#androidx api17 api23 api28 tns_platform_declarations@androidx upload_test_reports

**Comment by ADjenkov** [comment]
test tns_android#androidx tns_android#androidx android#androidx api17 api23 api28 tns_platform_declarations@androidx upload_test_reports

**Comment by manoldonev** [comment]
test tns_android#androidx tns_android#androidx android#androidx api17 api23 api28 tns_platform_declarations@androidx upload_test_reports

**Comment by SvetoslavTsenov** [comment]
test tns_android#androidx tns_android#androidx android#androidx api17 api23 api28 tns_platform_declarations@androidx upload_test_reports

**Comment by SvetoslavTsenov** [comment]
test --ignore tns_android#androidx android#androidx api17 api23 api28 tns_platform_declarations@androidx uitests#androidx cuteness#androidx modal_navigation#androidx nested_frame_navigation#androidx animations tests_app_transitions_android sdk_js_android qsf_android sample_android_background_services_android nativescript_worker_loader_demo_android groceries_android sdk_ng_android ngapps_android  upload_test_reports

**Comment by SvetoslavTsenov** [comment]
test --ignore tns_android#androidx android#androidx api17 api23 api27 tns_platform_declarations@androidx uitests#androidx cuteness#androidx modal_navigation#androidx nested_frame_navigation#androidx animations tests_app_transitions_android sdk_js_android qsf_android sample_android_background_services_android nativescript_worker_loader_demo_android groceries_android sdk_ng_android ngapps_android upload_test_reports

**Comment by ADjenkov** [comment]
test --ignore tns_android#androidx android#androidx api17 api23 api27 tns_platform_declarations@androidx uitests#androidx cuteness#androidx modal_navigation#androidx nested_frame_navigation#androidx animations tests_app_transitions_android sdk_js_android qsf_android#androidx sample_android_background_services_android nativescript_worker_loader_demo_android groceries_android sdk_ng_android ngapps_android upload_test_reports

**Comment by SvetoslavTsenov** [comment]
test --ignore tns_android#androidx android#androidx api17 api23 api27 tns_platform_declarations@androidx uitests#androidx cuteness#androidx modal_navigation#androidx nested_frame_navigation#androidx animations tests_app_transitions_android sdk_js_android qsf#androidx sample_android_background_services_android nativescript_worker_loader_demo_android groceries_android sdk_ng_android ngapps_android upload_test_reports

**Comment by SvetoslavTsenov** [comment]
test --ignore tns_android#android android#androidx api17 api23 api27 tns_platform_declarations@androidx  sample_android_background_services#androidx nativescript_worker_loader_demo#androidx

**Comment by SvetoslavTsenov** [comment]
test --ignore tns_android#android android#androidx api17 api23 api27 tns_platform_declarations@androidx sample_android_background_services#androidx nativescript_worker_loader_demo#androidx  upload_test_reports

**Comment by SvetoslavTsenov** [comment]
test --ignore build_tns_android#trifonov/android-x-only build_android#androidx api17 api23 api27 tns_platform_declarations@androidx sample_android_background_services#androidx nativescript_worker_loader_demo upload_test_reports

**Comment by SvetoslavTsenov** [comment]
test --ignore build_tns_android#trifonov/android-x-only build_android#androidx api17 api23 api27 tns_platform_declarations@androidx sample_android_background_services#androidx nativescript_worker_loader_demo upload_test_reports

**Comment by SvetoslavTsenov** [comment]
test --ignore build_tns_android#trifonov/android-x-only build_android#androidx api17 api23 api27 tns_platform_declarations@androidx sample_android_background_services#androidx nativescript_worker_loader_demo upload_test_reports

**Comment by SvetoslavTsenov** [comment]
test --ignore branch_tns_android#trifonov/android-x-only branch_android#androidx api17 api23 api27 tns_platform_declarations@androidx sample_android_background_services#androidx nativescript_worker_loader_demo upload_test_reports

**Comment by SvetoslavTsenov** [comment]
test --ignore  branch_android#trifonov/android-x-only api17 api23 api27 tns_platform_declarations@androidx sample_android_background_services#androidx nativescript_worker_loader_demo upload_test_reports

**Comment by SvetoslavTsenov** [comment]
test --ignore tns_android#android android#androidx api17 api23 api27 tns_platform_declarations@androidx sample_android_background_services#androidx nativescript_worker_loader_demo#androidx upload_test_reports

**Comment by SvetoslavTsenov** [comment]
test --ignore tns_android#android android#androidx api17 api23 api27 tns_platform_declarations@androidx sample_android_background_services_android#androidx nativescript_worker_loader_demo upload_test_reports

**Comment by SvetoslavTsenov** [comment]
test --ignore branch_android#trifonov/android-x-only   qsf_android#androix api17 api23 api27 upload_test_reports

**Comment by SvetoslavTsenov** [comment]
test --ignore branch_android#trifonov/android-x-only qsf_android#androix api17 api23 api27 upload_test_reports

**Comment by SvetoslavTsenov** [comment]
test --ignore branch_android#trifonov/android-x-only qsf_android#androix api17 api23 api27 upload_test_reports tns-platform-declarations#androix

**Comment by SvetoslavTsenov** [comment]
test --ignore branch_android#trifonov/android-x-only qsf_android#androidx api17 api23 api27 upload_test_reports tns-platform-declarations#androidx

**Comment by SvetoslavTsenov** [comment]
test --ignore  android#/tns-dist/tns-android/PR/eeaf515ecf644bfd53f64afdf4561a36eeeb1baf/tns-android.tgz qsf_android#androidx api17 api23 api27 upload_test_reports tns-platform-declarations#androidx

**Comment by manoldonev** [comment]
test --ignore android#/tns-dist/tns-android/PR/eeaf515ecf644bfd53f64afdf4561a36eeeb1baf/tns-android.tgz

**Comment by SvetoslavTsenov** [comment]
test --ignore android#/tns-dist/tns-android/PR/eeaf515ecf644bfd53f64afdf4561a36eeeb1baf/tns-android.tgz

**Pull request merged**
