### PR TITLE
TextField returnPress event will be raised if event KeyCode is ENTER

### LINKED ISSUE #1721: TextField returnPress event not working on Android
Just to make sure I am not doing anything wrong in my project, I have taken {N} sample Tap Achievement app and added a text field. I am trying to use returnPress event with the TextField and I cannot make it work.

`<TextField text="This is a test" returnKeyType="next" returnPress="{{ search }}"  autocorrect="false"/>`

If I attache the same function to a tap event of a button, it works:
`<Button text="TAP" tap="{{ search }}" />`

```
HelloWorldModel.prototype.search = function(){
        console.log("In search");
    }
```

I am on NativeScript 1.6 and I don't have a Mac to test this for iOS.

### PR DESCRIPTION
**Pull request by enchev**
Fixed #1721

### CODE REVIEW

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by hamorphis** [comment]
:+1:

**Pull request merged**
