### PR TITLE
fix: change #aarrggbb to #rrggbbaa

### PR DESCRIPTION
**Pull request by farfromrefug**
This makes {N} support the web standard ##rrggbbaa format
See https://github.com/NativeScript/NativeScript/issues/8517

Now are there some tests to update?

### CODE REVIEW

**Comment by NathanaelA** [comment]
I'm pretty sure their are tests; and you might also need to look at the NS-Theme; as their is the possibility that some of the theme colors is using the #aarrggbb format...

**Comment by vtrifonov** [comment]
test

**Comment by vtrifonov** [comment]
Yep, a lot of UI tests are failing. You can review them here - https://s3.amazonaws.com/ns-test-reports/index.html?prefix=reports/tns-modules/hex_colors/3942

**Comment by farfromrefug** [comment]
@vtrifonov thanks will fix them. Nice report interface !!!!

**Comment by farfromrefug** [comment]
@vtrifonov i fixed the issues and all the test are passing here.
However i dont understand the travis error :s I mean i dont see where that cant parse css color  happens.
Also please review that change https://github.com/NativeScript/NativeScript/pull/8519/commits/67c9907a6fcb7485274acc0d6536150f9bb41c7c
I did to prevent a regexp text on every single hex color.

**Comment by NathanWalker** [comment]
@farfromrefug thanks for this excellent contribution - I've long wanted this as well as much more intuitive - Given it's a breaking change we'll put this on the 7.0 release plan 👍

**Comment by NathanWalker** [comment]
@farfromrefug let's work together to get these changes into master - you may can close and reopen with target to master as would be nice to get this in {N} 7.0

**Comment by NathanWalker** [comment]
Closing this since I reimplemented on our 8.0 cleanup branch here:
https://github.com/NativeScript/NativeScript/commit/2bf86764a28950ee4d8acdbb85be79c8efed5199
@farfromrefug credit in the commit, thanks again for pushing this through, it will be in 8.0

**Pull request closed without merging**
