### PR TITLE
Fix TypeError for tabBar.items

### PR DESCRIPTION
**Pull request by onury**
In Angular/iOS project, `TabView` throws TypeError: null is not an object (evaluating 'tabBar.items.count')

Setting a font related style to `TabView` or `Page` (which is inherited by `TabView`) immediately triggers `getNativeFontValue()` method; before `tabBar` or it's items are initialized.

And since `getNativeFontValue()` method doesn't check whether `tabBar` or `tabBar.items` collection is available; it throws on `tabBar.items.count`.

Fixes issue #3568 and (also [this issue](https://github.com/NativeScript/nativescript-angular/issues/654)).

### CODE REVIEW

**Comment by onury** [comment]
Signed the CLA

**Comment by vchimev** [comment]
build

**Comment by onury** [comment]
debug, fix, send PR, sign CLA, get approved... and ...not merged.. 
happy contributing!

**Comment by vakrilov** [comment]
Hey @onury thanks for the contribution!
Actually we merged a similar fix (#3587) directly in the release branch.
We are in the midst of a major refactoring in the `master` branch and that is the reason your PR was on hold, although perfectly valid ;)

**Pull request closed without merging**
