### PR TITLE
(WIP) feat: TappableSpan support

### PR DESCRIPTION
**Pull request by edusperoni**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
There is no way to add links to Labels/TextViews.

## What is the new behavior?
Span now has a `linkClick` event which, when bound, makes it possible for it to be interacted with via tap.

Implements #3671.

### CODE REVIEW

**Comment by edusperoni** [comment]
If possible, I'd like that the core team test this implementation on Android and validate it's styling, so I can replicate it on iOS.

Challenges:

1. On iOS, making a Label clickable requires a [dirty hack](https://stackoverflow.com/a/28519273/6133327).
2. I have no idea if this works when the parent is a button (further testing needed).

There's an option to use the usual link highlighting (some adaptations are needed, or we could depend on https://github.com/saket/Better-Link-Movement-Method) to get this effect:

image

We could accomplish it by setting something like `android.highlightColor`, but when you override the span's background color, the highlight color never appears. This means we would not be able to create a span with a background that highlights.

This is also not possible on iOS (at least not in a trivial way). If our goal is to have the same style on both platforms, we can skip this step.

**Comment by shiv19** [comment]
Hi @edusperoni!
Can we please rename this to TappableSpan,
and change the name of the event to `linktap` since "click" is not a term that is used on mobile. :)

**Comment by edusperoni** [comment]
@shiv19 Absolutely, I used `CliackableSpan` because Android actually defines it like that (https://developer.android.com/reference/android/text/style/ClickableSpan). I'll update it to match `TappableSpan`

**Comment by elvticc** [comment]
Hello ! Great improvement, look forward to it being implemented :) Thank you very much for your work.

**Comment by edusperoni** [comment]
Closing in favor of #8256

**Pull request closed without merging**
