### PR TITLE
feat(utils): work openFile in simulator

### PR DESCRIPTION
**Pull request by tarunama**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
can not open file in iOS simulator. 

## What is the new behavior?
can open file in iOS simulator

Implements #8410

### CODE REVIEW

**Comment by vtrifonov** [comment]
test

**Comment by vtrifonov** [comment]
@tarunama can you please merge the following PR to your branch first https://github.com/tarunama/NativeScript/pull/1

**Comment by tarunama** [comment]
@vtrifonov 
Thank you for your perfect following !

**Comment by vtrifonov** [comment]
test

**Comment by tarunama** [comment]
@vtrifonov 
Sorry, I mistake git command

**Comment by vtrifonov** [comment]
test

**Comment by vtrifonov** [comment]
@tarunama one more PR to merge https://github.com/tarunama/NativeScript/pull/2 :)

**Comment by vtrifonov** [comment]
test

**Pull request merged**
