### PR TITLE
Expose configurable attributes property when loading components

### PR DESCRIPTION
**Pull request by akagr**
Implements #2048

### CODE REVIEW

**Comment by enchev** [comment]
Hey @akagr,

Please add test here:
https://github.com/NativeScript/NativeScript/blob/master/apps/tests/xml-declaration/xml-declaration-tests.ts

**Comment by akagr** [comment]
@enchev alrighty thanks!

**Comment by enchev** [comment]
run ci

**Comment by akagr** [comment]
hey @enchev can you help me understand why my builds are failing if you have time? As far as I can see, the test which I added is not even being run and android's logcat is shitting itself crazy. Moreover, the tests which do run all end `OK`.

**Comment by enchev** [comment]
:+1: @akagr It seems that we have temporary problems with our Travis CI. I've checked manually and everything is ok!

**Comment by akagr** [comment]
oh wow! thanks @enchev!

**Pull request merged**
