### PR TITLE
refactor: restore animators api usage

### PR DESCRIPTION
**Pull request by manoldonev**
Related to https://github.com/NativeScript/NativeScript/pull/6129#issuecomment-409852341

### CODE REVIEW

**Comment by manoldonev** [comment]
test branch_tests_app_transitions#mdonev/restore-animator-api animations testsappng

**Comment by manoldonev** [comment]
test --ignore animation_android animations_api23 branch_tests_app_transitions_android#mdonev/restore-animator-api tests_app_transitions_api23

**Comment by manoldonev** [comment]
test branch_tests_app_transitions#mdonev/restore-animator-api animations

**Comment by SvetoslavTsenov** [comment]
👍

**Comment by SvetoslavTsenov** [comment]
test --ignore branch_tests_app_transitions#mdonev/restore-animator-api animations api22 api19

**Comment by SvetoslavTsenov** [comment]
test --ignore branch_tests_app_transitions#mdonev/restore-animator-api api22 api19

**Pull request merged**
