### PR TITLE
fix: android use Nestedscrollview for vertical scroll-view

### PR DESCRIPTION
**Pull request by farfromrefug**
No api change just the underneath view is changing.
Also the scroll event are now handled through `NestedScrollView` scroll handler

### CODE REVIEW

**Comment by rigor789** [comment]
@farfromrefug seems like the ScrollView tests in `apps/automated` lock up with this change - we definitely need to address that before a merge. (look into why it locks up & fix if it's an issue, or fix/change the test)

**Comment by farfromrefug** [comment]
@rigor789 I actually ran the automated tests successfully here. 
I had some errors with other CSS tests though .

**Comment by farfromrefug** [comment]
the tests actually allowed me to fins a difference in behavior. thank you tests!

**Comment by rigor789** [comment]
Could be related to this:
image

Can you try updating the branch from `NativeScript:master`

**Comment by rigor789** [comment]
Hmm, still get's stuck here: 
```js
JS: Test: START SCROLL-VIEW TESTS.
JS: Test: --- [SCROLL-VIEW.test_snippets] OK, duration: 0.47
JS: Test: --- [SCROLL-VIEW.test_default_TNS_values] OK, duration: 1.52
JS: Test: --- [SCROLL-VIEW.test_vertical_oriantation_creates_correct_native_view] OK, duration: 0.55
JS: Test: --- [SCROLL-VIEW.test_horizontal_oriantation_creates_correct_native_view] OK, duration: 51.30
JS: Test: --- [SCROLL-VIEW.test_scrollableHeight_vertical_orientation_when_content_is_small] OK, duration: 23.39
JS: Test: --- [SCROLL-VIEW.test_scrollableHeight_vertical_orientation_when_content_is_big] OK, duration: 26.42
JS: Test: --- [SCROLL-VIEW.test_scrollableWidth_horizontal_orientation_when_content_is_small] OK, duration: 78.60
JS: Test: --- [SCROLL-VIEW.test_scrollableWidth_horizontal_orientation_when_content_is_big] OK, duration: 20.31
JS: Test: --- [SCROLL-VIEW.test_scrollToVerticalOffset_no_animation] OK, duration: 43.50
JS: Test: --- [SCROLL-VIEW.test_scrollToVerticalOffset_with_animation] OK, duration: 282.61
JS: Test: --- [SCROLL-VIEW.test_scrollToHorizontalOffset_no_animation] OK, duration: 47.76
JS: Test: --- [SCROLL-VIEW.test_scrollToHorizontalOffset_with_animation] OK, duration: 325.84
JS: Test: --- [SCROLL-VIEW.test_scrollView_persistsState_vertical] OK, duration: 419.14
JS: Test: --- [SCROLL-VIEW.test_scrollView_persistsState_horizontal] OK, duration: 249.20
```

I'll pull the branch down & try locally, seems weird.

**Comment by Upd4ting** [comment]
Any progress on this PR?

**Comment by rigor789** [comment]
@Upd4ting it crashes the test app, we are looking into a fix with @farfromrefug, just been busy for both of us!

**Comment by farfromrefug** [comment]
@rigor789 tests are failing for completely different reasons now. Like css parse error. I dont really get it

**Comment by Upd4ting** [comment]
How could I test that on my computer to help you?

**Comment by farfromrefug** [comment]
@Upd4ting you can fork that branch and run the automated app for android. some tests are not passing. 
I am really sorry I am completely under right now and I don't have much time to take a deep look at this.

**Comment by vallemar** [comment]
Is this on the roadmap?

**Review by NathanWalker — APPROVED** [review]

**Pull request merged**
