### PR TITLE
FIX: Adnroid app crashes when there is action bar on main page

### PR DESCRIPTION
**Pull request by vakrilov**

### CODE REVIEW

**Comment by nsndeck** [comment]
:+1:

**Comment by enchev** [comment]
:+1:

**Comment by andremoreiradealmeida** [comment]
.js fix?

**Comment by svalchinov** [comment]
FYI, actionbar on main page still crashes in newly generated sample app via tns create <projectName>.

tns 1.2.1

**Comment by maknz** [comment]
After upgrading to 1.2.2 this issue seems to have reappeared.

**Comment by vakrilov** [comment]
Related to issue #575

**Pull request merged**
