### PR TITLE
segmented bar selectedIndexChanged fix

### LINKED ISSUE #808: Segmentedbar selectedIndexChanged doesn't work
1.3 event only fires on view load. Tapping the bar items doesn't retrigger the event.

Add it to put the groceries app to test. 

IMO I don't even want it to fire on bind/load

### PR DESCRIPTION
**Pull request by enchev**
Fixed #808

### CODE REVIEW

**Comment by enchev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by hdeshev** [comment]
:+1:

**Comment by enchev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Pull request merged**
