### PR TITLE
feat(GridLayout): Add synonym property column for col in GridLayout

### LINKED ISSUE #7295: Make `column` a synonym for `col` property re layout child properties
**Is your feature request related to a problem? Please describe.**
I had been trying to use a "column" property on child elements of the `GridLayout` element before realizing that I was using the wrong property -- d'oh! "col", of course, is the correct property.

**Describe the solution you'd like**
Make "column" a synonym for "col"

**Describe alternatives you've considered**
Maybe throw an error?

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/74955690-make-column-a-synonym-for-col-property-re-layout-child-properties?utm_campaign=plugin&utm_content=tracker%2F12908224&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F12908224&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mehulcs**
- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [X] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
There is no column property synonym of col.

## What is the new behavior?
Added new property column synonym for col.

Fixes/Implements/Closes #7295 .

### CODE REVIEW

**Comment by mehulcs** [comment]
@cla-bot check

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
test

**Comment by vakrilov** [comment]
test

**Comment by vakrilov** [comment]
Hi @mehulcs 
First of all - thanks for the PR!

There are some failing unit tests in your PR currently. They are caused by the logic in the [`getColumn`](https://github.com/NativeScript/NativeScript/pull/7368/files#diff-c767e7a4682939a58bd19c58472988eeR140) and [`getColumnSpan`](https://github.com/NativeScript/NativeScript/pull/7368/files#diff-c767e7a4682939a58bd19c58472988eeR151) which select the value from one of the "synonym" over the other. 

Giving it a further thought - as long as there are 2 properties for one value (ex. `col` and `column`) there will always be a problem so syncing these properties with one another or having to choose which one is to use. 

I have another more simple and easy to maintain approach. Define the `column` and `columnSpan` properties as javascript properties with getters and setters that will just fallback to the original property:
```
Object.defineProperty(View.prototype, "column", {
    get(this: View): number { return this.col; },
    set(this: View, value: number) { this.col = value; },
    enumerable: true,
    configurable: true
});

Object.defineProperty(View.prototype, "columnSpan", {
    get(this: View): number { return this.colSpan; },
    set(this: View, value: number) { this.colSpan = value; },
    enumerable: true,
    configurable: true
});
```

This way we won't have to deal with syncing issues.

**Comment by mehulcs** [comment]
Thanks, @vakrilov @manoldonev 
@vakrilov That's a wonderful approach to make synonym property, Let me know if there are any changes required to be made in this PR.

**Comment by vakrilov** [comment]
Hey @mehulcs - I have extended your PR and re-opened it in #7641. 
Your initial commits are still there, so you will be recognized as contributor.

Thanks!

**Comment by mehulcs** [comment]
Thanks @vakrilov

**Pull request closed without merging**
