### PR TITLE
Implemented feature request: TextField `maxLength` property support.

### PR DESCRIPTION
**Pull request by PanayotCankov**
Rebased @EddyVerbruggen 's #3902 and resolved minor conflicts. Rerunning tests before merge.

### CODE REVIEW

**Comment by vakrilov** [comment]
LGTM!
@SvetoslavTsenov or @vchimev can we add a test for that in the `e2e` tests?

**Comment by SvetoslavTsenov** [comment]
sure

**Comment by PanayotCankov** [comment]
run-ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
Should be rebased once again to get Travis passing. :)

**Comment by vakrilov** [comment]
This is the issue for this PR: #3614

**Comment by vchimev** [comment]
There are test failures.

Android:
```
I/JS      ( 1652): 1436 OK, 7 failed
E/JS      ( 1652): Test: TEXT-FIELD.testSetHintToNumber FAILED: Actual: null; Expected: 1
E/JS      ( 1652): Test: TEXT-FIELD.testSetHint FAILED: Actual: null; Expected: type your username here
E/JS      ( 1652): Test: TEXT-FIELD.testBindHintDirectlyToModel FAILED: Actual: null; Expected: type your username here
E/JS      ( 1652): Test: TEXT-FIELD.testBindHintToBindingConext FAILED: Actual: null; Expected: type your username here
E/JS      ( 1652): Test: TEXT-VIEW.testSetHint FAILED: Actual: null; Expected: type your username here
E/JS      ( 1652): Test: TEXT-VIEW.testBindHintDirectlyToModel FAILED: Actual: null; Expected: type your username here
E/JS      ( 1652): Test: TEXT-VIEW.testBindHintToBindingConext FAILED: Actual: null; Expected: type your username here
```

iOS:
```
iOS.TEXT-FIELD.testSetHintToNumber
iOS.TEXT-FIELD.testSetHint
iOS.TEXT-FIELD.testBindHintDirectlyToModel
iOS.TEXT-FIELD.testBindHintToBindingConext
iOS.TEXT-VIEW.testSetHint
iOS.TEXT-VIEW.testBindHintDirectlyToModel
iOS.TEXT-VIEW.testBindHintToBindingConext
iOS.TEXT-VIEW.testHintColoriOS
```

**Comment by suresh-selvaraj** [comment]
Hi,

Kindly let us know when this maxLength property fix will be available in the master branch.

Thanks.
Suresh.S

**Comment by SvetoslavTsenov** [comment]
run uitests

**Comment by SvetoslavTsenov** [comment]
run uitests

**Comment by SvetoslavTsenov** [comment]
run uitests

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by vakrilov** [comment]
Rebased again and fixed the failing tests.
Will merge if all is green in the CI. 
CC @PanayotCankov @vchimev

**Pull request merged**
