### PR TITLE
Revert 5772 revert 5534 css gradients

### PR DESCRIPTION
**Pull request by ADjenkov**

### CODE REVIEW

**Comment by ADjenkov** [comment]
test branch_widgets#revert-122-revert-116-css-gradients branch_module_navigation

**Comment by ADjenkov** [comment]
test branch_widgets#revert-122-revert-116-css-gradients branch_modal_navigation

**Comment by ADjenkov** [comment]
test branch_widgets#revert-122-revert-116-css-gradients branch_testsappng

**Comment by ADjenkov** [comment]
test branch_widgets#revert-122-revert-116-css-gradients branch_testsappng#ns-40

**Comment by dtopuzov** [comment]
test branch_widgets#revert-122-revert-116-css-gradients branch_testsappng#ns-40

**Comment by dtopuzov** [comment]
test branch_widgets#revert-122-revert-116-css-gradients branch_testsappng#ns-40

**Comment by ADjenkov** [comment]
test branch_widgets#revert-122-revert-116-css-gradients branch_testsappng#ns-40

**Comment by ADjenkov** [comment]
test branch_widgets#revert-122-revert-116-css-gradients branch_testsappng#ns-40

**Comment by SvetoslavTsenov** [comment]
test branch_ tns-core-modules-widgets#revert-122-revert-116-css-gradients branch_testsappng#ns-40 testsappng

**Comment by SvetoslavTsenov** [comment]
test branch_tns-core-modules-widgets#revert-122-revert-116-css-gradients branch_testsappng#ns-40 modal_navigation

**Comment by SvetoslavTsenov** [comment]
test branch_tns-core-modules-widgets#revert-122-revert-116-css-gradients branch_testsappng#ns-40 testsappng

**Comment by SvetoslavTsenov** [comment]
test branch_tns-core-modules-widgets#revert-122-revert-116-css-gradients testsappng

**Pull request merged**
