### PR TITLE
Remove the android.app.Application extend from the core modules

### PR DESCRIPTION
**Pull request by atanasovg**
This pull removes the Android Application object extend from the core modules. The change enables the following scenarios:

- Make the modules Heap snap-shottable
- Allow users to provide custom `android.app.Application` implementation. This includes
    - Entirely custom application type
    - Implement an additional interface on the default `com.tns.NativeScriptApplication` class

The change also introduces the following paths for application initialization:

- User provides custom application extend. In the `onCreate` method he should manually initialize the application module via `application.android.init(this)`. The static-binding-generator will take care of the `*.JAVA` file generation.
- No custom extend is defined. Application will use the default `com.tns.NativeScriptApplication` implementation provided with the Android Runtime project template. Application module is initialized upon `application.start` call.
- User provides custom extend but does not initialize the application module explicitly. This falls back to a somewhat hacky implementation, that retrieves the native `android.app.Aplication` object through reflection. **TODO: We may throw an error instead of doing this**.

Note: This pull will work when we merge this one as well: https://github.com/NativeScript/android-runtime/pull/471

### CODE REVIEW

**Comment by hshristov** [comment]
👍 
My only concern is how will this affect existing applications? I guess they will need to manually add this `android.application.js` in their project templates?

**Comment by atanasovg** [comment]
@hshristov They are not forced to do so - that's the second initialization path, as listed in the pull's description. The extend will happen only if they need to add some custom initialization logic.

In other words - existing applications shouldn't be affected.

**Comment by vchimev** [comment]
run ci

**Comment by atanasovg** [comment]
run ci

**Comment by hshristov** [comment]
👍

**Pull request merged**
