### PR TITLE
[DO NOT MERGE] Test

### PR DESCRIPTION
**Pull request by dtopuzov**
## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the new behavior?

Fixes/Implements/Closes #[Issue Number].

### CODE REVIEW

**Comment by dtopuzov** [comment]
test android#trifonov/v8-change branch_sdk branch_uitests branch_cuteness branch_qsf branch_testsappng branch_groceries

**Comment by dtopuzov** [comment]
test branch_android#trifonov/v8-change branch_sdk branch_uitests branch_cuteness branch_qsf branch_testsappng branch_groceries

**Comment by vtrifonov** [comment]
test branch_android#trifonov/v8-6.0.286.52 branch_sdk branch_uitests branch_cuteness branch_qsf branch_testsappng branch_groceries

**Comment by SvetoslavTsenov** [comment]
test branch_android#trifonov/v8-change branch_sdk branch_uitests branch_cuteness branch_qsf branch_testsappng branch_groceries api23 --ignore

**Comment by vtrifonov** [comment]
test branch_android#trifonov/v8-6.0.286.52 branch_uitests branch_cuteness branch_qsf branch_testsappng branch_groceries api23 --ignore

**Comment by vtrifonov** [comment]
test branch_android#trifonov/v8-6.5.254.28 branch_uitests branch_cuteness branch_qsf branch_testsappng branch_groceries api23 --ignore

**Comment by vtrifonov** [comment]
test branch_android#trifonov/v8-6.0.286.52 branch_uitests branch_cuteness branch_qsf branch_testsappng branch_groceries api23 --ignore

**Pull request closed without merging**
