### PR TITLE
Revisit lazy require routine

### PR DESCRIPTION
**Pull request by atanasovg**
Lazy require calls degrade the runtime performance in some cases, especially when called frequently in a function that is performance-critical - for example [ListView._getItemTemplateContent](https://github.com/NativeScript/NativeScript/blob/master/ui/list-view/list-view-common.ts#L135). This degrade is particularly visible for Android where the `require` routine calls to Java to compute the absolute path of the module.

What this pull does is to revisit all the lazy calls, to remove some that are part of the loading routine anyways and to cache the rest on the JavaScript side.

### CODE REVIEW

**Comment by enchev** [comment]
:100:

**Comment by atanasovg** [comment]
run ci

**Comment by atanasovg** [comment]
run ci

**Comment by atanasovg** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by hshristov** [comment]
:+1:

**Pull request merged**
