### PR TITLE
fix(ios): revert regression from PR #10096

### PR DESCRIPTION
**Pull request by farfromrefug**
https://github.com/NativeScript/NativeScript/pull/10096

The changes in `ui/page/index.ios.ts` where not meant to be there. And it broke back navigation event https://github.com/NativeScript/NativeScript/commit/6148955335f164aa160e719a98ad811b4d006560#commitcomment-92040756

For reference there is a github mystery here
https://github.com/NativeScript/NativeScript/blame/c957b487a8d98e529df5432aed5b7126a83a6020/packages/core/ui/page/index.ios.ts
https://github.com/akylas/NativeScript/blame/main/packages/core/ui/page/index.ios.ts

Both blames say the part (around line 127) date from before the core refactoring but with a different code :s 
I am sorry about this i am baffled by this...
and thanks to @tombien for discovering this!

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/DevelopmentWorkflow.md#running-unit-tests-application.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/tools/notes/WritingUnitTests.md.

## What is the new behavior?

Fixes/Implements/Closes #[Issue Number].

### CODE REVIEW

**Comment by rigor789** [comment]
A test failed in the original PR (#10096), as well as here:

```js
Test: TAB-VIEW-ROOT.test_offset_zero_should_raise_same_events FAILED:  At /0/2 
  actual:   'Tab0 Frame0 Page0 navigatingTo' and 
  expected: 'Tab0 Frame0 Page0 loaded'       differ.
```

I believe the actual is now expected - but the test has not been updated to reflect that. Other than that - wouldn't `loaded` need to be called as well? 

```
Tab0 Frame0 Page0 navigatingTo loaded
```

(haven't looked at the actual test, just looking at the failed test in CI)

**Comment by farfromrefug** [comment]
@rigor789 the change in frame should NOT be reverted! I need to fox this

**Comment by farfromrefug** [comment]
@rigor789 @NathanWalker i fixed this correctly now by only adding the notify of the event for the Frame.
I also added a comment to explain the situation and the emphasis on the fact that all that should be refactored / fixed. To me it seems iOS does not send those events at the right time.

I also added navigation tests back (only some as others were failing) and added tests for the Frame events

**Review by NathanWalker — APPROVED** [review]

**Comment by NathanWalker** [comment]
nicely done @farfromrefug thank you!

**Pull request merged**
