### PR TITLE
Added async image source functionality

### PR DESCRIPTION
**Pull request by atanasovg**
This pull implements `fromFile`, `fromResource` and `fromBase64` as asynchronous methods on the `ImageSource` class.

### CODE REVIEW

**Comment by atanasovg** [comment]
ping @PanayotCankov

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by PanayotCankov** [comment]
:+1:

**Comment by atanasovg** [comment]
run CI

**Comment by dtopuzov** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
@atanasovg,

there are two failing tests with 'Test timeout':

Android.IMAGE.test_SettingImageSrcToFileWithinAppAsync
Android.IMAGE.test_SettingImageSrcToDataURIAsync

**Comment by PanayotCankov** [comment]
When this feature is adopted in the nativescript-marketplace-demo, it crashes the app on high speed scrolling. We will have to use cancelable requests, that will stop any previous requests when src is changed on the image. The iOS does better image caching under the hood and behaves well though.

**Comment by atanasovg** [comment]
We discussed this case with @PanayotCankov & @hshristov and decided to close it for now because it is not trivial to implement cancelable requests. Instead, we recommend usage of https://github.com/NativeScript/nativescript-fresco.

**Pull request closed without merging**
