### PR TITLE
Add binding expressions tests.

### PR DESCRIPTION
**Pull request by vchimev**

### CODE REVIEW

**Comment by enchev** [comment]
:+1:

**Comment by hdeshev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by hdeshev** [comment]
:+1:

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by vchimev** [comment]
Causes https://github.com/NativeScript/android-runtime/issues/149.

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Pull request merged**
