### PR TITLE
Promises rejected properly when loading wrong content

### PR DESCRIPTION
**Pull request by enchev**
Fix for #651

### CODE REVIEW

**Comment by enchev** [comment]
run ci

**Comment by nsndeck** [comment]
:+1:

**Comment by dtopuzov** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by vakrilov** [comment]
:+1:

**Comment by vakrilov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Pull request merged**
