### PR TITLE
fix: rollback regexp eslint changes

### PR DESCRIPTION
**Pull request by farfromrefug**
this fixes the regression discovered here https://github.com/NativeScript/NativeScript/pull/9017#issuecomment-726242266

### CODE REVIEW

**Comment by DimitrisRK** [comment]
@farfromrefug There had been test failures in automate app, so I took a deep look.
It seems that few promise changes have also broken few things.
What I discovered so far is these 2 lines:
https://github.com/NativeScript/NativeScript/blob/master/packages/core/ui/animation/animation-common.ts#L103
https://github.com/NativeScript/NativeScript/blob/master/packages/core/ui/animation/animation-common.ts#L110

Reverting those got rid of about 20 test failures.

**Comment by farfromrefug** [comment]
damn let me fix this

**Comment by farfromrefug** [comment]
automated app tests are running (still issues but not related to this)

**Review by NathanaelA — APPROVED** [review]

**Comment by NathanaelA** [comment]
Thank you @farfromrefug - I can confirm that the automated tests are fully working again on iOS and has one broken on Android that appears to be unrelated to this set of PR's.

**Comment by farfromrefug** [comment]
Thanks @NathanaelA sorry I broke it in the first place. Would nt be a good idea to have automated apps ran before merging any PR ? I know it is heavy but it really seems necessary

**Comment by NathanaelA** [comment]
Totally agree, I thought Automated was already was being ran (in fact I went and looked to see how the prior PR passed the tests because I was surprised to see these two follow up PRs in my inbox, and can see it isn't running.  Ugh, something else to get added/fixed, LOL -- it never ends  ...)

**Pull request merged**
