### PR TITLE
Support for binding expressions in event bindings

### PR DESCRIPTION
**Pull request by enchev**
Implemented #600

### CODE REVIEW

**Comment by enchev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by hdeshev** [comment]
:+1: 

sonic

**Comment by enchev** [comment]
run ci

**Comment by hshristov** [comment]
:+1: 

run ci

**Comment by enchev** [comment]
run ci

**Comment by nsndeck** [comment]
:+1:

**Pull request merged**
