### PR TITLE
fix: dont default to Font.default

### PR DESCRIPTION
**Pull request by farfromrefug**
This would cause a font to be set for any label even when using default system font.
This will also cause a typeface creation which is pretty long

This PR also add a new optional behavior. In my `nativescript-htmllabel` the `textSize` is handled by the component and not using `Font`. To make things faster i would need the fontSizeProperty not to create a `fontInternal` as it would create native `typeface`.
So this PR checks for `handleFontSize` property on the `View`.
If you prefer it done another way i am happy to change it.

### CODE REVIEW

**Comment by vmutafov** [comment]
test

**Comment by vtrifonov** [comment]
@farfromrefug can you please update your branch? Thanks!

**Comment by vtrifonov** [comment]
test

**Comment by vtrifonov** [comment]
@farfromrefug can you please fix the following linter errors:
```
18:53:42 ERROR: /Users/nsbuilduser/workspace/pr-tns-core-modules/nativescript-core/ui/styling/style-properties.ts:1173:11 - missing whitespace
18:53:42 ERROR: /Users/nsbuilduser/workspace/pr-tns-core-modules/nativescript-core/ui/styling/style-properties.ts:1173:19 - view is deprecated: use `viewRef` instead.
18:53:42 
18:53:42 The `ViewBase` object associated with the Style!
18:53:42 ERROR: /Users/nsbuilduser/workspace/pr-tns-core-modules/nativescript-core/ui/styling/style-properties.ts:1173:24 - ' should be "
```

**Comment by vtrifonov** [comment]
ping @farfromrefug , can you update your branch and fix the linter errors :)

**Comment by vtrifonov** [comment]
test

**Comment by vtrifonov** [comment]
@farfromrefug can you check the following PR - https://github.com/Akylas/NativeScript/pull/2

**Comment by farfromrefug** [comment]
@vtrifonov awesome. Sorry about that :s

**Comment by vtrifonov** [comment]
test

**Comment by vtrifonov** [comment]
@farfromrefug one more PR to merge https://github.com/Akylas/NativeScript/pull/3 :)

**Comment by farfromrefug** [comment]
@vtrifonov what test is that that showed the bold font error for tabs? Maybe i could run that on my side and save you some time ...

**Comment by vtrifonov** [comment]
test

**Pull request merged**
