### PR TITLE
Implement Typescript Definitions for APIs beyond 17

### PR DESCRIPTION
**Pull request by georgeedwards**
This is intended to be a work in progress PR, to track work related to issue #2295. So far I have just manually implemented several bits of the missing definitions, to allow my project with Eddy's nativescript-bluetooth plugin to port to typescript. However, I intend (when my issue gets some responses), to implement a complete solution for each API level ( assuming I don't have to do everything manually).

### Does your pull request have unit tests
I don't think they are necessary for definition files.

### CODE REVIEW

**Comment by georgeedwards** [comment]
On a separate note, is ^ an issue with ns-bot?

**Comment by atanasovg** [comment]
Hey @georgeedwards, thanks a lot for your contribution!

Have you checked the https://github.com/NativeScript/android-dts-generator repo? There are several issues for the generator to be fully functional and user-friendly but the whole idea is to automate the generation of definition files, based on any `*.JAR` or `*.AAR` file(s).

**Comment by georgeedwards** [comment]
@atanasovg Yes I have, but I was hoping for some action on [this](https://github.com/NativeScript/android-dts-generator/issues/1) issue, before I got started, either contributing to the tool or just producing the output and manually tailoring it.

**Comment by dtopuzov** [comment]
run ci

**Comment by roblav96** [comment]
@georgeedwards OMG this is wonderful! 😄

**Comment by Pip3r4o** [comment]
@georgeedwards https://github.com/NativeScript/android-dts-generator/ was updated recently. README has also been improved including instructions for generating definitions

**Pull request closed without merging**
