### PR TITLE
[DO NOT MERGE] no-op change for widget test

### PR DESCRIPTION
**Pull request by manoldonev**
no-op change to test widgets PR https://github.com/NativeScript/tns-core-modules-widgets/pull/110

### CODE REVIEW

**Comment by manoldonev** [comment]
test branch_widgets#ddfreiling/fix-color-filter

**Comment by ddfreiling** [comment]
@manoldonev anything I did, that made it fail?

**Comment by manoldonev** [comment]
@ddfreiling nope, it's on our end and we are working on it.

**Comment by manoldonev** [comment]
test branch_widgets#ddfreiling/fix-color-filter

**Pull request closed without merging**
