### PR TITLE
fix(android/text ios/text): allow -1 to be a valid binding value

### PR DESCRIPTION
**Pull request by shiv19**
Instead of using -1 as a special value, use Symbol(-1)
so that it can't be reset accidentally

Closes issue #5559

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
https://github.com/NativeScript/NativeScript/issues/5559

## What is the new behavior?
Replaced -1 with Symbol(-1) so that it reset can't be set accidentally

Fixes/Implements/Closes #[Issue Number].

#5556

### CODE REVIEW

**Comment by shiv19** [comment]
I ran the tests.

All the tests have passed :)

And this PR doesn't require any new test case.

**Comment by vakrilov** [comment]
test

**Comment by vakrilov** [comment]
test

**Comment by vakrilov** [comment]
test

**Pull request merged**
