### PR TITLE
feat: implementing multiple templates for Repeater

### PR DESCRIPTION
**Pull request by DimitrisRK**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
Repeater does not support multiple templates.

## What is the new behavior?
Repeater will support multiple templates using keys, just like ListView.

Implements #3781 .

This was tested carefully on android devices and no issues occured.

### CODE REVIEW

**Comment by NathanaelA** [comment]
@DimitrisRK - Can you re-target his to he new master repo please; looks like awesome new functionality!

**Comment by DimitrisRK** [comment]
> @DimitrisRK - Can you re-target his to he new master repo please; looks like awesome new functionality!

@NathanaelA Thanks a lot for replying. Should I create a new PR based on new master branch then?
Thanks.

**Comment by NathanaelA** [comment]
Sorry, I'm not a git pro -- their might be a way to rebase the PR onto the new master, which of course would be the quickest method.   But if your like me, it might be easier just to redo the changes real quick on the current master and create a new PR...  :grinning:

**Comment by NathanWalker** [comment]
@DimitrisRK I can probably help you here - perhaps a zoom chat in next week? If you're on {N} slack you can ping me there or shoot me email (which is widely publicly available 👍 ) We can look at any pending branch work you may have and help get ya settled.

**Comment by DimitrisRK** [comment]
> @DimitrisRK I can probably help you here - perhaps a zoom chat in next week? If you're on {N} slack you can ping me there or shoot me email (which is widely publicly available 👍 ) We can look at any pending branch work you may have and help get ya settled.

That sounds great, but how about I attempted to adapt changes to NS7 first? This way, I won't be much of a bother. :)) 
I'm currently migrating my applications to NativeScript 7 (I really like these new changes) and trying to locate any possible issues. When done, I believe I can take another look at this.

**Comment by DimitrisRK** [comment]
I close this PR in favor of PR #8981

**Pull request closed without merging**
