### PR TITLE
Add sibling combinators for CSS rules

### PR DESCRIPTION
**Pull request by SBats**
Hi !
After asking for the opportunity to do a PR in this issue (https://github.com/NativeScript/NativeScript/issues/3727), I've worked a bit on it and, event if it's not complete, I would love to have a first feedback on the direction I'm taking.

I've implemented direct sibling combinator support, so the `+` combinator in web css.
To do so, I've modified the `createSelector` method and created a custom selector for handling this specific type of combination.

- Do you think it's a good approach?
- In this case, are extensive tests page in the `app` app enough, or do you want other kinds of automated unit tests on the methods?

Thank you a lot in advance for your help on this subject!

### CODE REVIEW

**Comment by SBats** [comment]
Wow! Thanks a lot for this extensive feedback, really appreciate it!
All you've said make sense, I'll work on it and update this PR as soon as I can.
PS: Nice idea for the pseudo-class selectors 👍 , I'll add that.

**Comment by SBats** [comment]
@PanayotCankov , I think I've come up with a solution matching what you advised. I've also added a unit test for a basic sibling case. When you have time I would be grateful to have another feedback.
Travis tests failed, but it seems to be more linked to an environment and config issue than to code itself. Is it normal or did I miss something?

If you're okay with it, I'd prefer to work on positional pseudo class in another PR as to be sure to finish this one properly before handling another feature.
Thank you for your help and time.

**Comment by PanayotCankov** [comment]
run-ci

**Comment by SBats** [comment]
Great news! Thanks again for your help on this and the time you take.
No worries for 3.0, I'm just glad I could contribute to NS. I don't have an emergency needs for this feature yet.
In the meantime, I'll start working on the positional pseudo class PR.
Let me know if there's anything to change on this, and good luck for v3 release!

**Comment by dtopuzov** [comment]
run ci

**Comment by jlooper** [comment]
@SBats This PR qualified for special treatment! Congratulations on your new badge!

contrib

**Comment by SBats** [comment]
@jlooper Wow, thanks a lot, I'm honored :).
And also thanks again @PanayotCankov for your help!

**Comment by PanayotCankov** [comment]
run-ci

**Comment by PanayotCankov** [comment]
I am closing this. Will merge: #4146. It is pretty much the same changes squashed and rebased onto master. There were 2 tslint errors (you can run tslint with `npm run tslint` in the root of the repo).

**Pull request closed without merging**
