### PR TITLE
fix(iOS): Opening alert/confirm on top most of modal dialogs

### LINKED ISSUE #6939: Alert dialog cannot be shown while modal dialog is being shown on iOS
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.1
 - Cross-platform modules: 5.0.5
 - Android Runtime: 5.1.0
 - iOS Runtime: 5.1.1
 - Plugin(s): Unrelated

**Describe the bug**
Alert dialog cannot be shown while modal dialog is being shown on iOS.

**To Reproduce**
Open a modal. After modal is open, show an alert dialog inside that modal's component. It doesn't show an alert dialog even though it works in Android.

**Expected behavior**
It should show an alert box.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/70332958-alert-dialog-cannot-be-shown-while-modal-dialog-is-being-shown-on-ios?utm_campaign=plugin&utm_content=tracker%2F12908224&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F12908224&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by slolam**
This is fix for the issue #6939 where alert() and confirm() does not work in a modal dialog if it's opened on top of an existing modal dialog.

## PR Checklist

- [ x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ x] You have signed the [CLA](http://www.nativescript.org/cla).
- [ x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ x] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
If you have modal dialog on top of another modal dialog (which is support from {N} 4.0), you cannot show an alert/confirm in iOS. It simply does not show the alert, it silently gives a warning. This is an iOS only behavior and is reported in the #6939. 

Here is the link to the Playground https://play.nativescript.org/?template=play-ng&id=GeR8Q4&v=2 
The alert box is shown on the first dialog but not on the stacked ones on top of it.

## What is the new behavior?
It uses the top most UIViewController to present the alert/confirm

Fixes #6939.
This fix does not contain any breaking changes

### CODE REVIEW

**Comment by slolam** [comment]
@ADjenkov, do you want me to update the branch? It looks the master is out of date and will it require re-approval?

**Comment by ADjenkov** [comment]
@slolam no need of re-approval. I'll update it now

**Comment by slolam** [comment]
@ADjenkov, typically how many days does it take to merge and release after approval? I have been manually updating the framework file for this fix before I build the app for release.

**Comment by ADjenkov** [comment]
test

**Comment by slolam** [comment]
> test

The failed test output has java.lang.* I am wondering how my iOS related changes creeping into the Android world.

Is there a way I could get access to the output/log of the test?

**Comment by ADjenkov** [comment]
@slolam sorry for the late response. Don't mind the test results for now, since we are facing some issues with testing on our side. Will try to merge it today, thanks for the PR!

**Comment by SvetoslavTsenov** [comment]
test --ignore branch_uitest ios13

**Comment by SvetoslavTsenov** [comment]
test --ignore branch_uitest ios13

**Comment by etabakov** [comment]
@cla-bot check

**Comment by SvetoslavTsenov** [comment]
test --ignore ios12

**Comment by etabakov** [comment]
Hey, thanks for your contribution! We have a special program for our first-time contributors and you are eligible to participate in it. If you haven't applied already, all you need to do to claim your prize is to fill our [Application Form](https://goo.gl/forms/lPKpXzG4F1EhfKM72).

Regards from the whole team 🥇

**Pull request merged**
