### PR TITLE
code refactored to support ios9

### PR DESCRIPTION
**Pull request by enchev**
Fix for #851

### CODE REVIEW

**Comment by dtopuzov** [comment]
run ci

**Comment by nsndeck** [comment]
:+1:

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run cu

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
Console log from nsbuildmac01:
```
Oct  2 04:32:02 nsbuildmac01.local TestApp[69281]: file:///app/tns_modules/trace/trace.js:145:29: CONSOLE INFO Test: --- [REPEATER.test_splice_observable_array_refreshes_the_Repeater] OK
Oct  2 04:32:03 nsbuildmac01.local TestApp[69281]: file:///app/tns_modules/trace/trace.js:145:29: CONSOLE INFO Test: --- [REPEATER.test_usingAppLevelConvertersInRepeaterItems] OK
Oct  2 04:32:04 nsbuildmac01.local TestApp[69281]: file:///app/tns_modules/trace/trace.js:145:29: CONSOLE INFO Test: --- [REPEATER.test_BindingRepeaterToASimpleArray] OK
Oct  2 04:32:04 nsbuildmac01.local SpringBoard[69253]: Unable to get short BSD proc info for 69281: No such process
Oct  2 04:32:04 nsbuildmac01 com.apple.CoreSimulator.SimDevice.AEDB1C68-08A4-4746-A66E-4C377DF23439.launchd_sim[69242] (UIKitApplication:org.nativescript.TestApp[0x6736][69281]): Service exited due to signal: Killed: 9
Oct  2 04:32:04 nsbuildmac01.local ScriptAgent[69284]: Warning - Unable to stop script because the script was already stopped.
Oct  2 04:32:04 --- last message repeated 1 time ---
Oct  2 04:32:04 nsbuildmac01.local SpringBoard[69253]: Application 'UIKitApplication:org.nativescript.TestApp[0x6736]' exited abnormally via signal.
Oct  2 04:32:04 nsbuildmac01 assertiond[69257]: assertion failed: 13F34 12B411: assertiond + 11523 [3F572A0B-7E12-378D-AFEE-EA491BAF2C36]: 0x1
Oct  2 04:32:05 nsbuildmac01.local DTMobileIS[69266]: Could not create service named com.apple.dt.Xcode.WatchProcessControl
Oct  2 04:32:05 nsbuildmac01.local DTMobileIS[69266]: Could not create service named com.apple.instruments.server.services.launchdaemon
Oct  2 04:32:05 nsbuildmac01.local DTMobileIS[69266]: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
```

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
:+1:

**Pull request merged**
