### PR TITLE
Include test page for max-lenght poperty

### PR DESCRIPTION
**Pull request by SvetoslavTsenov**

### CODE REVIEW

**Comment by vchimev** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
run uitests

**Comment by SvetoslavTsenov** [comment]
This commit will break some test because of changed paths to the test pages.

**Comment by SvetoslavTsenov** [comment]
run uitests

**Comment by SvetoslavTsenov** [comment]
run uitests

**Comment by SvetoslavTsenov** [comment]
run uitests

**Pull request merged**
