### PR TITLE
feature(ios/core/dialog): set destructive style from options

### PR DESCRIPTION
**Pull request by danielorihuela**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?

User can create default actions in iOS.

## What is the new behavior?

User can now create destructive actions in iOS as well.

Implements #6749. Related to #3830, #5553.

### CODE REVIEW

**Comment by diegovincent** [comment]
Closes #6749

**Comment by NathanWalker** [comment]
@diegovincent Thank you for this - possible to do a quick format on the files to use tabs [2]?  I know, I'm not a fan of tabs either (shhhh) - that's way core modules has been formatted historically so stick with that for now - we will most likely add an auto format on commit hook in so you don't have to worry about this hassle in the future. That will make the changeset a bit easier to see.

**Comment by diegovincent** [comment]
> @diegovincent Thank you for this - possible to do a quick format on the files to use tabs [2]? I know, I'm not a fan of tabs either (shhhh) - that's way core modules has been formatted historically so stick with that for now - we will most likely add an auto format on commit hook in so you don't have to worry about this hassle in the future. That will make the changeset a bit easier to see.

Gotta say, I am more of a tabs than spaces guy! But there is a reason for it. Tabs can be configured however you want, but spaces cannot (in terms of width). Thus, for accesibility reasons (visual impairment) tabs > spaces. When I realized that, the discussion was over for me.

Having said that, I'll see how to format it as you want, I guess you can do it with Prettier _prettier_ easily.

**Comment by diegovincent** [comment]
@cla-bot check

**Comment by diegovincent** [comment]
@NathanWalker as seen in https://github.com/NativeScript/NativeScript/pull/8676/commits/06dd08388eb213abeea206072265b1de201a6d90 and [on this Travis CI build](https://travis-ci.org/github/NativeScript/NativeScript/builds/705343740) I had to use 4 spaces because that is what the Travis CI asked for.

Unless you want us to explicitly disobey the CI, this should be merged as it is. If instead you want double tabs, simply revert the last commit (https://github.com/NativeScript/NativeScript/pull/8676/commits/06dd08388eb213abeea206072265b1de201a6d90).

**Comment by NathanWalker** [comment]
Thank you @diegovincent

**Comment by NathanWalker** [comment]
Released with https://github.com/NativeScript/NativeScript/releases/tag/6.5.9 now

**Comment by jarrodwhitley** [comment]
I can't find any instructions on how to use this new option.

**Pull request merged**
