### PR TITLE
refactor(console): remove the console module

### PR DESCRIPTION
**Pull request by Pip3r4o**
Removing the console module implementation eliminates some error-prone formatting logic, and certain platform-specific checks. The implementation was also android-specific. Left a stub Console class
implementation as one is necessary to avoid errors with `console` being undefined during the snapshot stage for android.

The console module is replaced by a 'console' implementation in the Android Runtime. See android-runtime/PR #884

Unit test changes PR - https://github.com/NativeScript/functional-tests/pull/9

### CODE REVIEW

**Comment by Pip3r4o** [comment]
Tests PR - https://github.com/NativeScript/functional-tests/pull/9

**Comment by SvetoslavTsenov** [comment]
run android

**Comment by SvetoslavTsenov** [comment]
run uitests-android

**Comment by SvetoslavTsenov** [comment]
android

**Comment by SvetoslavTsenov** [comment]
run android

**Comment by SvetoslavTsenov** [comment]
uitests android

**Comment by SvetoslavTsenov** [comment]
run ci

**Pull request closed without merging**
