### PR TITLE
Implement custom measure for ios btn when textWrap is true

### PR DESCRIPTION
**Pull request by vakrilov**
Related to #4287
UI testa added `issues->issue-4287`
cc @SvetoslavTsenov

### CODE REVIEW

**Comment by vchimev** [comment]
```
E/JS      ( 1752): Test: FLEXBOXLAYOUT.testFlexboxPage FAILED: Building UI from XML. @file:///app/ui/layouts/flexbox-layout-page.xml:21:17
E/JS      ( 1752):  > Invalid boolean: wrap
```

**Comment by vchimev** [comment]
run ci

**Comment by vakrilov** [comment]
run uitests

**Comment by SvetoslavTsenov** [comment]
run uitests

**Comment by SvetoslavTsenov** [comment]
uitests

**Comment by SvetoslavTsenov** [comment]
run  uitests

**Comment by SvetoslavTsenov** [comment]
run uitests

**Pull request merged**
