### PR TITLE
FIX: WebView not showing in gallery app

### PR DESCRIPTION
**Pull request by vakrilov**
Using `url` will throw exception now.

### CODE REVIEW

**Comment by SvetoslavTsenov** [comment]
👍

**Comment by EddyVerbruggen** [comment]
Nooooooooooooo! I need that property. There is no other way to load a local html file with a querystring; passing `~/file.html` to `src` works, but `~/file.html?foo=bar` loads a blank page because it can't find the local file. `url` works perfectly for that case.

**Comment by vakrilov** [comment]
@EddyVerbruggen We should be able to make this work with `src` property as well. 
Do you have specific html doc that we can test with? 
Also is this android/ios (or both) related issue?

**Comment by EddyVerbruggen** [comment]
@vakrilov That would be awesome!

Theoretically (looking at the code, which is in the common file of the module) it's for both platforms, but I only verified this on iOS.

What I'm doing now is loading a map with natively determined lat/lng (to suppress a very nasty web-geolocation prompt on iOS):

```js
webView.url = `file:///${fs.knownFolders.currentApp().path}/mypath/map.html?lat=${location.lat}&lng=${location.lng}`;
```

With the `src` attribute that would be:
```js
webView.src = `~/mypath/map.html?lat=${location.lat}&lng=${location.lng}`;
```

The local HTML file queries the url and extracts the lat/lng params. But it could be anything of course. You can just do:

```js
webView.src = '~/mypath/myfile.html?foo=bar';
```

Currently it won't find `myfile.html` at all because of the query params, but if you can make that work again you can alert the URL in `myfile.html` - if that still contains `?foo=bar` then we can use `src` instead of `url`.

```html
<!DOCTYPE html>
<html>
  <script type="text/javascript" charset="utf-8">
    alert("URL: " + document.location.href);
  </script>
</html>
```

**Comment by speigg** [comment]
IMO, I think we need to keep both:

* `src` should be the url that was explicitly set
* `url` should be the current url (following redirects, navigation, etc)

**Pull request merged**
