### PR TITLE
feat(modal): introduce stretched param to showModal method

### PR DESCRIPTION
**Pull request by ADjenkov**

### CODE REVIEW

**Comment by ADjenkov** [comment]
test testsappng

**Comment by ADjenkov** [comment]
test branch_testsappng

**Comment by ADjenkov** [comment]
test testsappng

**Comment by hshristov** [comment]
@ADjenkov What's the point of removing the code that sets horizontal & vertical alignments and later introduce `stretched` which sets the same properties?

**Comment by SvetoslavTsenov** [comment]
test branch_testsappng#master

**Comment by ADjenkov** [comment]
@hshristov The previous commit that removed the horizontalAlignment="center" was pretty much a  Breaking Change and you had to manually set `horizontalAlignment="center"` and `verticalAlignment="middle"` on the root visual element you are showing modally - Page e.g. But in Angular we wrap the components that we are navigating to in Page and you can't manually set `horizontalAlignment` .

**Comment by SvetoslavTsenov** [comment]
👍

**Pull request merged**
