### PR TITLE
fix: fix ios hmr

### LINKED ISSUE #5293: [ios] Could not install application with code: -402620394
When I try to to install any NativeScript application on an iPad Air running iOS 11.2.2, I get the following error:

```
$ tns run ios --log trace
[...]
Installing...
Will send the following information to Google Analytics: { googleAnalyticsDataType: 'event',
  action: 'Deploy',
  label: 'iOS_Device_11.2.2',
  customDimensions: { cd2: 'Pure JavaScript' } }
Getting applications information for devices with identifiers: 5784c839f6bde322f71ed053979b3459900e92d5
Received multiple results:
{ '5784c839f6bde322f71ed053979b3459900e92d5': 
   [ { deviceId: '5784c839f6bde322f71ed053979b3459900e92d5',
       response: [] } ] }
Result when getting applications for which LiveSync is enabled:  []
Project dir from hooksArgs is: undefined.
Hooks directories: [ '/Users/nicolae.surdu/.npm-global/lib/node_modules/nativescript/lib/hooks',
  '/Users/nicolae.surdu/.npm-global/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/nicolae.surdu/work/<my-app>/hooks' ]
BeforeHookName for command install is before-install
Installing /Users/nicolae.surdu/work/<my-app>/platforms/ios/build/device/myApp.ipa on devices with identifiers: 5784c839f6bde322f71ed053979b3459900e92d5.
Error while executing ios device operation: Could not install application with code: -402620394
Failed to install /Users/nicolae.surdu/work/<my-app>/platforms/ios/build/device/myApp.ipa on device with identifier 5784c839f6bde322f71ed053979b3459900e92d5. Error is: Could not install application
Unable to apply changes on device: 5784c839f6bde322f71ed053979b3459900e92d5. Error is: Failed to install /Users/nicolae.surdu/work/<my-app>/platforms/ios/build/device/myApp.ipa on device with identifier 5784c839f6bde322f71ed053979b3459900e92d5. Error is: Could not install application.
Project dir from hooksArgs is: /Users/nicolae.surdu/work/<my-app>.
Hooks directories: [ '/Users/nicolae.surdu/.npm-global/lib/node_modules/nativescript/lib/hooks',
  '/Users/nicolae.surdu/.npm-global/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/nicolae.surdu/work/<my-app>/hooks' ]
AfterHookName for command watch is after-watch
Project dir from hooksArgs is: /Users/nicolae.surdu/work/<my-app>.
Hooks directories: [ '/Users/nicolae.surdu/.npm-global/lib/node_modules/nativescript/lib/hooks',
  '/Users/nicolae.surdu/.npm-global/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/nicolae.surdu/work/<my-app>/hooks' ]
AfterHookName for command liveSync is after-liveSync
```

Versions:
```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.4.1           │ 3.4.1          │ Up to date  │
│ tns-core-modules │ 3.4.0           │ 3.4.0          │ Up to date  │
│ tns-android      │ 3.4.1           │ 3.4.1          │ Up to date  │
│ tns-ios          │ 3.4.1           │ 3.4.1          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘

$ npm --version
4.6.1

$ node --version
v7.7.2
```

### PR DESCRIPTION
**Pull request by kmmccafferty96**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.

## What is the current behavior?

https://github.com/NativeScript/nativescript-cli/issues/5293

## What is the new behavior?

Fixes https://github.com/NativeScript/nativescript-cli/issues/5293.

### CODE REVIEW

**Comment by vtrifonov** [comment]
test

**Comment by kmmccafferty96** [comment]
I don't think the code-modules-tests are failing due to my changes, but I can't reach http://nsbuild01.telerik.com to check.

**Comment by vtrifonov** [comment]
test

**Comment by vtrifonov** [comment]
sure, we'll check what the problem is!

**Comment by vtrifonov** [comment]
test

**Pull request merged**
