### PR TITLE
text-field hint now can be set to number

### LINKED ISSUE #790: Cannot use number values in EditableText's hint field
`<TextField hint="1" />`
`<TextField hint="0.0" />`

does not work, however it does work with strings that don't contain numbers.

And throws this error for iOS:

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber length]: unrecognized selector sent to instance 0xb000000000000012'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107207f65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000106c81deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010721058d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010715df7a ___forwarding___ + 970
	4   CoreFoundation                      0x000000010715db28 _CF_forwarding_prep_0 + 120
	5   UIKit                               0x0000000105dc87a8 -[UITextField setPlaceholder:] + 45
	6   mobile                              0x000000010458f33c ffi_call_unix64 + 76
	7   ???                                 0x00007fff5bc62650 0x0 + 140734733100624
)
libc++abi.dylib: terminating with uncaught exception of type NSException

```

### PR DESCRIPTION
**Pull request by enchev**
Fixed #790

### CODE REVIEW

**Comment by enchev** [comment]
run ci

**Comment by nsndeck** [comment]
:+1:

**Comment by dtopuzov** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Pull request merged**
