### PR TITLE
feat: (iOS dialog size using CSS) Set dialog size using CSS or attribute like android

### PR DESCRIPTION
**Pull request by slolam**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
To size a dialog in iOS, one has to pass extra iOS specific attributes to ModalDialogService unlike Android. Android uses CSS or dialog root element attributes to size the dialog.

## What is the new behavior?
Like Android, this change will use CSS or attributes on the dialog root element to determine the size of the dialog. The existing code that uses iOS specific dialog size information passed to ModalDialogService will continue to work. However, any CSS or attribute size will override the existing size information passed using ModalDialogService parameters.

Fixes/Implements/Closes #[Issue Number].
#8698

### CODE REVIEW

**Comment by farfromrefug** [comment]
Option width and height should be preferred. Consequently it should be an if else. Also you should handle percentage too as you can compute it from the parent controller

**Comment by slolam** [comment]
> Option width and height should be preferred. Consequently it should be an if else. Also you should handle percentage too as you can compute it from the parent controller

@farfromrefug, I could move the code into else block, however, I wanted make an headway for the people to use CSS & attributes over Options to be consistent with Android. Since, I was working only on NativeScript iOS, I came up with the Options for width & height back then in my previous pull request for dialog size. Now that I work on both iOS and Android I don't appreciate the inconsistency between them both the platforms when it comes to dialog size.

As I said, the purpose is to make it consistent with Android. Android does not support percentage width and height. Trying to do it for iOS does not make a lot of sense. 

Please let me know if you want me to move the code to else block.

Thanks.

**Comment by farfromrefug** [comment]
OK i get it. I would go for android changes to. 
One thing is that when using options width and height I like not to have that handler running for nothing. It can hurt perfs in a sense, not a heavy compute but the sum of little things can turn up to be a big thing!
About percentage same thing would be best to have it on both.

That being said if this PR only brings the same behavior I guess it is good enough. Maybe a todo comment ?

**Comment by slolam** [comment]
> OK i get it. I would go for android changes to.
> One thing is that when using options width and height I like not to have that handler running for nothing. It can hurt perfs in a sense, not a heavy compute but the sum of little things can turn up to be a big thing!
> About percentage same thing would be best to have it on both.
> 
> That being said if this PR only brings the same behavior I guess it is good enough. Maybe a todo comment ?

Added TODO comment, I have already moved the handler code into else block in my previous commit.

**Comment by slolam** [comment]
Hey @farfromrefug, anything you are waiting from my side or this PR is good to go?

**Comment by farfromrefug** [comment]
@slolam sorry I don't the rights to merge your PR right now. Nathan will look at this. Simply a lot of things happening right now ;)

**Comment by NathanWalker** [comment]
Nice work @slolam sorry for delay, appreciate the contribution!

**Pull request merged**
