### PR TITLE
feat: add option to set a different root view at run time

### PR DESCRIPTION
**Pull request by MartoYankov**
Expose a method to open a new root view when your app is running. It will be useful for test apps and angular livesync.

### CODE REVIEW

**Comment by SvetoslavTsenov** [comment]
test cuteness uitests

**Comment by SvetoslavTsenov** [comment]
Hey @MartoYankov, can you check this unittest please 
http://nsbuild01.telerik.com:8080/build/job/integration-tests-stable-unittestapp-android-api23-emulator/1830/artifact/target/surefire-reports/html/index.html

**Comment by hshristov** [comment]
There is `root` property on `application.launch` event args. If you attach listener to this event and then call `frame.reloadPage` method you will be able to set the rootView in the `eventArgs.root`.
And this changes will lose the root view once Activity is destroyed!

**Comment by SvetoslavTsenov** [comment]
test api25

**Comment by SvetoslavTsenov** [comment]
test api25 api27

**Comment by vakrilov** [comment]
@hshristov 
Can you elaborate a bit. I'm guessing you are talking about that we are no longer caching the rootView inside [`(<any>app).rootView`](https://github.com/NativeScript/NativeScript/pull/5386/files#diff-c1ad77120477acf9bacdaabe6af2518dL959)?
Will getting the rootView with `application.gettRootView()` in `frame.reloadPage` resolve the issue?

**Comment by SvetoslavTsenov** [comment]
test

**Pull request merged**
