### PR TITLE
perf: additional GridLayout optimizations

### PR DESCRIPTION
**Pull request by SeanKelly369**
Optimised of the gridlayout code for iOS.  Use in a production app, with no breaking changes.

### CODE REVIEW

**Comment by vallemar** [comment]
@SeanKelly369 Have you done any performance testing?

**Comment by SeanKelly369** [comment]
I did for the app for work within a CollectionView table.

**Comment by NathanWalker** [comment]
@SeanKelly369 when possible, if you can sign the CLA as mentioned here?

**Comment by SeanKelly369** [comment]
Going to focus on smaller PRs and run tests, from now on.

**Pull request closed without merging**
