### PR TITLE
add required interface for generalized listview comonent

### PR DESCRIPTION
**Pull request by PeterStaev**
Adds an interface needed for https://github.com/NativeScript/nativescript-angular/issues/1222

### CODE REVIEW

**Comment by vakrilov** [comment]
test

**Comment by vakrilov** [comment]
test

**Comment by manoldonev** [comment]
test

**Comment by SvetoslavTsenov** [comment]
test

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
test

**Comment by SvetoslavTsenov** [comment]
test

**Pull request merged**
