### PR TITLE
[Do Not Merge] chore(e2e): skip specific test suites with known issues on android / ios

### PR DESCRIPTION
**Pull request by manoldonev**
Currently we have the following known issues:
- [Android] https://github.com/NativeScript/NativeScript/issues/6798
- [iOS] https://github.com/NativeScript/NativeScript/issues/6728

This PR skips specific test suites taking into account the issues above so e2e is green for the rest of platform/version combos:
- On Android API level 19 skip all tests with "Flip" transition navigation
- On iOS skip all tests with layout root and "Slide" transition navigation

### CODE REVIEW

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api19 api21 api23 api25 api27 api28

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api19 api20 api21 api22 api23 api24 api25 api26 api27 api28

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api19 api23 api25

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api19 api23 api25

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api19 api20 api21 api22 api23 api24 api25 api26 api27 api28

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api19 api20 api21 api22 api23 api24 api25 api26 api27 api28

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api19 api20 api21 api22 api23 api24 api25 api26 api27 api28

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api19 api21 api22 api23 api24 api25 api26 api27 ios11 api17 api28 ios10 iosx

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api19 api21 api22 api23 api24 api25 api26 api27 api28 ios10 ios11 iosx

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api19 api21 api22 api23 api24 api25 api26 api27 api28 ios10 ios11 iosx

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api19 iosx

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api28

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api28 iosx

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api28

**Comment by SvetoslavTsenov** [comment]
test

**Comment by SvetoslavTsenov** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api28 api23 ios11 ios12

**Comment by SvetoslavTsenov** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api28 api23 ios11 ios12

**Comment by SvetoslavTsenov** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api27 api23 ios11 ios12

**Comment by SvetoslavTsenov** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api28 api23 ios11 ios12

**Comment by SvetoslavTsenov** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api28

**Comment by SvetoslavTsenov** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api19 api20 api21 api22 api23 api24 api25 api26 api27 api28 ios11 ios12

**Comment by SvetoslavTsenov** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test api28 api23 ios11 ios12

**Comment by SvetoslavTsenov** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test ios11 ios12 api19 api21 api22 api23 api24 api25 api26 api27 api28

**Comment by SvetoslavTsenov** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-test ios11 ios12 api19 api21 api22 api23 api24 api25 api26 api27 api28

**Pull request merged**
