### PR TITLE
backgroundColor added in ActionBarStyler

### PR DESCRIPTION
**Pull request by zh-m**
backgroundColor property is added in the ActionBarStyler property thus allowing changing it runtime. 
The ui-test is updated so that scenarios for android only are recognized more easily.

### CODE REVIEW

**Comment by vchimev** [comment]
build

**Comment by vchimev** [comment]
build

**Comment by vchimev** [comment]
build

**Comment by hshristov** [comment]
run ci

**Comment by vchimev** [comment]
build

**Comment by vchimev** [comment]
build

**Pull request merged**
