### PR TITLE
fix(ios-image-asset): getImageAsync() can retrieve assets stored remotely in iCloud

### LINKED ISSUE #5704: iOS: getImageAsync() fails if PHAsset is in iCloud (remote)
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes.

### Tell us about the problem
ImageAsset.getImageAsync(), and thus ImageSource.fromAsset(), fails if the PHAsset is remotely stored in iCloud and must be retrieved over the network as described [here](https://developer.apple.com/documentation/photos/phimagerequestoptions/1616934-networkaccessallowed?language=objc).

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI:
4.0.0
- Cross-platform modules:
4.0.0
- Runtime(s):
"tns-android": "4.0.0"
"tns-ios": 4.0.1"
- Relevant plugins:
"nativescript-imagepicker": "6.0.1"

### Please tell us how to recreate the issue in as much detail as possible.
The asset must be in Photos, but not stored locally, and available in the cloud

### PR DESCRIPTION
**Pull request by DickSmith**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [N/A] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
getImageAsync() cannot retrieve assets stored remotely in iCloud

## What is the new behavior?
getImageAsync() can retrieve assets stored remotely in iCloud

Fixes #5704 .

### CODE REVIEW

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
Hey @DickSmith - can you sign the CLA at http://www.nativescript.org/cla?
Also, can you update your commit message to follow the guidelines listed [here](https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#-commit-message-guidelines)

**Comment by vakrilov** [comment]
**Note**: You can check the em-mail you should sign the CLA with in the [info of your commit](https://github.com/NativeScript/NativeScript/commit/14d06c14ee71678e88e187a8c418e2c211124371.patch)

**Comment by DickSmith** [comment]
@manoldonev @vakrilov 

Sorry about that, I forgot which email was tied to this commit. 😀 

Also, I updated the Subject Header. I think it's correct now?

**Comment by manoldonev** [comment]
test

**Pull request merged**
