### PR TITLE
fix(action-bar): #5743 navController may be null

### PR DESCRIPTION
**Pull request by DickSmith**
Fix for #5743
From my own Crashlytics:
`stderr: file:///app/vendor.js:1:860568: JS ERROR TypeError: null is not an object (evaluating 'a.viewControllers')`
```
file:///app/vendor.js:1:860489
var l,p=a.viewControllers.indexOfObject(n);if(p>0&&p<a.viewControllers.count&&(t=a.viewControllers[p-1]),t)
```
which corresponds to:
https://github.com/NativeScript/NativeScript/blob/2fc1d8a8d4cf64e98eb98296e21564ac9b508f95/tns-core-modules/ui/action-bar/action-bar.ios.ts#L132

further up `navController` is checked for truthiness:
https://github.com/NativeScript/NativeScript/blob/2fc1d8a8d4cf64e98eb98296e21564ac9b508f95/tns-core-modules/ui/action-bar/action-bar.ios.ts#L119

So applying same logic.

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

### CODE REVIEW

**Comment by vakrilov** [comment]
Having no `navigationController`/`navigationBar` will cause more trouble in this method [here](https://github.com/DickSmith/NativeScript/blob/c4915336a41a4504c1fb9db32aab546d99b43926/tns-core-modules/ui/action-bar/action-bar.ios.ts#L157-L164) and [here](https://github.com/DickSmith/NativeScript/blob/c4915336a41a4504c1fb9db32aab546d99b43926/tns-core-modules/ui/action-bar/action-bar.ios.ts#L175-L179) where there is no guards. 

I would suggest that we do the check for missing `navigationController` in the beginning of the method and just return if the is none (the same way we do in if there is [no page or frame](https://github.com/DickSmith/NativeScript/blob/c4915336a41a4504c1fb9db32aab546d99b43926/tns-core-modules/ui/action-bar/action-bar.ios.ts#L112-L114).

**Comment by DickSmith** [comment]
@vakrilov 
Perfect, will do.

**Comment by DickSmith** [comment]
@vakrilov 
Updated.

**Comment by vakrilov** [comment]
test

**Comment by manoldonev** [comment]
test

**Pull request merged**
