### PR TITLE
Implement the BorderDrawable class used in background.android.ts in Java

### LINKED ISSUE #2318: Implement the BorderDrawable class used in background.android.ts in Java

### PR DESCRIPTION
**Pull request by hamorphis**
Resolves #2318

### CODE REVIEW

**Comment by vchimev** [comment]
uitests android

**Comment by hamorphis** [comment]
uitests android

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
We should merge the PR to widgets, build it and then run tests.

**Comment by hamorphis** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
uitests android

**Comment by hamorphis** [comment]
uitests android

**Comment by hamorphis** [comment]
run ci

**Comment by hamorphis** [comment]
cuteness

**Comment by hamorphis** [comment]
uitests ios

**Comment by vchimev** [comment]
uitests android

**Comment by vchimev** [comment]
cuteness android

**Comment by vchimev** [comment]
uitests android

**Pull request merged**
