### PR TITLE
Update iOS TypeScript declarations with iOS 10 beta 6

### PR DESCRIPTION
**Pull request by jasssonpet**
For more information about API changes: https://developer.apple.com/library/prerelease/content/releasenotes/General/iOS10APIDiffs/

~~Generated and working only with this iOS PR - https://github.com/NativeScript/ios-runtime/pull/612~~ Should be working with the 2.3 release.

Metadata is generated on build against the currently installed Xcode and has to match that in these TypeScript declarations, so Xcode 8 - beta 6 is required for running tests and apps. The docs have to be updated if this is to be merged.

These should be also updated with the official Xcode release.

Closes https://github.com/NativeScript/NativeScript/issues/2456

### CODE REVIEW

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by jasssonpet** [comment]
Closing in favor of https://github.com/NativeScript/NativeScript/pull/2702.

**Pull request closed without merging**
