### PR TITLE
chore: update dev workflow for Angular app

### PR DESCRIPTION
**Pull request by rynop**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?

When trying to contribute to `tns-core*`, and using an external NS Angular to develop/test these contributions, the compile step fails when following the instructions currently outlined in [DevelopmentWorkflow.md](https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-another-app) (Running Another App).

@bundyo [discovered](https://github.com/NativeScript/nativescript-dev-webpack/issues/1044#issuecomment-533397897) this workaround, I'll paste his findings here:

> The problem with linking is that Angular/TS project tend to grab the linked TS files in core modules and try to compile them without the references needed. I've only managed to run it by compiling the core modules with outDir and linking that (.d.ts, package.json and other files, except TS ones should be copied over too). Maybe the team can consider moving to an outDir compilation. Another way would be dev-webpack to forbid Angular/ts-loader for traversing node_modules.

## What is the new behavior?

This PR contains a workaround for Angular that moves `tns-core*` to a new `dist` directory.

This workflow is obviously not ideal.  Would love the NativeScript team's thoughts on a cleaner solution.

Fixes https://github.com/NativeScript/nativescript-dev-webpack/issues/1044 and https://github.com/NativeScript/NativeScript/issues/7745

### CODE REVIEW

**Comment by MartoYankov** [comment]
While this works it requires lots of manual work, which is not ideal. Imho, it should work the same for Angular and TS project. Here are my thoughts:

1. The Angular compiler seems to ignore or fail to resolve the references.d.ts in the tns-core-modules folder. If you add `tns-platform-declarations` and a `references.d.ts` to your app, the required references will be there. We can add this to the steps.
2. It seems that even when you do 1. the Angular compiler still doesn't like the typescript in the core modules. We should perhaps investigate these errors. They seem to be connected to the interface exports in the d.ts files.

**Comment by bundyo** [comment]
I'll make some tests where the problem is, since it is happening only in Angular (though I might have seen it in Vue+TS) and then we can address it in dev-webpack or, if not possible - create an automated script to deploy to another folder.

**Comment by MartoYankov** [comment]
@bundyo I followed the steps from "running another app" plus one additional step - adding the `tns-platform-declarations` packages to the app. The errors that the ng compiler producers are with types and exports. I suspect these still happen in the regular `ts-loader`, but as warnings. The ng compiler is producing them as errors.

The reason why we don't want to promote alternative dev setups is because we can't support them. We adhere to the dev setup in the nativescript plugin seed to make sure the `tns-core-modules` have a similar setup to all plugins. What I mean is, we should fix the current setup or if not possible - change the dev setup in the plugin seed first.

**Comment by manoldonev** [comment]
@rynop as elaborated by @MartoYankov I have logged a separate issue https://github.com/NativeScript/NativeScript/issues/7905 that we will need to address to fix the dev workflow in this scenario. I will close this PR for the time being.

**Pull request closed without merging**
