### PR TITLE
Fix CssAnimationProperty default value

### PR DESCRIPTION
**Pull request by hshristov**

### CODE REVIEW

**Comment by vakrilov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
run animations

**Comment by SvetoslavTsenov** [comment]
run animations

**Comment by SvetoslavTsenov** [comment]
run animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by SvetoslavTsenov** [comment]
animations

**Comment by dtopuzov** [comment]
animations

**Pull request merged**
