### PR TITLE
fix(ios/bottom-navigation): Changing tabs programatically messes up styles

### LINKED ISSUE #7667: [BottomNav][iOS] Changing tabs programatically messes up styles
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.0
 - Cross-platform modules: 6.0.0
 - Android Runtime: 6.0.0
 - iOS Runtime: 6.0.0
 - Plugin(s):

**Describe the bug**
When you change the `selectedIndex` programatically the tab actually changes but the styles are not applied, so visually the old tab remains selected and the new one looks like unselected. Works as expected on android. 

**To Reproduce**
https://play.nativescript.org/?template=play-tsc&id=ill2KK 
tap on button in the action bar

**Expected behavior**
Styles to be applied correctly. 

**Sample project**

**Additional context**

Related to #6967

### PR DESCRIPTION
**Pull request by ycherniavskyi**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
Currently, TabStrip items event emitting only when user click on UITabBar within processing `tabBarControllerDidSelectViewController` handler method of `UITabBarControllerDelegate` class. That is why when `selectedIndex` property changed programmatically TabStrip styling messed up.

## What is the new behavior?
Current fix, just move TabStrip items event emitting into `onSelectedIndexChanged` handler, which called on processing `tabBarControllerDidSelectViewController` handler method (within `_onViewControllerShown` method) and on processing `selectedIndex` property changed programmatically.

Fixes/Implements/Closes #7667.

### CODE REVIEW

**Comment by ycherniavskyi** [comment]
@MartoYankov I see that you supervise the TabView component developing, maybe you could check this small PR, which fix really annoying for iOS developer issue.

**Comment by vakrilov** [comment]
Hi @ycherniavskyi 
We were busy preparing the 6.3 release and this will probably won't make it in as we are already in a code-freeze phase.
However, it is a patch so we can probably release it as a patch (`6.3.x`) when it gets merged.

**Comment by ycherniavskyi** [comment]
@vakrilov thank you for clarification, so I am waiting for the 6.3 patch release.

**Comment by vtrifonov** [comment]
test

**Pull request merged**
