### PR TITLE
feat: add number & phone inputType for prompt dialog

### LINKED ISSUE #6363: Feature: New Dialog Prompt Input Type for Phone / Numbers
**Is your feature request related to a problem? Please describe.**

PromptOptions when creating a dialog.prompt currently takes inputType as an option.

It is only limited to text, password or email.

There are cases when it is nice to take a number as an input, where the keypad is restricted to numbers only, instead of taking any string, and then checking if it is a number, and if not, reshowing the prompt.

**Describe the solution you'd like**

Would like to add an option called number to inputType, and show the numeric keypad in case the inputType is set to number.

**Additional context**
I'm assuming this would be similar to #3118. If it will be similar, I can create a PR for the same and send it for review.

### PR DESCRIPTION
**Pull request by shyamseshadri**
Add an inputType number to the PromptOptions for dialogs

Closes #6363

## PR Checklist

- [X] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [X] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [X] You have signed the [CLA](http://www.nativescript.org/cla).
- [X] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?

This is to support #6363 

Currently, NativeScript only allows accepting inputType email, phone and password to prompt dialog.

## What is the new behavior?

This change adds a inputType number which shows the numeric pad in android and iOS for dialog prompts

Fixes/Implements/Closes #6363 .

### CODE REVIEW

**Comment by vakrilov** [comment]
Hey @shyamseshadri,

Thanks for the PR! The code looks good.

Would you mind adding a showcase of the new option [along with the other prompt types in this test page](https://github.com/NativeScript/NativeScript/blob/master/apps/app/ui-tests-app/dialogs/dialogs.xml#L8-L10).

**Comment by shyamseshadri** [comment]
hey @vakrilov , let me know if this looks good or if you need me to make any other changes.

**Comment by vakrilov** [comment]
test

**Comment by vakrilov** [comment]
Hey @shyamseshadri - thanks again for the PR!
We are currently in a code-freeze phase for the NativeScript 5.0 release. This means it might take more time to merge PRs into master.

We will notify you if the is some action needed form your side. 
Thanks for understanding and being awesome part of the NS community!

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
merging this -- agreed with @SvetoslavTsenov that he will update the images for the failing ui dialog tests: http://nsbuild01.telerik.com:8080/build/job/pr-composite-ns-core-modules/733/

**Comment by radeva** [comment]
Hi @shyamseshadri ,

Congratulations on being one of the winners in the {N} First-time contributors contest! 

You can claim your prize by contacting us at nativescriptwinners[at]progress.com not later than Nov 30th 2018 . Make sure you send us the following info: 
👉Your full name 
👉Your email 
👉Your country or residence 

Best regards,
The NativeScript Team

**Pull request merged**
