### PR TITLE
fix: #8622

### LINKED ISSUE #8622: [UPDATED] Live-Sync & page.minWH#.xml problem.
**Environment**
 - CLI: 6.4
 - Cross-platform modules:
 - Android Runtime: 6.4.1
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
If you perform changes to a page that is screen resolution-specific (e.g. home-items-page.minWH120.xml), live-sync will fail to load corresponding script file and will try to look for home-items.page.minWH120.js. This bug occurs when using CLI (tns run), and does not apply to NativeScript Playground.

**To Reproduce**
Run app using CLI and perform a change (e.g. backgroundColor) to home-items-page.minWH120.xml.
Even though I share a playground sample, this bug occurs only when using CLI (tns run), and does not apply to NativeScript Playground.

**Expected behavior**
Page should be fully reloaded without issues.

**Sample project**
https://play.nativescript.org/?template=play-js&id=bHuiUa&v=8

**Additional context**
This extremely annoying live-sync bug occurs only when using CLI (tns run), and does not apply to NativeScript Playground. Furthermore, this has to be tested on a device that meets page dimension critiria.

### PR DESCRIPTION
**Pull request by DimitrisRK**
A dirty hack for taking care qualifier-based pages issues during hot module reload.

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
Live-sync fails to load script and style files <file-name>.<extension> (e.g. js, css) for <file-name>[.<qualifier>]*.xml files.

## What is the new behavior?
Reload will work.

Closes #8622 .

This way of making module-resolve reload these files is quite dirty, so I hope there'll be a better alternative of extracting qualifiers from file paths.

### CODE REVIEW

**Comment by NathanWalker** [comment]
Thanks @DimitrisRK 👍  - we'll wanna check against Angular and Vue projects to make sure doesn't cause any side effects.

**Comment by DimitrisRK** [comment]
> Thanks @DimitrisRK 👍 - we'll wanna check against Angular and Vue projects to make sure doesn't cause any side effects.

@NathanWalker Considering Angular filename formats, I suspect there might really be issues since my patch extracts qualifiers by splitting path, using dot "." as separator. At the same time, I'm working on finding a more accurate solution.

**Comment by DimitrisRK** [comment]
@cla-bot check

**Comment by DimitrisRK** [comment]
@NathanWalker After few tests of mine with angular and vue app samples, it seems that this module resolver isn't being used for these frameworks's components, but only for NS Core modules.

Either way, I worked on qualifier-matcher and used regular expressions in certain cases.
This way, a great accuracy is achieved in retrieving qualifiers from file names.

### Example:

Before this update:
home-page.component.minWH360.js -> Qualifier-matcher will consider 'component' to be a qualifier that does not meet conditions and ignore this file.

After this update:
home-page.component.minWH360.js -> Qualifier-matcher will only retrieve 'minWH360' qualifier using a regular expression and if condition is met, file will be (re)loaded.

Of course, if this is too complicated and unwanted, there is always the option of first commit with split and join.

Please feel free to make tests in depth.

**Comment by NathanWalker** [comment]
Thanks @DimitrisRK, really appreciate the effort here. Possible to add just a sample component to the `e2e/ui-tests-app`? This will help lock the desired behavior in to test against as well as help keep track of any possible regressions that could be affected (sounds like none but to be sure).

**Comment by DimitrisRK** [comment]
@NathanWalker Done. Hope this sample is helpful.

**Comment by NathanWalker** [comment]
Thanks for another excellent contribution @DimitrisRK - this will go out with another round of updates at end of week 👍

**Comment by DimitrisRK** [comment]
> Thanks for another excellent contribution @DimitrisRK - this will go out with another round of updates at end of week 👍

Sounds great. By the way, it seems I missed a semicolon at the end of https://github.com/NativeScript/NativeScript/blob/master/nativescript-core/module-name-resolver/qualifier-matcher/qualifier-matcher.d.ts. Since it's at the end of the file it's causing no issues, I just wanted to point out that small omission.

**Comment by NathanWalker** [comment]
@DimitrisRK one thing I noticed is that the unit tests fail with these changes. Although it's merged we may hold on releasing it until the unit tests pass. To run them do the following from root of repo:
```
cd tests
tns run ios --emulator
```

The results of the tests will output in the simluator and in console and note that most all the failures are from the qualifier matchers. Not sure if tests need to be updated or if this indicates these changes may have introduced regression. Can you give it a shot and if you see same issue you might check and can submit another PR to clear 👍

**Comment by DimitrisRK** [comment]
@NathanWalker I apologize for the inconvenience. It seems there were things I missed. I submitted PR #8658 .
Its latest 4 commits are additions supposed to solve pending problems. Thanks to these additions, I ran unit tests on my computer without issues. If by any chance you still get failures, please let me know.

**Pull request merged**
