### PR TITLE
Action item custom view

### PR DESCRIPTION
**Pull request by PeterStaev**
Implements #1488

### CODE REVIEW

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
:+1:

**Comment by vakrilov** [comment]
:+1: 
Looks good to me - I suggest we merge this for 1.7 release.

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Pull request merged**
