### PR TITLE
refactor(android-tabview): adapter data change called unnecessary

### PR DESCRIPTION
**Pull request by MartoYankov**
Android TabView pager adapter's notifyDataSetChanged() was called unnecessary too many times, which causes the view pager to refresh.

Changes:
1. Remove setAdapterItems() from initNativeView and disposeNativeView since it's called in onLoaded and onUnloaded.

2. Add a check that calls notifyDataSetChanged() only if the newly assigned items are different. Both onLoaded and the items binding are calling it simultaneously on navigate.

### CODE REVIEW

**Comment by SvetoslavTsenov** [comment]
test ios10 api25 uitests

**Comment by SvetoslavTsenov** [comment]
test ios10 api25 uitests

**Comment by SvetoslavTsenov** [comment]
test api25 uitests

**Comment by MartoYankov** [comment]
test api25 uitests

**Comment by SvetoslavTsenov** [comment]
test  uitests

**Comment by SvetoslavTsenov** [comment]
👍

**Pull request merged**
