### PR TITLE
Fix #817

### LINKED ISSUE #817: timers.clearInterval doesn't work on Android
The following code doesn't clear the interval and the callback gets executed infinitely:

```js
mV = vm.progressViewModel.get("maxValue"); // 100
    vm.progressViewModel.set("currentValue", 0);

    // create a repeating timer to jump our progress value
    t = timer.setInterval(function () {
        var cV = vm.progressViewModel.get("currentValue");
        var nV = cV + 5;
        console.log("new: " + nV + ", max: " + mV);
        if (nV >= mV) {
            console.log(">=!!!");
            timer.clearInterval(t);
        } else {
            vm.progressViewModel.set("currentValue", nV);
        }
    }, 500);

```

### PR DESCRIPTION
**Pull request by atanasovg**

### CODE REVIEW

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by enchev** [comment]
:+1:

**Comment by enchev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by enchev** [comment]
I've just noticed that there is no test. Can we add one?

**Pull request merged**
