### PR TITLE
SegmentedBar selectedIndexChanged added

### PR DESCRIPTION
**Pull request by enchev**
Implemented #698

### CODE REVIEW

**Comment by enchev** [comment]
run ci

**Comment by hdeshev** [comment]
:+1:

**Comment by sitefinitysteve** [comment]
I have tried using the latest version of this widget, and the event just doesn't trigger...?

viewModel = new observable({
    index: 1
});

<SegmentedBar selectedIndexChanged="changed" selectedIndex="{{ index }}">

Doing something wrong?

**Comment by jlooper** [comment]
@sitefinitysteve and I are battling this over - I have installed 1.3 (hope I did it right) and created a new sample app (tns --version = 1.3). In the xml, the 'changed' function on selectedIndexChanged doesn't seem to fire.... so not sure if I'm going at this properly.

**Comment by NathanaelA** [comment]
I have **quickly** built this site: http://nativescript.rocks/ -- you can download the latest master from it, should auto build the latest master daily.  ;-D

**Comment by NathanaelA** [comment]
@jlooper - **tns --version** only tells you the version of the tns/nativescript command line version.  You need to be running the current master version of the Core/Common modules (which is this github repo) to test this functionality.   Since Telerik currently doesn't have available the nightly master pre-built; that is what the http://nativescript.rocks site will allow you to easily download without having to get everything installed to build the master's..    

@sitefinitysteve - if you are running a master version before 2 days ago; you won't have the new commit.   And just like Jen, you can now pull the latest master's from http://nativescript.rocks

**Comment by jlooper** [comment]
@NathanaelA thank you, I appreciate! The core modules in the .tgz file don't appear to contain this most recent change, however. So I think I must wait until 1.3 to really trap a selectedIndexChangedEvent. I'm hoping there will be some sample code to fix up the docs as well. @enchev will this be released with 1.3?

thanks!

**Comment by NathanaelA** [comment]
@jlooper -- Thanks for letting me know.   I made a silly mistake in my NativeScript common core build script --  I just fixed the script and re-built the masters on the site.      I even double checked that this change is NOW in the master on my site for you.   Sorry about that; but thank you for letting me know the Nativescript.rocks site wasn't up to date...

**Pull request merged**
