### PR TITLE
Refer to current _map, not most recent _map in Observable

### PR DESCRIPTION
**Pull request by jjd314**
The `Observable` module uses `defineProperty` every time a new `Observable` is made, and the get/set methods refer to the `that` variable in the closure.  The result is that If you call `new Observable()` multiple times on objects that have identical properties (like `Observables` in an `ObservableArray`, as in [this StackOverflow question](http://stackoverflow.com/questions/31898061/observable-in-listview-binds-elements-incorrectly)), all the `Observables` will access/update only the last object's properties.

I changed the get/set methods to use `this`, which solves the immediate problem.  It still seems inefficient to redefine the get/set methods every time an `Observable` is created.  Also, every `Observable` will have every observable property from any other `Observable` defined for it, which seems odd, but not the worst possible problem, I suppose.

### CODE REVIEW

**Comment by hamorphis** [comment]
Thank you for your work. We will need some kind of a unit test which we can add to our test suite. The test must fail before the suggested changes and it must pass after we make the suggested changes.

**Comment by jjd314** [comment]
Thanks @hamorphis.  I took a stab at adding the test to the test suite.  I apologize in advance if I did not follow your conventions for it.  If it is not correct as is, the test is very simple and I hope it won't be too much trouble for you to move it to where it should be.

**Comment by hamorphis** [comment]
@jjd314 I will take a look at it today. Thank you so much.

**Comment by dtopuzov** [comment]
run ci

**Comment by hamorphis** [comment]
I have extended the unit test a little bit, made some refactoring and created a new pull request: https://github.com/NativeScript/NativeScript/pull/927

**Pull request closed without merging**
