### PR TITLE
Do not change the Android layer types (hardware/software)

### PR DESCRIPTION
**Pull request by PanayotCankov**
I don't know why we did this in the first place,
but changing the rendering mode can not be good.
Let's re-run all possible UI tests.

### CODE REVIEW

**Comment by PanayotCankov** [comment]
run ci

**Comment by NathanaelA** [comment]
The reason that we were using Hardware layers is for speed.  If you eliminate the hardware layers the app itself will be slower when drawing things.      However, the reason there is code to disable it is because some ops are not supported in hardware mode; so it is switched to software mode while those ops are going on.

Maybe you should read this: https://developer.android.com/guide/topics/graphics/hardware-accel.html 

I am firmly against this patch, unless you can show a really good reason why slowing down the android platform is justified.

**Comment by PanayotCankov** [comment]
Ya red that,

A little while ago I removed some of the ops that were clipping images. Clipping with paths were not applying antialiasing on the images so they looked terrible anyway. Containers may not clip content when with rounded corners but that would be rarely a problem.

In general I think we should not mess internally with the rendering mode. "Hardware acceleration is enabled by default if your Target API level is >=14" and we will now never set it to software, so layers instead of forced to software every once in a while by {N}, should stay hardware all the time.

Now since we do not enable/disable hardware acceleration I think you can control it (e.g. on the windows) and it will be inherited by the views down the hierarchy. Or at least you can use the `<application android:hardwareAccelerated="true">` mentioned in the article you refer and the {N} won't mess with it.

Can you actually try the next versions of the widgets and the tns-core-modules in your app and verify that there is a performance hit?

**Comment by hshristov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
run android

**Comment by dtopuzov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
Hey, @PanayotCankov could try to rebase this pull request.

**Comment by bradmartin** [comment]
At one time, I think Enchev and I went back and forth on fixing an Android issue and it required changing the layer type. I can't recall the specifics, it was probably in late 2015 when I was working on some initial plugins for android components but something didn't work and we started stumbling on the layer types. If I find it, I'll drop a link. This might be totally unrelated but just wanted to throw it out there 😄

**Comment by bradmartin** [comment]
Ah so it was @vakrilov who helped, Enchev just cleaned up 👍 
https://github.com/NativeScript/NativeScript/issues/830#issuecomment-155374124

**Comment by PanayotCankov** [comment]
@bradmartin I think before we relied on Canvas clipping to round the button, and clipping was not antialiased and was not working properly on some devices, unless software mode is set. I think I prefer to keep the defaults now since the geometry is drawn for the button background using different Canvas APIs. If the issue reoccur, I'd like to rather provide a property on the view to control the rendering mode.

**Comment by SvetoslavTsenov** [comment]
uitests

**Comment by SvetoslavTsenov** [comment]
animations

**Pull request merged**
