### PR TITLE
feat(typings): Adding android typings for API levels from 17 to 27

### PR DESCRIPTION
**Pull request by vtrifonov**

### CODE REVIEW

**Comment by vakrilov** [comment]
test

**Comment by vtrifonov** [comment]
That's how the interface is named in [Java](https://developer.android.com/reference/android/content/SharedPreferences), so I think this is the proper way of using it. How do we mark the breaking changes in the `tns-platform-declarations` package?

**Comment by SvetoslavTsenov** [comment]
[unit-tests for css parser](https://github.com/NativeScript/NativeScript/tree/trifonov/typings-improvements/unit-tests) are failing to build

> NativeScript@ unit-test /home/travis/build/NativeScript/NativeScript
tsc -p tsconfig.unit-tests.json && mocha --opts unit-tests/mocha.opts
tns-core-modules/ui/frame/transition-definitions.d.ts(8,51): error TS2694: Namespace 'android' has no exported member 'animation'.

**Comment by vakrilov** [comment]
test

**Comment by vakrilov** [comment]
test

**Pull request merged**
