### PR TITLE
Define defaultValue for font-size to allow overwriting it.

### PR DESCRIPTION
**Pull request by Buuhuu**
Relates to #4234. 

I tested that on my app and it works as expected. Though I cannot estimate side effects

### CODE REVIEW

**Comment by vakrilov** [comment]
run ci

**Comment by vchimev** [comment]
Hey @Buuhuu,

there is a failing unit test for Android only:
```
I/JS      ( 1712): === ALL TESTS COMPLETE ===
I/JS      ( 1712): 1441 OK, 1 failed
E/JS      ( 1712): Test: TAB-VIEW.test_FontIsReappliedWhenTabItemsChange FAILED: Font must be the original one after resetting the style. [typeface] Actual: <null>(object). Expected: <android.graphics.Typeface@a5f25733>(object)
```
CC: @vakrilov

**Comment by vchimev** [comment]
I would like to execute our UI tests suites in order to measure the side effects (if any) before getting this merged.

**Comment by vchimev** [comment]
uitests

**Comment by vchimev** [comment]
uitests ios

**Comment by vakrilov** [comment]
Hi @Buuhuu 
Thanks for the contribution. However - let's first try to understand what the problem is (see #4234).
When we know what the issue is, we would be able to write a proper unit test and assure that it is solved for good.

**Comment by vakrilov** [comment]
Closing due to inactivity - please reopen needed.

**Pull request closed without merging**
