### PR TITLE
fix(dark-mode): formatted string and html view text color

### PR DESCRIPTION
**Pull request by vchimev**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

### CODE REVIEW

**Comment by vchimev** [comment]
test --ignore

**Comment by SvetoslavTsenov** [comment]
test --ignore api24 ios13 ios12 uitests

**Comment by SvetoslavTsenov** [comment]
test --ignore ios13 ios12 uitests

**Comment by vchimev** [comment]
test --ignore ios13 ios12 uitests

**Pull request merged**
