### PR TITLE
feat(ui): TouchManager for ease in adding interactivity

### PR DESCRIPTION
**Pull request by NathanWalker**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/DevelopmentWorkflow.md#running-unit-tests-application.

## What is the current behavior?

No easy way to add dynamic touch down/up animations for nice interactivity in the UI.

## What is the new behavior?

Introduces a `TouchManager` with an easy api to enable rich interactivity throughout the UI.
Also adds `touchAnimation` and `ignoreTouchAnimation` properties to views. This allows each view to opt into and define/control it's own touch down/up animations.

`TouchManager.enableGlobalTapAnimations = true` can also be used alongside `TouchManager.animations.{up|down}` animations to define consistent reusable animations for the entire UI by auto detecting and attaching to any view with a `tap` binding.

### CODE REVIEW

**Comment by farfromrefug** [comment]
@NathanWalker very nice. So we agree it is disabled by default?  maybe `enableGlobalTapAnimations` and other props should be initiated to `false`.
Also i think this should disabled by default for buttons. Dont you think? It is already handled natively

**Comment by NathanWalker** [comment]
Everything is disabled by default - completely opt-in. I’m writing a blog post which will break all this down, the why and how it unlocks Rich interactivity in ways that aren’t possible easily without quite bit of overhead (in case of iOS was not even possible given the inability to customize certain gestures by default without manually configuring natively).

**Comment by farfromrefug** [comment]
ok. then i think variables should be initialized to ensure the code is clear. and to prevent errors with like `!!` because the commonly used`!!` will return true for undefined.

**Comment by NathanWalker** [comment]
@farfromrefug all is safe as is regarding default values `undefined` is false with `!!` as expected:
```
> a = undefined
> !!a
false
```

**Comment by farfromrefug** [comment]
you are right my bad about the !! test. still think it should be a forced rule to always initialize class properties. it does not cost anything and brings clarity

**Pull request merged**
