### PR TITLE
Resolved #811: Page Navigation Transitions

### LINKED ISSUE #811: Page Navigation Transitions
Would be great to be able to customise the transitions between pages. Right now it's either animation or no animation. Both Android and iOS support custom transistions.

### PR DESCRIPTION
**Pull request by hamorphis**
Test app is located at `perf-tests/NavigationTest`

### CODE REVIEW

**Comment by hamorphis** [comment]
```
frame.topmost().navigate({
    moduleName: "some-page",
    animated: true,
    navigationTransition: {
        transition: "slide",
        duration: 400,
        curve: "easeOut"
    },
});
```

**Comment by hamorphis** [comment]
```
/**
     * Represents an object specifying a page navigation transition.
     */
    export interface NavigationTransition {
        /**
         * Either a string specifying one of the built-in transitions or an user-defined instance of the "ui/transition".Transition class.
         */
        transition: any;
        
        /**
         * The length of the transition in milliseconds. If you do not specify this, the default platform transition duration will be used.
         */
        duration?: number;

        /**
         * An optional transition animation curve. Possible values are contained in the [AnimationCurve enumeration](../enums/AnimationCurve/README.md).
         * Alternatively, you can pass an instance of type UIViewAnimationCurve for iOS or android.animation.TimeInterpolator for Android.
         */
        curve?: any;
    }
```

**Comment by hamorphis** [comment]
Example of a user-defined custom transition: 

- https://github.com/NativeScript/NativeScript/blob/transitions/apps/perf-tests/custom-transition.android.ts

- https://github.com/NativeScript/NativeScript/blob/transitions/apps/perf-tests/custom-transition.ios.ts

**Comment by hamorphis** [comment]
Built-in transitions:

- curl (same as curlUp) (iOS only)
- curlUp (iOS only)
- curlDown (iOS only)
- explode (Android Lollipop an up only)
- fade
- flip (same as flipRight)
- flipRight
- flipLeft
- slide (same as slideLeft)
- slideLeft
- slideRight
- slideTop
- slideBottom

**Comment by enchev** [comment]
:100:

**Comment by hamorphis** [comment]
TODO: Create extensive documentation article with animated gifs and sample code.

**Comment by hamorphis** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by hamorphis** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by hamorphis** [comment]
run ci

**Comment by hamorphis** [comment]
run ci

**Comment by hamorphis** [comment]
run ci

**Pull request merged**
