### PR TITLE
fix: animations continue after View unloaded

### LINKED ISSUE #9406: In android Animations continue after the view is unloaded, consuming resources.
**Environment**
√ Component nativescript has 8.0.2 version and is up to date.
√ Component @nativescript/core has 8.0.5 version and is up to date.
√ Component @nativescript/android has 8.0.0 version and is up to date.

**Describe the bug**
When an animation is specified through CSS on a view e.g. A Label, and this Label is unloaded e.g. by a *ngIf statement, the animation continues consuming resources in the background.

**To Reproduce**
I've attached a demo project, when you click the button to hide the labels the animations should stop.

**Expected behavior**
You can see the current behavior by profiling in android studio, cpu activity does not stop completely when the labels are unloaded ( by clicking the toggle button), and multiple toggles makes it more obvious.

**Sample project**
[animationLeak.zip](https://github.com/NativeScript/NativeScript/files/6510039/animationLeak.zip)

**Additional context**

I believe the issue is that the onUnloaded Method of CssState should call the stopKeyframeAnimations method to stop any existing animations.

Uncommenting ```accessPrivate._cssState.stopKeyframeAnimations();``` in the sample project does this and seems to fix the issue.

This does not appear to affect IOS.

### PR DESCRIPTION
**Pull request by jcassidyav**
## PR Checklist

- [X] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [X] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [X] You have signed the [CLA](http://www.nativescript.org/cla).
- [X] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/DevelopmentWorkflow.md#running-unit-tests-application.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/tools/notes/WritingUnitTests.md.

## What is the current behavior?
On Android animations continue to consume resources after the View has been unloaded.

## What is the new behavior?
Stop any running animations as the view is unloaded

Fixes/Implements/Closes #9406

### CODE REVIEW

**Review by NathanWalker — APPROVED** [review]

**Comment by NathanWalker** [comment]
@jcassidyav when you get a chance if you don’t mind signing the CLA once more - we updated it to reflect our affiliation with OpenJS now and just need resigning. Thanks again.

**Comment by jcassidyav** [comment]
@cla-bot check

**Comment by jcassidyav** [comment]
@NathanWalker all signed, thanks.

**Comment by pekevski** [comment]
Hi @NathanWalker would this leak have occurred in Android for a css animation on a view? Currently on v6.4 and notice a leak on a RadListView template item with a css class that has an infinite animation - profiling suggests that it consumes CPU forever. Looks like this patches it.

**Comment by NathanWalker** [comment]
@pekevski yes it should. You can add a custom pack of 6.4 core modules with this patch in place to confirm it in your app.

**Pull request merged**
