### PR TITLE
fix(tabs-ios9): no view controller managing visible view error

### PR DESCRIPTION
**Pull request by manoldonev**
Problem is related to `UIPageViewController.setViewControllers(_:direction:animated:completion:)` method when animated argument is `true`. For more information on the issue see https://stackoverflow.com/a/17330606.

Fixes: https://github.com/NativeScript/NativeScript/issues/7836

### CODE REVIEW

**Comment by manoldonev** [comment]
test

**Comment by SvetoslavTsenov** [comment]
test --ignore ios9 ios12 ios10

**Comment by manoldonev** [comment]
test --ignore ios9 ios12 ios10

**Comment by SvetoslavTsenov** [comment]
test --ignore ios9 ios12 ios10

**Comment by SvetoslavTsenov** [comment]
test --ignore ios9 ios12 ios10

**Comment by SvetoslavTsenov** [comment]
test --ignore ios9

**Comment by manoldonev** [comment]
test --ignore ios9

**Comment by manoldonev** [comment]
test --ignore ios9

**Comment by manoldonev** [comment]
test --ignore ios9

**Comment by manoldonev** [comment]
test --ignore ios9

**Pull request merged**
