### PR TITLE
Fix iOS ActionBar problem while internet sharing #4283

### PR DESCRIPTION
**Pull request by kssfilo**
for #4283 

This problem also happens while phone call.

It can be tested by Alt+Y  on emulator.

### CODE REVIEW

**Comment by SvetoslavTsenov** [comment]
run uitests

**Comment by SvetoslavTsenov** [comment]
run uitests

**Comment by vakrilov** [comment]
run ci

**Comment by vakrilov** [comment]
Hi, @kssfilo 
Thanks for the contribution!

We are currently running some tests on the PR.
Also we are preparing for the `3.1` release, the review of this PR might delay a couple of days.

**Comment by SvetoslavTsenov** [comment]
run uitests ios

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by vakrilov** [comment]
LGTM!

**Comment by vakrilov** [comment]
Merging!
10x for the great contribution @kssfilo

**Comment by jlooper** [comment]
hi @kssfilo, thanks for your awesome PR! You've earned a badge!

contrib

Ping me on Slack with your mailing address and I'll send you some NativeScript swag!

**Pull request merged**
