### PR TITLE
fix(iOS): check for iOS 13 APIs

### PR DESCRIPTION
**Pull request by vchimev**
### Scenario

Build the application with Xcode 10 (no iOS 13 APIs available) and deploy it to iOS 13.

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?

The application crashes.

## What is the new behavior?

The application runs and fallbacks to APIs < 13.

### CODE REVIEW

**Comment by james-criscuolo** [comment]
I see this is on the `release` branch, but it doesn't look like it actually made a tagged/NPM release. Is there any timeline for when this gets out? Without this, it doesn't seem like anyone with older Xcode versions can build for all ios end points (ios 13 phones crash on start), unless I'm missing something.

**Comment by MCorzo** [comment]
James, you can use this fix using the rc version of tns-core-modules, backup your project and change your references to tns-core-modules@rc.

**Comment by atchaiecommerce** [comment]
any updates on this one?

**Comment by james-criscuolo** [comment]
This was released in the latest 6.2 version, so today's 6.3 release probably has it as well.

**Pull request merged**
