### PR TITLE
white space

### PR DESCRIPTION
**Pull request by pedromorgan**
adding some ws as a python dev.preamble .  trying to solve https://github.com/NativeScript/NativeScript/issues/5622

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the new behavior?

Fixes/Implements/Closes #[Issue Number].

### CODE REVIEW

**Comment by pedromorgan** [comment]
lets make ns-bot recuss @ns-bot

**Comment by SvetoslavTsenov** [comment]
test

**Comment by vakrilov** [comment]
Hey @pedromorgan - can you sign the CLA at http://www.nativescript.org/cla

**Comment by vakrilov** [comment]
Hey @pedromorgan. We appreciate that you took the time to make the PR. However, we our policy forbids us form merging it before you sign the CLA at http://www.nativescript.org/cla

**Comment by vakrilov** [comment]
**Note**: You must sign the CLA with the e-mail used in your commits. As I see in your commit info [here](https://github.com/NativeScript/NativeScript/commit/83489766ed1c387d479d02b8d4a2608f5ed35c1e.patch) it is pedromorgan@users.noreply.github.com.

**Comment by vakrilov** [comment]
Closing due to inactivity.
@pedromorgan You can reopen this PR. Please make sure you rebase to master and sign the CLA before that.

**Pull request closed without merging**
