### PR TITLE
fix(android): image asset handling

### PR DESCRIPTION
**Pull request by triniwiz**
closes https://github.com/NativeScript/plugins/issues/124
closes https://github.com/NativeScript/NativeScript/issues/8203

### CODE REVIEW

**Comment by zghotlawala** [comment]
Is it handled for the Nativescript versions running 6x ?

**Comment by alexist** [comment]
Is it handled for the Nativescript versions running 7x ?

**Comment by NathanWalker** [comment]
Believe it or not you can bump:
```
@nativescript/core ~7.2.0, 7.1.0, 7.0.0, whatever
```
To:
```
@nativescript/core: ~8.0.0
```
And you're now using the latest. 
For {N} 6 users you probably want to install this plugin: https://github.com/NativeScript/eslint-plugin and run it against your project to update a majority of your old imports. There will be some left over to update manually but that would get you most way there.

For {N} 7 users, just bumping core is often enough (may be few small things but largely nothing). Give it a try.

**Comment by alexist** [comment]
Thanks, I have bump the version yesterday and confirm that it fix our issue. I though webpack 5 was mandatory, that's why i didn't upgraded.

**Comment by NathanWalker** [comment]
Good to hear thanks. We should publish a quick blog post on this - totally fine to use cli 8, runtimes 8 and core 8 with webpack 4 (totally fine)

**Pull request merged**
