### PR TITLE
iOS ActionBar will now display transparent colors and background images

### PR DESCRIPTION
**Pull request by PanayotCankov**

### CODE REVIEW

**Comment by PanayotCankov** [comment]
run ci

**Comment by enchev** [comment]
:+1:

**Comment by hshristov** [comment]
:+1:

**Comment by vakrilov** [comment]
:+1:

**Comment by PanayotCankov** [comment]
This needs some more piping, currently the ActionBar background is not updated on back navigation.

**Comment by PanayotCankov** [comment]
We will open the PR once we take care of all use cases.

**Pull request closed without merging**
