### PR TITLE
Revert "feat(animation): support animating width/height properties (W…

### PR DESCRIPTION
**Pull request by SvetoslavTsenov**
Reverting PR:  #4917 because of some glitches in animations:
IOS: 
In the example "layout-stack-height" appears white line during the animation
[demo_ios.mp4.zip](https://github.com/NativeScript/NativeScript/files/1534930/demo_ios.mp4.zip)

Android:
In the examples "animation-army-100" on each animation on the top left corner of the screen, appears a rectangle before the animation to be completed.

[demo.mp4.zip](https://github.com/NativeScript/NativeScript/files/1534911/demo.mp4.zip)

### CODE REVIEW

**Comment by justindujardin** [comment]
Did you skip the review? It kind of sucks, now I've got a reverted PR that could have been avoided. I'm pretty sure I commented on this stuff.

**Comment by vchimev** [comment]
A branch with the original changes has been created - [animate-width-height](https://github.com/NativeScript/NativeScript/commits/animate-width-height).

**Comment by vchimev** [comment]
@justindujardin,

We appreciate your contribution and definitely want it into our code base.

I am afraid that while being busy working on the next official release of NativeScript (version 3.4.0), we have not been able to devote the time and attention it deserves to your pull request.

Let me reopen it and share our suggestions there.

**Comment by justindujardin** [comment]
@vchimev @SvetoslavTsenov I totally understand, sorry for sounding critical. :+1:

**Pull request merged**
