### PR TITLE
API Level 14 Compatibility (replace android.view.View.generateViewId)

### PR DESCRIPTION
**Pull request by vbresults**
NativeScript/NativeScript#694

### CODE REVIEW

**Comment by dtopuzov** [comment]
run ci

**Comment by vchimev** [comment]
@vbresults,

there are typescript errors:
```
Using the custom compiler : node_modules/typescript/bin/tsc
--project tsconfig.json --outDir ./bin/dist --removeComments
tns-core-modules/ui/frame/frame.android.ts(300,37): error TS2304: Cannot find name 'com'.
tns-core-modules/ui/list-view/list-view.android.ts(55,35): error TS2304: Cannot find name 'com'.
tns-core-modules/ui/scroll-view/scroll-view.android.ts(89,35): error TS2304: Cannot find name 'com'.
tns-core-modules/ui/tab-view/tab-view.android.ts(213,35): error TS2304: Cannot find name 'com'.
```

**Comment by vbresults** [comment]
@vchimev `com.tns.View` is a reference to a native java class, so it wouldn't be declared.

**Comment by vbresults** [comment]
@vchimev All of the associated commits have been made so that this can work.  Again, see here: NativeScript/NativeScript#694

**Comment by vakrilov** [comment]
Closing this one as it is now outdated.
@vbresults - if you still want to work on that please reach out.

**Pull request closed without merging**
