### PR TITLE
Added a test for locks while writing and deleting a file

### PR DESCRIPTION
**Pull request by PanayotCankov**

### CODE REVIEW

**Comment by enchev** [comment]
:+1:

**Comment by vakrilov** [comment]
:+1:

**Comment by hshristov** [comment]
run ci

**Comment by hdeshev** [comment]
run ci

**Comment by hdeshev** [comment]
run ci

**Comment by hdeshev** [comment]
run ci

**Comment by ErjanGavalji** [comment]
run ci

**Comment by ErjanGavalji** [comment]
:+1:

**Pull request merged**
