### PR TITLE
Fix: background-repeat is not respected

### PR DESCRIPTION
**Pull request by hamorphis**
Related to #2318

### CODE REVIEW

**Comment by hamorphis** [comment]
uitestsapp

**Comment by hamorphis** [comment]
ui tests

**Comment by hamorphis** [comment]
uitests

**Comment by hamorphis** [comment]
cuteness

**Comment by hamorphis** [comment]
uitests

**Comment by hamorphis** [comment]
cuteness

**Comment by hamorphis** [comment]
cuteness

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
cuteness ios

**Comment by vchimev** [comment]
cuteness ios

**Pull request merged**
