### PR TITLE
fix(text-view): only reload text if hint is showing on ios

### PR DESCRIPTION
**Pull request by dosomder**
## PR Checklist

- [X] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [X] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [X] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
iOS TextView reloads text every time the TextView is focused

## What is the new behavior?
Only reload text if necessary (i.e. previously was the hint shown)

Fixes/Implements/Closes https://github.com/NativeScript/NativeScript/issues/8620

### CODE REVIEW

**Comment by dosomder** [comment]
@NathanWalker rebased on master to fix merge conflicts

**Comment by NathanWalker** [comment]
Thanks @dosomder

**Comment by dosomder** [comment]
@NathanWalker Do you know when this is planned to be merged / released?

**Comment by NathanWalker** [comment]
This will go out this week in a patch update 👍

**Comment by dosomder** [comment]
Looking forward to the release 👍

**Comment by NathanWalker** [comment]
Released with https://github.com/NativeScript/NativeScript/releases/tag/6.5.9 now

**Pull request merged**
