### PR TITLE
return press fixed

### PR DESCRIPTION
**Pull request by enchev**
Related to #713 and #1721

### CODE REVIEW

**Comment by enchev** [comment]
Hey @PeterStaev @Daxito,

Can you verify if this fix can work on your cases?

Thanks

**Comment by Daxito** [comment]
@enchev It now works for me, thank you!

**Comment by PeterStaev** [comment]
@enchev confirmed :+1:

**Comment by vakrilov** [comment]
:+1:

**Comment by Daxito** [comment]
Seems like this fix was not included in {N} 2.0! :-(
Is there a reason? I have to manually apply it every time I remove the android platform :-(

Thanks

**Comment by orsag** [comment]
It works correctly without this fix on 2.0. You don't have to apply it at all.

**Comment by Daxito** [comment]
@orsag You are right, I had to update tns-core-modules from 1.7.1 to 2.0, my bad.

**Pull request merged**
