### PR TITLE
Fixed #909: Android ListView will not update its UI after refresh is …

### LINKED ISSUE #909: Android ListView will not update its UI after refresh is called until it is scrolled up and down.
When bound to a simple array of simple items, the ListView does not update its UI after refresh is called.

### PR DESCRIPTION
**Pull request by hamorphis**
…called until it is scrolled up and down.

### CODE REVIEW

**Comment by hshristov** [comment]
:+1:

**Comment by hamorphis** [comment]
@arover  I am not missing else. If the data item is not observable I need to reset the binding context so it can be refreshed.

**Comment by hamorphis** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Pull request merged**
