### PR TITLE
fix(ios-tabview): crash when setting tab text color

### PR DESCRIPTION
**Pull request by MartoYankov**
fixes https://github.com/NativeScript/NativeScript/issues/7166

### CODE REVIEW

**Comment by MartoYankov** [comment]
Tried it, but there isn't an easy way to get the tab text color to verify it natively.

**Comment by MartoYankov** [comment]
test package_version#latest

**Comment by dtopuzov** [comment]
test package_version#latest branch#release

**Comment by MartoYankov** [comment]
test package_version#latest

**Comment by SvetoslavTsenov** [comment]
test package_version#latest

**Pull request merged**
