### PR TITLE
FPS module will now correctly count frames while scrolling in iOS

### PR DESCRIPTION
**Pull request by PanayotCankov**

### CODE REVIEW

**Comment by hshristov** [comment]
:100:

**Comment by atanasovg** [comment]
Excellent, @PanayotCankov! You solved the mystery :smile:

**Comment by PanayotCankov** [comment]
@fealebenpae pointed us in the right direction :smile:

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by vakrilov** [comment]
:+1:

**Pull request merged**
