### PR TITLE
Non-uniform borders

### LINKED ISSUE #859: Allow borders to be applied on a per-side basis in CSS
I'm finding that I frequently need to put a border on one side of a UI component, but NativeScript currently does not support this. I'm requesting that the following CSS properties be added:

* `border-top-width`
* `border-top-color`
* `border-right-width`
* `border-right-color`
* `border-bottom-width`
* `border-bottom-color`
* `border-left-width`
* `border-left-color`

To be consistent with CSS, I would also like the `border-width` and `border-color` shorthands to work like they do in CSS.

screen shot 2015-09-30 at 8 17 47 am

> Update: You can vote for this feature at https://nativescript.ideas.aha.io/ideas/NS-I-110.

Thanks.

### PR DESCRIPTION
**Pull request by hamorphis**
Resolves #859

Current limitations are:
 - Different border radii on the four corners are not yet supported
 - Border radius is supported only when the border width and color is uniform on all four sides.
 - Images on iOS will still render behind the border as they always have, until a fix is provided.

### CODE REVIEW

**Comment by hamorphis** [comment]
uitests

**Comment by hamorphis** [comment]
widgets

**Comment by hamorphis** [comment]
widgets

**Comment by vchimev** [comment]
uitests-widgets

**Comment by vchimev** [comment]
widgets-uitests-ios

**Comment by hamorphis** [comment]
uitests-widgets

**Comment by hamorphis** [comment]
widgets-uitests-ios

**Comment by hamorphis** [comment]
widgets-uitests-android

**Comment by hamorphis** [comment]
widgets-uitests-ios

**Comment by hamorphis** [comment]
widgets-uitests-android

**Comment by hamorphis** [comment]
tests

**Comment by hamorphis** [comment]
widgets-uitests-android

**Pull request merged**
