### PR TITLE
fix(hmr): support for multi module replacement

### PR DESCRIPTION
**Pull request by manoldonev**
Fixes: https://github.com/NativeScript/NativeScript/issues/7294

### CODE REVIEW

**Comment by manoldonev** [comment]
test tsapps ngapps nested_frame_navigation

**Comment by manoldonev** [comment]
test tsapps ngapps nested_frame_navigation

**Comment by dtopuzov** [comment]
test tsapps ngapps nested_frame_navigation

**Comment by manoldonev** [comment]
test tsapps ngapps nested_frame_navigation

**Comment by manoldonev** [comment]
test tsapps ngapps nested_frame_navigation

**Comment by manoldonev** [comment]
test tsapps ngapps nested_frame_navigation

**Pull request merged**
