### PR TITLE
fix: restore TextField.textChange and Switch.checkedChange event syntax in xml

### PR DESCRIPTION
**Pull request by NathanaelA**
## PR Checklist

-  [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [X] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [X] You have signed the [CLA](http://www.nativescript.org/cla).
- [X] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
`<TextField textChange="someFunc"/> `
`SomeFunc` does not fire.   When NativeScript was upgraded to v3.0.0 somehow when the renaming the events from `properyChange` to `textChange` on the text editable fields; this event was not properly declared.  This became a nasty breaking change for NS-Core apps, as there is then now no way to wire up the "change" events via xml anymore at all.    This really becomes problematic with repeaters and listviews (i.e. anything that has templates that can repeat)

## What is the **FIXED** behavior?
`<TextField textChange="someFunc"/> `
`someFunc` will now be wired up properly from the XML builder so that this event will properly fire.  This fixes the **regression** in NS 3.0 that has causes a lot of issues for those who are using NS Core for the last couple versions of NS.

Fixes/Implements/Closes #[Issue Number].
#5835, #3971 https://github.com/NativeScript/nativescript-angular/issues/79

I would really like to see this show up in v6.00 -- It was broke in 3.00 and we (ns-core) have limped along with some significantly **CRAPPY** work arounds -- its time to get it fixed...  ;-)  

Btw, I can also add `checkedChange` (i.e. `Switch` regressed) event to this PR or another if you prefer.  It is another item that's even was regressed in v3.0 of NS.

### CODE REVIEW

**Comment by NathanaelA** [comment]
Can we make sure we get some visibility on this so it doesn't get dropped.   
@manoldonev @vchimev @vakrilov @EmilStoychev 

I just ended up upgrading a second NS-Core 2.x app to NS 5 tonight and ran into this again.   However, this time the client needs to be able to build the app; which complicates this drastically as on the first app I can easily modify my own tns-core-modules -- and build it from that.    But for this second one I'd rather not be distributing a custom tns-core-modules just to fix a bug that you so simply can commit and have fixed for all future versions...   Please can we fix this!

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
@NathanaelA we'd really like to find a more general solution (probably in the builder module) but for the time being we decided to accept this change as I am not sure we'll be able to investigate this further within the NativeScript 6.0 release timeframe.

**Pull request merged**
