### PR TITLE
fix(connectivity): getActiveNetworkInfo and NetworkInfo modern compliance #8580

### PR DESCRIPTION
**Pull request by triniwiz**

### CODE REVIEW

**Comment by NathanWalker** [comment]
iOS changes lgtm - @NathanaelA can approve android changes.

**Comment by triniwiz** [comment]
Existing apps using the connectivity module will need to add the following to the `AndroidManifest.xml` which should be located in `app/App_Resources/Android/src/main/AndroidManifest.xml`
```xml
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
```

**Comment by farfromrefug** [comment]
If i may jump in. I think it would be best not to use the extend syntax (android NetworkCallback). But to use constructor implementation instead. Same behavior behind but in a sense it is more readable (typings) as not seen as class extension. Also it allows to pass object for which instance methods can be used as implementation. Means it prevents instantiating functions everytime. 
Finally you should use method shorthands for the methods definitions for NetworkCallback. Like  'onUnvailable:notifyCallback'

**Comment by farfromrefug** [comment]
@triniwiz as we discussed yesterday, `extend`is the best way to go as it could be the same syntax on iOS.
Rest the point about not creating funcs every time
And using `extend` it means you should store the newly created class for later use.

**Comment by NathanWalker** [comment]
Released with https://github.com/NativeScript/NativeScript/releases/tag/6.5.9 now

**Pull request merged**
