### PR TITLE
Note for deprecated module Border in HOW-TO.md

### PR DESCRIPTION
**Pull request by NickIliev**
related to [https://github.com/NativeScript/docs/issues/333](https://github.com/NativeScript/docs/issues/333)

### CODE REVIEW

**Comment by NathanaelA** [comment]
@NickIliev -- What CSS property (in NativeScript) do you use if all you want is a single line on say the bottom of a StackLayout; or what item do you use if you want a border only on one side of a Label?    To my knowledge NativeScript's CSS doesn't support borders on a single side.

**Comment by NickIliev** [comment]
@NathanaelA you are absolutely right.. will dismiss this PR than as the border module obviously still has its actual meaning.

**Comment by NathanaelA** [comment]
Rats, I was really hoping I was wrong and missed a brand new cool css borders calls...  :grinning:

**Comment by NickIliev** [comment]
For everyone who is interested in per-sed border applying, you can already do that with CSS styles.
e.g.

```
..btn {
    border-width: 5 10 15 20;
    border-color: red;
}
```

**Pull request closed without merging**
