### PR TITLE
ref(android): Cleanup and optimization for scroll view classes

### LINKED ISSUE #10200: [Android][NS 8.4] Exception thrown when restoring state for ScrollView
### Issue Description

When an app which contains a Vertical ScrollView has it's state restored, (e.g. after it has been sent to the background and then brought forward, and the os has decided to remove the activity from memory.) the following exception will be thrown:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.scrollViewCrash/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
Error: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: androidx.core.widget.NestedScrollView$SavedState
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Reproduction

1. create a plain ns typescript app
2. add a scrollView 
3. Enable in Developer settings on the phone "Don't Keep activities, Destroy every activity as soon as the user leaves it" 
4. run app , send to background
5. bring app to forground
6. Error will be shown.

### Relevant log output (if applicable)

_No response_

### Environment

_No response_

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

### PR DESCRIPTION
**Pull request by CatchABus**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/DevelopmentWorkflow.md#running-unit-tests-application.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/tools/notes/WritingUnitTests.md.

## What is the current behavior?
NativeScript scroll views are currently inheriting android `NestedScrollView` and `HorizontalScrollView` classes. This results in NativeScript horizontal and vertical scrollviews containing features that are already implemented by those classes mentioned above.

In addition, scroll view saved state has stopped working because of conflict problems. See #10200

## What is the new behavior?
This patch gets rid of obsolete code and fixes open issue at the same time.
On top of that, scroll view classes will now call superclass `onLayout` which handles saved state restoration too.

@farfromrefug Your opinion is very important on this one.

Fixes/Closes #10200.

### CODE REVIEW

**Comment by farfromrefug** [comment]
@CatchABus I really like those changes. Looks much cleaner and efficient (all relying on NestedScrollView original behavior).
And personally I am ok with the breaking Change. Thanks for this !

**Comment by CatchABus** [comment]
> @CatchABus I really like those changes. Looks much cleaner and efficient (all relying on NestedScrollView original behavior). And personally I am ok with the breaking Change. Thanks for this !

Thank you very much! I've marked it as draft for now because iOS has center alignment as default so I'll look more into this.
I've managed to alter gravity defaults but centering needs improvements.

**Comment by farfromrefug** [comment]
@CatchABus and we can't have the child of the scrollview default android alignment set to center? That way it would not be a breaking change

**Comment by CatchABus** [comment]
@farfromrefug I did a bit of work about that here: https://github.com/NativeScript/NativeScript/pull/10202/commits/462b993813f49dbc3960e9a74d97978fb22b8da8

It uses the gravity defaults we already had and applies result to scroll views until built-in layout is completed. In cases where scrollview nested layout has a fixed height but its children overlap, center alignment has still got different results but I think old behaviour was also different than that of iOS.

I believe this PR needs testing with more scenarios. Also, we should consider if it was less of a trouble to keep copies of those classes like we did before.
Feel free to post results or perform any changes that you see fit.

**Comment by jcassidyav** [comment]
@CatchABus This looks great, but I am a little confused, does it contain a breaking change ?   I do see differences in vertical alignment. ( Centering Vertically)

**Comment by CatchABus** [comment]
@jcassidyav I committed 2 fixes, one of which solves the problem you described.
Let me know if you see any other strange issue.

New changes have caused one of `HorizontalScrollView` tests to break so I'm still investigating a few things.

**Comment by jcassidyav** [comment]
@CatchABus Another odd one, when a scroll view is used inside a @nativescript-community/ui-material-tabs , it no longer scrolls.  No errors it just won't respond to a touch to scroll it.

e.g. https://stackblitz.com/edit/nativescript-stackblitz-templates-dgf6vd?file=app/main-page.xml

**Comment by CatchABus** [comment]
@farfromrefug @jcassidyav I close this in favor of #10213 . Layout rework gave me trouble because of how it currently works in {N} so I focused solely on exception fix.
We could retry this sometime in the future.

**Pull request closed without merging**
