### PR TITLE
fix(ios): preferredDatePickerStyle

### PR DESCRIPTION
**Pull request by asharghi**
Backport of #8899

### CODE REVIEW

**Review by NathanWalker — APPROVED** [review]
Awesome @asharghi thank you!

**Comment by NathanWalker** [comment]
When you commit are you using command line with force or some other tool? There's a precommit hook which auto formats but looks like your push is going around the formatting? (The ci build just mentions some formatting)

**Comment by asharghi** [comment]
Hmm.. I'm just using vscode with a git extension. 
vscode

**Comment by NathanWalker** [comment]
Ok thanks I'll have to look into why that is going around the precommit hooks. 🤔

**Comment by farfromrefug** [comment]
Maybe it would be good to add an enum for this? Like it is done everywhere else

**Comment by asharghi** [comment]
Agree @farfromrefug. Feel free to take over

**Comment by blurp1478963** [comment]
Hi!
I still have trouble with the datePicker in iOS 14, since last apple update...

Here's the error from Xcode console:

```
CONSOLE LOG file:///app/vendor.js:1:3022513: DatePickerField Error: Error: -[_UIDatePickerIOSCompactView setHighlightsToday:]: unrecognized selector sent to instance 0x7fe9caf5a0b0
```

Error appends on click on picker (and selector doesn't open)

```html
          <DatePickerField
            required
            formControlName="dateOfIssue"
            hint="date"
            class="-border m-0"
          ></DatePickerField>
```

Any idea? I upgraded to 6.5.20 for core modules, clean all, rebuild dozen times...

Thanks by advance!

**Comment by asharghi** [comment]
Hi @blurp1478963 . This PR fixes the NativeScript ui elements for `<DatePicker />` and `<TimePicker />`. Looks like you are using `<DatePickerField />` which is a plugin, `nativescript-datetimepicker`. You should create a issue over there: https://github.com/NativeScript/nativescript-datetimepicker

**Pull request merged**
