### PR TITLE
Integrate recent iOS Runtime global.__onUncaughtError feature

### PR DESCRIPTION
**Pull request by atanasovg**
https://github.com/NativeScript/ios-runtime/issues/78

### CODE REVIEW

**Comment by enchev** [comment]
:+1:

**Comment by dtopuzov** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by dtopuzov** [comment]
:+1:

**Pull request merged**
