### PR TITLE
test(safe-area): fix ios 12 landscape tests

### PR DESCRIPTION
**Pull request by MartoYankov**
* Add longer text for `WrapLayout` tests, so that the setup is the same in landscape
* Add wait until actual ios modal is closed. This should be a temp fix for unit tests.
* Add `greaterOrCloseEnough` assert method similar to `lessOrCloseEnough`, so that landscape cases are covered.

### CODE REVIEW

**Comment by MartoYankov** [comment]
test --ignore ios12

**Comment by SvetoslavTsenov** [comment]
test --ignore ios12

**Comment by SvetoslavTsenov** [comment]
test --ignore ios12 tns_core_modules_unit_tests ios11

**Comment by SvetoslavTsenov** [comment]
build_tns_core_modules_unit_tests
test --ignore ios12 tns_core_modules_unit_tests  build_tns_core_modules_unit_tests ios11

**Comment by SvetoslavTsenov** [comment]
test --ignore ios12 tns_core_modules_unit_tests build_tns_core_modules_unit_tests ios11

**Comment by SvetoslavTsenov** [comment]
test --ignore ios12 ios11

**Comment by MartoYankov** [comment]
test ios12

**Comment by SvetoslavTsenov** [comment]
test --ignore ios12 tns_core_modules_unit_tests xcode10

**Pull request merged**
