### PR TITLE
Android: ActionBar transparent background crashes

### LINKED ISSUE #3565: ActionBar transparent background crahses on android  with NS 2.5.0
_From @ullalaaron on February 2, 2017 15:24_

Setting 
```
ActionBar{
         background-color : transparent;
}
```
makes the Android app crash.

_Copied from original issue: NativeScript/nativescript-cli#2479_

### PR DESCRIPTION
**Pull request by vakrilov**
Resolves #3565

### CODE REVIEW

**Comment by vakrilov** [comment]
run ci

**Comment by vakrilov** [comment]
uitests

**Comment by vakrilov** [comment]
runci

**Comment by vakrilov** [comment]
build

**Comment by vakrilov** [comment]
build

**Comment by vchimev** [comment]
build

**Pull request merged**
