### PR TITLE
refactor: update e2e tests for CI

### PR DESCRIPTION
**Pull request by manoldonev**

### CODE REVIEW

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation_android#mdonev/e2e-nested-frames-anim api23

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation_android#mdonev/e2e-nested-frames-anim api23 tsapps_android

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-nested-frames-anim api23

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-nested-frames-anim api23

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-nested-frames-anim api23 iosx

**Comment by SvetoslavTsenov** [comment]
test --ignore nested_frame_navigation_ios#mdonev/e2e-nested-frames-anim nested_frame_navigation_ios12

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-nested-frames-anim nested_frame_navigation_api23 nested_frame_navigation_ios12

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-nested-frames-anim nested_frame_navigation_api23 nested_frame_navigation_ios12

**Comment by manoldonev** [comment]
test --ignore nested_frame_navigation#mdonev/e2e-nested-frames-anim nested_frame_navigation_api23 nested_frame_navigation_ios12

**Pull request merged**
