### PR TITLE
Implement non uniform border corner radiuses and fix blinking image-view radiuses

### PR DESCRIPTION
**Pull request by PanayotCankov**

### CODE REVIEW

**Comment by PanayotCankov** [comment]
ui tests

**Comment by PanayotCankov** [comment]
ui test

**Comment by PanayotCankov** [comment]
ui-test

**Comment by PanayotCankov** [comment]
ui-tests

**Comment by vchimev** [comment]
widgets-uitests-android

**Comment by PanayotCankov** [comment]
uitests

**Comment by vchimev** [comment]
widgets-uitests-android

**Comment by vchimev** [comment]
widgets

**Comment by vchimev** [comment]
ci/jenkins/widgets (unit tests) are good
ci/jenkins/widgets-uitests-android: 
http://nsbuild01.telerik.com/build/job/tns-modules-widgets-PR-uitests-android/22/artifact/functional-tests/target/surefire-reports/html/index.html

**Comment by PanayotCankov** [comment]
uitests

**Comment by PanayotCankov** [comment]
widgets-uitests-android

**Comment by PanayotCankov** [comment]
widgets-uitests-android

**Comment by PanayotCankov** [comment]
widgets

**Comment by SvetoslavTsenov** [comment]
https://github.com/NativeScript/NativeScript/issues/4521

**Comment by PanayotCankov** [comment]
widgets-uitests-android

**Comment by SvetoslavTsenov** [comment]
widgets-uitests-android

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
uitests

**Comment by PanayotCankov** [comment]
widgets-uitests-android

**Comment by PanayotCankov** [comment]
uitests

**Comment by SvetoslavTsenov** [comment]
uitests

**Comment by SvetoslavTsenov** [comment]
widgets

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
widgets-uitests-android

**Comment by SvetoslavTsenov** [comment]
Hey @PanayotCankov 
It seems that the fix is fine.
I need to know what do you think about these two images for iOS
http://nsbuild01.telerik.com/build/job/tns-modules-PR-uitests-ios/325/artifact/functional-tests/target/surefire-reports/screenshots/button_border_08_actual.png
http://nsbuild01.telerik.com/build/job/tns-modules-PR-uitests-ios/325/artifact/functional-tests/target/surefire-reports/screenshots/button_border_08_expected.png

As far as for android the tests look fine
http://nsbuild01.telerik.com:8080/build/view/PR/job/tns-modules-widgets-PR-uitests-android/46/artifact/functional-tests/target/surefire-reports/html/index.html

**Comment by SvetoslavTsenov** [comment]
cuteness

**Comment by SvetoslavTsenov** [comment]
cuteness ios

**Comment by SvetoslavTsenov** [comment]
cuteness android

**Comment by SvetoslavTsenov** [comment]
animations

**Pull request merged**
