### PR TITLE
Fixed multiple gestures for Android

### LINKED ISSUE #654: Multiple gestures not working for Android
```XML
<Page>
  <Label text="Label" loaded="loaded"/>
</Page>
```

```JavaScript
var gestures = require("ui/gestures");
function loaded(args) {
    var lbl = args.object;
    lbl.observe(gestures.GestureTypes.tap | gestures.GestureTypes.doubleTap | gestures.GestureTypes.longPress, function (args) {
        console.log("Args: " + args);
    });
}
exports.loaded = loaded;

```

### PR DESCRIPTION
**Pull request by enchev**
Fixed #654.

### CODE REVIEW

**Comment by nsndeck** [comment]
:+1:

**Comment by vchimev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by vakrilov** [comment]
:+1:

**Pull request merged**
