### PR TITLE
Extracted view-related utility methods from "utils/utils" to "ui/util…

### PR DESCRIPTION
**Pull request by hamorphis**
…s" so that the "utils/utils" module does not depend on the view module.

### CODE REVIEW

**Comment by enchev** [comment]
:+1:

**Comment by hdeshev** [comment]
:+1:

**Comment by hshristov** [comment]
If this is going to be iOS specific module then you don't need ```.d.ts.``` file.
And you can call it iosUtils to make it clear that it contains iOS specific code only.

**Comment by hamorphis** [comment]
run ci

**Pull request merged**
