### PR TITLE
fix: bundle entry points

### PR DESCRIPTION
**Pull request by farfromrefug**
As requested here is the PR again which fixes

This PR fixes a big issue which appeared with N 7 / esm / webpack

With webpack import / require order is not respected : https://github.com/webpack/webpack/issues/1343

Now in [bundle-config-loader](https://github.com/Nativescript/NativeScript/blob/65a3302a048fb32da78968256c16fc63a5706e3d/packages/webpack/bundle-config-loader.ts#L55) we rely on `require` to load `bundle-entry-points` thus calling `initGlobals` and making tslib functions global.
Because it uses `require` it actually end up at the end of your `main.js` (simply look at a generated bundle.js)

To keep that call up we need to use `import` 
But that is not enough!
in `bundle-entry-points` we use 'require' on 'globals'. And using `import` is not enough either because we call a method on it which will end up after all imports!

The solution to all this is call `initGlobal` inside `global/index.ts` then use `import './global'` for example.
Doing that i needed cleanup a bit and we end up with only on use of `initGlobal`

EDIT: that [app](https://github.com/nativescript-community/gesturehandler/tree/master/demo_vue) will crash on ios because of that. The reason is that i import View at the top of my main.ts which include files using `__metadata`

### CODE REVIEW

**Comment by NathanWalker** [comment]
I think we did some tests with import vs. require and were seeing exactly what is commented on that thread here:
https://github.com/webpack/webpack/issues/1343#issuecomment-523076943

Where using require as opposed to import seemed to be guarantee.

**Comment by farfromrefug** [comment]
Imports will all get at the top you are right. Which is why I changed the way initGlobals is called to ensure the right order. 
In bundle config loader using require makes it end up last. Look at the generated code for a current app to see it.

**Comment by farfromrefug** [comment]
After that test with that code and you ll see the order being correct.

**Comment by rigor789** [comment]
LGTM - I'll just run a test and include a diff here with the before/after behavior.

**Review by rigor789 — APPROVED** [review]

**Comment by NathanWalker** [comment]
Awesome thanks @farfromrefug and @rigor789 👍

**Comment by NathanWalker** [comment]
Released with 7.0.5 https://github.com/NativeScript/NativeScript/releases/tag/7.0.5-core

**Comment by asharghi** [comment]
Possible to get this fix for NS 6 also?

**Comment by farfromrefug** [comment]
@NathanWalker i think it needs a webpack release too. https://github.com/NativeScript/NativeScript/issues/8778

**Pull request merged**
