### PR TITLE
fix(6913): set/unset touchListener.owner onLoaded/onUnloaded

### LINKED ISSUE #6913: Is there a memory problem with the owner references on android?
I'm researching a memory leak we have with `nativescript-angular` (https://github.com/NativeScript/nativescript-angular/issues/1738) and I noticed a few things in `NativeScript Core`.

Why is the `owner` references on Android not a `WeakRef` like it is on `iOS`?

For instance if you look at the `TouchListener` added here:
https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/core/view/view.android.ts#L416
This `owner` reference is not cleared when the `View` is destroyed, so there is circular reference between the `touchListener` and `owner` view.
On iOS the owner property would have been a `WeakRef` and there wouldn't have been a problem.

In my test project (https://github.com/NativeScript/nativescript-angular/issues/1738#issuecomment-464471438) this results in many leftover `Label` objects: 
image

The screenshot is after forcing 100 redraws of a `ListView` with ~22 items, resulting in ~2200 `Label` objects.

I could submit a PR fixing this for the `touchListener` so the owner reference is cleared, but before that I'd like to understand why android views don't use a `WeakRef` to the owner like the `iOS` views do?

### PR DESCRIPTION
**Pull request by m-abs**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?

The `TouchListener` added to `View` on android have a owner-reference that is never cleared like it is on other native classes like the `clickListener` in `button.android.ts`.
So the `TouchListener` and `View` will keep pointing to each other as seen in #6913.

## What is the new behavior?

Like on `clickListener` in `button.android.ts` `owner` is bound to the `touchListener` when `onLoaded` is called and removed again when `onUnloaded` is called.

Fixes #6913

### CODE REVIEW

**Comment by m-abs** [comment]
The one of the existing tests failed with:

```bash
JS: Test: --- [UTILS.test_releaseNativeObject_canBeCalledWithNativeObject] FAILED: __releaseNativeCounterpart is not defined, Stack: ReferenceError: __releaseNativeCounterpart is not defined
```
I don't think I caused it, but cannot check the "All existing tests are passing:"-box.

**Comment by m-abs** [comment]
Hi @vakrilov 

That was something I wondered when I reported the issue.

On iOS `tns-core-modules` using a `WeakRef` for the `owner` reference, but most cases I've seen for Android don't use a `WeakRef` for the same (like here: https://github.com/NativeScript/NativeScript/blob/23147aecf338bbebbfb655c29e62833c72d247a8/tns-core-modules/ui/action-bar/action-bar.android.ts#L145).


That was why I choose not to use one.

**Comment by vakrilov** [comment]
test

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
test

**Pull request merged**
