### PR TITLE
added simple showModal() overload

### PR DESCRIPTION
**Pull request by enchev**
Now you can do:
```JavaScript
        var p = new Page();
        var ai = new ActivityIndicator();
        ai.busy = true
        p.content = ai;
        p.showModal();
        
        setTimeout(function () { p.closeModal(); }, 1000);
```

### CODE REVIEW

**Comment by hamorphis** [comment]
:+1:

**Comment by vakrilov** [comment]
:+1:

**Comment by alexrainman** [comment]
I still thinking this need to be added to Dialogs module including some parameters to set the overlay mode opacity. Anyway, i wish you make it work this way :)

**Comment by alexrainman** [comment]
This loading wheel will be available from view-model?

**Pull request merged**
