### PR TITLE
feat: testID property for use with e2e testing without interfering with a11y

### PR DESCRIPTION
**Pull request by NathanWalker**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/DevelopmentWorkflow.md#running-unit-tests-application.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/tools/notes/WritingUnitTests.md.

## What is the current behavior?

Using `automationText` for e2e testing interferes with a11y.

## What is the new behavior?

Adds a new `testID` property matching what the [React Native community adopted](https://reactnativetesting.io/component/testing.html#testing-text), also [reference api here](https://reactnative.dev/docs/view#testid) which helps discern e2e testing id's apart from anything specific to a11y.

* [x] confirm when set if it should modify any other behavior to achieve what's needed for clear e2e testing

### CODE REVIEW

**Comment by rigor789** [comment]
Marked as WIP - still need to do a cleanup pass and run a few more tests with both appium and detox.

**Comment by farfromrefug** [comment]
@NathanWalker seems quite good to me.
One question i have is are we sure this:
```
if (typeof __USE_TEST_ID__ !== 'undefined' && __USE_TEST_ID__ && this.testID) {
...
}
```
is removed if `__USE_TEST_ID__` is not defined and is transformed to `if (this.testID) {..}` if set ?

It is worth testing  to ensure the code is removed completely

**Comment by rigor789** [comment]
@farfromrefug I'll be checking that - just got a detox demo set up, still need an appium one to check all cases - and then clean up anything that can be cleaned up...

If that doesn't get tree-shaken, I'll just drop the typeof check - since we'll be setting it in webpack by default to false (unless `--env.e2e`).

**Comment by rigor789** [comment]
@farfromrefug seems to be tree-shaken away just fine!

```js
// default

    [_view_common__WEBPACK_IMPORTED_MODULE_0__.testIDProperty.setNative](value) {
        this.setTestID(this.nativeViewProtected, value);
    }
    setTestID(view, value) {
        if (false) {}
    }
```

```js
// with --env.e2e

    [_view_common__WEBPACK_IMPORTED_MODULE_0__.testIDProperty.setNative](value) {
        this.setTestID(this.nativeViewProtected, value);
    }
    setTestID(view, value) {
        if (true) {
            const id = _utils__WEBPACK_IMPORTED_MODULE_11__.ad.resources.getId(':id/nativescript_accessibility_id');
            if (id) {
                view.setTag(id, value);
                view.setTag(value);
            }
            view.setContentDescription(value);
        }
    }
```

**Comment by farfromrefug** [comment]
@rigor789 very good! very good to know we write something like this 😃

**Review by rigor789 — APPROVED** [review]

**Pull request merged**
