### PR TITLE
perf(android): gridlayout with less JNI calls 

### PR DESCRIPTION
**Pull request by farfromrefug**
A rewrite of `GridLayout` on Android to makes less JNI calls. The result is around 30% time gained on average `GridLayout`

### CODE REVIEW

**Comment by NathanWalker** [comment]
@farfromrefug possible to peek at the failing android tests? I merged latest and also rebuild the ui-mobile-base widgets (aka, TNSWidgets) since this has a .java change on it) and seems we have the following failing tests with these changes:
```
 Test: GRIDLAYOUT.test_removeColumns FAILED: Cannot convert number to Lorg/nativescript/widgets/GridUnitType; at index 1
 Test: GRIDLAYOUT.test_removeRows FAILED: Cannot convert number to Lorg/nativescript/widgets/GridUnitType; at index 1
 Test: GRIDLAYOUT.test_removeChildren FAILED: Cannot convert number to Lorg/nativescript/widgets/GridUnitType; at index 1
 Test: GRIDLAYOUT.test_measuredWidth_when_not_stretched_two_columns FAILED: Cannot convert number to Lorg/nativescript/widgets/GridUnitType; at index 1
 Test: GRIDLAYOUT.test_measuredWidth_when_not_stretched_three_columns FAILED: Cannot convert number to Lorg/nativescript/widgets/GridUnitType; at index 1
 Test: GRIDLAYOUT.test_desiredSize_isCorrect FAILED: Cannot convert number to Lorg/nativescript/widgets/GridUnitType; at index 1
 Test: GRIDLAYOUT.test_columnsActualWidth_isCorrect FAILED: Cannot convert number to Lorg/nativescript/widgets/GridUnitType; at index 1
 Test: GRIDLAYOUT.test_rowsActualHeight_isCorrect FAILED: Cannot convert number to Lorg/nativescript/widgets/GridUnitType; at index 1
 Test: GRIDLAYOUT.test_Measure_and_Layout_Children_withCorrect_size FAILED: Cannot convert number to Lorg/nativescript/widgets/GridUnitType; at index 1
 Test: GRIDLAYOUT.test_ColumnWidth_when_4stars_and_width_110 FAILED: Cannot convert number to Lorg/nativescript/widgets/GridUnitType; at index 1
 Test: GRIDLAYOUT.test_columns_widths FAILED: Cannot convert number to Lorg/nativescript/widgets/GridUnitType; at index 1
```
Link to test run here: https://github.com/NativeScript/NativeScript/actions/runs/9719521521/job/26829475734?pr=10402

**Comment by farfromrefug** [comment]
@NathanWalker will take a look

**Comment by farfromrefug** [comment]
@NathanWalker i did fix some tests. now i am facing a dilemma. Some tests like this one  https://github.com/Akylas/NativeScript/blob/b9d5ba1c53987a7bbc3a8430b327c96dac03eb8c/apps/automated/src/ui/layouts/grid-layout-tests.ts#L372 are still failing. The reason is that before my PR on the JS side _cols and _rows were actually native objects  modified from the native side (`org.nativescript.widgets.ItemSpec`). Then on those native objects `_actualLength` to assert the tests.
But that only existed for the tests and makes GridLayout slower as we maintain and access native objects from the JS side. So i dont think we should keep on doing it that way.
I can create special methods in the android GridLayout to query that `_actualLength` for the purpose of the tests. However it means the tests will be different on iOS / Android. IS that ok?

**Comment by NathanWalker** [comment]
Thanks for explaining, I think that’d be okay 👍

**Comment by farfromrefug** [comment]
@NathanWalker should be good now

**Review by NathanWalker — APPROVED** [review]

**Pull request merged**
