### PR TITLE
feat: implement capitalization type option for prompt dialogs

### PR DESCRIPTION
**Pull request by hettiger**
Allow setting auto capitalization to "none", "all", "sentences" and "words".
This feature works on both Android and iOS.
Closes: #6326 

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests. → __Some tests are failing, but these are failing on the master branch as well and don't seem to be connected to my changes in any way. (See the "Test Results" section.)__
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?

Prompt dialogs do not support auto capitalization.
This leads to a bad user experience and bad input.

## What is the new behavior?

It's now possible to set a capitalization type on the PromptOptions object.

__Example:__

```ts
const options: PromptOptions = {
    title: "Title",
    message: "Message",
    inputType: inputType.text,
    okButtonText: "OK",
    cancelButtonText: "Cancel",
    cancelable: true,
    capitalizationType: capitalizationType.sentences
};
```

(The new property is: `capitalizationType: capitalizationType.sentences`)

There are no breaking changes to be expected.
The new property is optional.

### iOS

```txt
=== ALL TESTS COMPLETE ===
1612 OK, 6 failed
DURATION: 28714.39 ms
=== END OF TESTS ===
CONSOLE ERROR file:///app/tns_modules/tns-core-modules/trace/trace.js:166:30: Test: FLEXBOXLAYOUT.testJustifyContent_flexEnd_withParentPadding FAILED:  Actual: <654>(number). Expected: <686>(number)
CONSOLE ERROR file:///app/tns_modules/tns-core-modules/trace/trace.js:166:30: Test: SAFEAREALAYOUT.test_grid_component_cells_layout_in_safe_area_action_bar_hidden FAILED: cell height should be equal - cell11<432> - cell21<431> Actual: <432>(number). Expected: <431>(number)
CONSOLE ERROR file:///app/tns_modules/tns-core-modules/trace/trace.js:166:30: Test: SAFEAREALAYOUT.test_grid_component_cells_layout_in_safe_area_tab_bar FAILED: cell height should be equal - cell11<398> - cell21<399> Actual: <398>(number). Expected: <399>(number)
CONSOLE ERROR file:///app/tns_modules/tns-core-modules/trace/trace.js:166:30: Test: SAFEAREALAYOUT.test_grid_nested_grid_cells_layout_beyond_safe_area_action_bar_hidden FAILED: cell11 height<432> not less or equal cell21 height<431>
CONSOLE ERROR file:///app/tns_modules/tns-core-modules/trace/trace.js:166:30: Test: SAFEAREA-LISTVIEW.test_grid_nested_list_views_layout_in_safe_area_action_bar_hidden FAILED: cell11 height<432> not less or equal cell21 height<431>
CONSOLE ERROR file:///app/tns_modules/tns-core-modules/trace/trace.js:166:30: Test: SAFEAREA-SCROLL-VIEW.test_grid_component_cells_layout_in_safe_area_action_bar_hidden FAILED: cell11 height<432> not less or equal cell21 height<431>
CONSOLE INFO file:///app/tns_modules/tns-core-modules/trace/trace.js:160:29: Test: Tests EOF!
```

### Android

```
JS: === ALL TESTS COMPLETE ===
JS: 1489 OK, 2 failed
JS: DURATION: 47099.06 ms
JS: === END OF TESTS ===
JS: Test: FLEXBOXLAYOUT.testAlignContent_spaceAround FAILED: Label<text3>.bottom:1368 is not 52.5 of FlexboxLayout<flexbox>.bottom:1422
JS: Test: FLEXBOXLAYOUT.testAlignContent_spaceAround_flexDirection_column FAILED: Label<text3>.right:906 is not 52.5 of FlexboxLayout<flexbox>.right:960
JS: Test: Tests EOF!
```

### CODE REVIEW

**Comment by hettiger** [comment]
I'm not familiar with NativeScript e2e testing. Am I expected to provide tests or does the label »e2e test needed« mean that someone of the NativeScript team will take care of it?

I'd be happy to provide the tests myself but I'll probably need some help / reviews and input to get me started on NativeScript e2e testing.

- I guess I have to create a new directory `/e2e/prompt-capitalization-types` for my tests
- Within the directory I follow this guide: https://docs.nativescript.org/plugins/ui-tests

Am I on the right track? Is there anything special about this repository that differs from the [guide](https://docs.nativescript.org/plugins/ui-tests)?
Are there any additional docs to get me started that I've missed?

Please let me know how we can continue with this PR @vakrilov

**Comment by vakrilov** [comment]
Hey @hettiger 
First of all - thanks for the awesome PR! 
The few failing test are not caused by your code, so don't worry about them.

You are not expected to provide and e2e test about this PR (the `e2e test needed` label is for internal use for now). It would be great if you could extend the [existing test page for dialogs](https://github.com/NativeScript/NativeScript/tree/master/apps/app/ui-tests-app/dialogs) with buttons showing a dialogs with the new capitalization options. Our QAs will just add the e2e tests using this page once the PR is merged. Once that is ready - I think this one is ready to land in master.

**Comment by hettiger** [comment]
Thank you for your feedback @vakrilov 

- I've added the requested buttons to the existing test page.
- The test results remain the same after the new commit.

Let me know if there's anything missing.

**Comment by vakrilov** [comment]
LGTM!
We are waiting merge some PRs that should fix the broken tests. 
We will update you branch after that and hopefully everything should be green.
Nothing to do from your side for now.

**Comment by vakrilov** [comment]
test

**Comment by vakrilov** [comment]
test

**Comment by radeva** [comment]
Hi @hettiger ,

Congratulations on being one of the winners in the {N} First-time contributors contest! 

You can claim your prize by contacting us at nativescriptwinners[at]progress.com not later than Nov 30th 2018 . Make sure you send us the following info: 
👉Your full name 
👉Your email 
👉Your country or residence 

Best regards,
The NativeScript Team

**Pull request merged**
