### PR TITLE
CSS support for styling status bar

### PR DESCRIPTION
**Pull request by zh-m**
Page exposes two properties:
 - statusBarStyle - it can be 'dark' or 'light' - dark background with light letters and vice versus. 
 - androidStatusBarBackground - only for Android since the background color of the status bar in ios cannot be modified.

### CODE REVIEW

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Pull request merged**
