### PR TITLE
gestures now can be added with on() and removed with off()

### PR DESCRIPTION
**Pull request by enchev**
Now you can do:

```XML
<Page loaded="pageLoaded">
  <StackLayout>
  </StackLayout>
</Page>
```

```TypeScript
import observable = require("data/observable");
import view = require("ui/core/view");
import gestures = require("ui/gestures");
import label = require("ui/label");
import button = require("ui/button");
import pages = require("ui/page");
import stackLayout = require("ui/layouts/stack-layout");

export function pageLoaded(args: observable.EventData) {
    var page = <pages.Page>args.object;
    var stack = <stackLayout.StackLayout>page.content;

    var lbl1 = new label.Label();
    lbl1.text = "Label1";
    // Add single gesture
    lbl1.on(gestures.GestureTypes.tap, (args: gestures.GestureEventData) => {
        console.log("Event: " + args.eventName + ", sender: " + args.object);
    });
    stack.addChild(lbl1);

    var lbl2 = new label.Label();
    lbl2.text = "Label2";
    // Add multiple gestures
    lbl2.on(gestures.GestureTypes.tap | gestures.GestureTypes.doubleTap | gestures.GestureTypes.longPress, (args: gestures.GestureEventData) => {
        console.log("Event: " + args.eventName + ", sender: " + args.object);
    });
    stack.addChild(lbl2);

    var lbl3 = new label.Label();
    lbl3.text = "Label3";
    // Add single gesture as string
    lbl3.on("tap", (args: gestures.GestureEventData) => {
        console.log("Event: " + args.eventName + ", sender: " + args.object);
    });
    stack.addChild(lbl3);

    var lbl4 = new label.Label();
    lbl4.text = "Label4";
    // Add multiple gestures as comma separated strings
    lbl4.on("tap, doubleTap, longPress", (args: gestures.GestureEventData) => {
        console.log("Event: " + args.eventName + ", sender: " + args.object);
    });
    stack.addChild(lbl4);

    var lbl5 = new label.Label();
    lbl5.text = "Label5";
    // Add normal event
    lbl5.on("loaded", (args: observable.EventData) => {
        console.log("Event: " + args.eventName + ", sender: " + args.object);
    });
    stack.addChild(lbl5);

    var lbl6 = new label.Label();
    lbl6.text = "Label6";
    // Add normal event and gesture as comma separated strings
    lbl6.on("loaded, tap", (args: observable.EventData) => {
        console.log("Event: " + args.eventName + ", sender: " + args.object);
    });
    stack.addChild(lbl6);

    var btn1 = new button.Button();
    btn1.text = "Button1";
    // Add normal events as comma separated strings
    btn1.on("loaded, tap", (args: observable.EventData) => {
        console.log("Event: " + args.eventName + ", sender: " + args.object);
    });
    stack.addChild(btn1);
}
```

### CODE REVIEW

**Comment by enchev** [comment]
Implemented https://github.com/NativeScript/NativeScript/issues/615

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by nsndeck** [comment]
:+1:

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by hdeshev** [comment]
:+1: :grinning:

**Comment by dtopuzov** [comment]
run ci

**Comment by ligaz** [comment]
Are we going to `@deprecate` the `observe` method or it still has its purpose?

**Pull request merged**
