### PR TITLE
TS fail on type errors

### PR DESCRIPTION
**Pull request by PanayotCankov**

### CODE REVIEW

**Comment by hshristov** [comment]
:+1:

**Comment by PanayotCankov** [comment]
run ci

**Comment by hdeshev** [comment]
Why not add the option to the tsconfig.json?

**Comment by hdeshev** [comment]
:+1: for that option

**Comment by PanayotCankov** [comment]
I think this is an option of the `grunt-ts` and not the `tsc` itself. The `tsconfig.json` allready has `noEmitOnError: true`.

[There is some more information on that matter here.](https://github.com/TypeStrong/grunt-ts#failontypeerrors)

**Comment by PanayotCankov** [comment]
run ci

**Comment by PanayotCankov** [comment]
run ci

**Pull request merged**
