### PR TITLE
Improve ImageAsset scaling

### PR DESCRIPTION
**Pull request by DimitarTachev**
- don’t respect screen size while scaling
- [Android only] calculate natively following the files flow when used in ImageView

> The native handling of images is improved [here](https://github.com/NativeScript/tns-core-modules-widgets/pull/109) and this version of the Image should use the updated widgets one.

Fixing issue #3955 and [camera plugin issue #26](https://github.com/NativeScript/nativescript-camera/issues/26)

### CODE REVIEW

**Comment by SvetoslavTsenov** [comment]
uitests-ios-pickers

**Comment by SvetoslavTsenov** [comment]
tests widgets#test api25 uitests

**Comment by SvetoslavTsenov** [comment]
test widgets#tachev/improve-images-handling api25 uitests

**Comment by SvetoslavTsenov** [comment]
test widgets#tachev/improve-images-handling api25 uitests

**Comment by SvetoslavTsenov** [comment]
👍

**Comment by SvetoslavTsenov** [comment]
Hey @DimitarTachev, could you please rebase again.

**Comment by SvetoslavTsenov** [comment]
test widgets#tachev/improve-images-handling api25 uitests

**Comment by p-3** [comment]
any update when this will be merged?

**Comment by SvetoslavTsenov** [comment]
test widgets#tachev/improve-images-handling

**Comment by SvetoslavTsenov** [comment]
test branch_widgets#tachev/improve-images-handling

**Comment by SvetoslavTsenov** [comment]
test branch_widgets#tachev/improve-images-handling

**Comment by ADjenkov** [comment]
test branch_widgets#tachev/improve-images-handling

**Comment by SvetoslavTsenov** [comment]
👍

**Pull request merged**
