### PR TITLE
Add and remove event listener fixes

### LINKED ISSUE #605: Guard for "undefined" in Observable's on and off
The:
```
application.android.off(application.AndroidApplication.activiryResultEvent, onResult);
```
Throws:
```
TypeError: Cannot read property 'split' of undefined'.
```
A protection against `undefined` with meaningful error message would be handy.

### PR DESCRIPTION
**Pull request by enchev**
Fixed #605

### CODE REVIEW

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by hdeshev** [comment]
:+1:

**Comment by PanayotCankov** [comment]
:+1:

**Pull request merged**
