### PR TITLE
application module events added

### PR DESCRIPTION
**Pull request by enchev**
Fix for #233 & #244.

Example:
```TypeScript
import application = require("application");
application.mainModule = "app/mainPage";

application.on(application.launchEvent, function (args: application.ApplicationEventData) {
    console.log("launchEvent, iOS: " + args.ios + ", Android: " + args.android);
});

application.on(application.uncaughtErrorEvent, function (args: application.ApplicationEventData) {
    console.log("uncaughtErrorEvent, iOS: " + args.ios + ", Android: " + args.android);
});

application.on(application.suspendEvent, function (args: application.ApplicationEventData) {
    console.log("suspendEvent, iOS: " + args.ios + ", Android: " + args.android);

});

application.on(application.resumeEvent, function (args: application.ApplicationEventData) {
    console.log("resumeEvent, iOS: " + args.ios + ", Android: " + args.android);
});

application.on(application.exitEvent, function (args: application.ApplicationEventData) {
    console.log("exitEvent, iOS: " + args.ios + ", Android: " + args.android);
});

application.on(application.lowMemoryEvent, function (args: application.ApplicationEventData) {
    console.log("exitEvent, iOS: " + args.ios + ", Android: " + args.android);

});

application.start();
```

### CODE REVIEW

**Comment by alejonext** [comment]
+1

**Comment by nsndeck** [comment]
:+1:

**Comment by hshristov** [comment]
:+1: what about putting this example in the docs?

**Comment by enchev** [comment]
@hshristov Will do!

**Comment by bfattori** [comment]
`application.exitEvent` is not called when the app is killed via the Android app manager. Has anyone else experienced this?

**Pull request merged**
