### PR TITLE
css import support added

### PR DESCRIPTION
**Pull request by enchev**

### CODE REVIEW

**Comment by ErjanGavalji** [comment]
:+1:

**Comment by hshristov** [comment]
Do we cache CSS selectors if you navigate twice to the same page?

**Comment by enchev** [comment]
@hshristov Not sure. Maybe this can be the next task.

**Comment by ErjanGavalji** [comment]
@hshristov @enchev Caching is an interesting domain. We must be careful not to have too much stuff cached. A user might never use the cached item(s), thus cache only pointlessly eating memory.

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by nsndeck** [comment]
:+1:

**Pull request merged**
