### PR TITLE
wrong app delegate creation removed

### PR DESCRIPTION
**Pull request by enchev**
This class is automatically created - we should not instantiate it!

### CODE REVIEW

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by vakrilov** [comment]
:+1:

**Comment by ErjanGavalji** [comment]
:+1:

**Pull request merged**
