### PR TITLE
No more ambient modules for tns-core-modules/* subpackages.

### PR DESCRIPTION
**Pull request by hdeshev**
- Use path mappings in tsconfig.json to resolve module typings
- Only use ambient mobules for global API's
- Move single-file modules to a subdir with the same name so that
we can provide a hand-written typing next to it (via package.json)
- Delete all mentions of tns-core-modules.d.ts
- Delete reference d.ts assembly build steps. Not needed anymore.
- HACK! Use a `<reference>` for global typings in application.d.ts
to avoid publishing a separate @types/tns-core-modules package.

TODO before merging:

- [x] Update the typescript plugin and add a path mappings tsconfig migration
- [x] Upgrade tests and ui-tests apps
- [ ] ~~~PR's for the typescript and angular project templates removing references.d.ts~~~
- [x] Don't create a references.d.ts file on typescript plugin installation.

### CODE REVIEW

**Comment by hdeshev** [comment]
run ci

**Comment by hdeshev** [comment]
run ci

**Comment by hdeshev** [comment]
run ci

**Comment by hdeshev** [comment]
run ci

**Comment by hdeshev** [comment]
run ci

**Comment by vchimev** [comment]
full-build

**Comment by vchimev** [comment]
full build

**Pull request merged**
