### PR TITLE
1631|fix(dialogs): change alert dialog context

### LINKED ISSUE #1631: dialogs.confirm throws exception when writing angular 2 + {N} app
Steps to reproduce:

I wrote this simple snippet:

  confirm() {
    var options = {
      title: 'my title',
      message: 'my message',
      okButtonText: "OK",
      cancelButtonText: "Cancel"
    };
    dialogs.confirm(options).then(function (result) {
      console.log(result);
      console.log("Type of result: " + typeof(result));
      console.log("result is "+result);
    }).catch(e => {
      console.log(e);
    });
  }

Expected result:

show the confirm dialog

Actual result:

Exception is thrown:
`
JS: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
JS:     android.app.AlertDialog.resolveDialogTheme(AlertDialog.java:222)
JS:     android.app.AlertDialog$Builder.<init>(AlertDialog.java:452)
JS:     java.lang.reflect.Constructor.newInstance(Native Method)
JS:     com.tns.Platform.createInstance(Platform.java:305)
JS:     com.tns.Platform.callJSMethodNative(Native Method)
JS:     com.tns.Platform.dispatchCallJSMethodNative(Platform.java:799)
JS:     com.tns.Platform.callJSMethod(Platform.java:700)
JS:     com.tns.Platform.callJSMethod(Platform.java:680)
JS:     com.tns.Platform.callJSMethod(Platform.java:670)
JS:     com.tns.gen.android.app.Fragment_ftns_modules_ui_frame_frame_l22_c42__.onCreateView(android.app.Fragment.java)
JS:     android.app.Fragment.performCreateView(Fragment.java:2220)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
JS:     android.app.BackStackRecord.run(BackStackRecord.java:793)
JS:     android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
JS:     android.app.FragmentController.execPendingActions(FragmentController.java:325)
JS:     android.app.Activity.performStart(Activity.java:6267)
JS:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
JS:     android.app.ActivityThread.-wrap11(ActivityThread.java)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:148)
JS:     android.app.ActivityThread.main(ActivityThread.java:5417)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`

### PR DESCRIPTION
**Pull request by ofirdagan**
closes #1631

### CODE REVIEW

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by enchev** [comment]
:+1:

**Comment by NathanWalker** [comment]
I am still seeing this issue on Android:

> JS: Error: Uncaught (in promise): Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
> JS:     android.app.AlertDialog.resolveDialogTheme(AlertDialog.java:154)
> JS:     android.app.AlertDialog$Builder.<init>(AlertDialog.java:379)
> JS:     com.tns.Runtime.callJSMethodNative(Native Method)

By just simply calling `dialogs.action` or `dialogs.prompt`. Any idea on how to fix this issue?

**Pull request merged**
