### PR TITLE
send console messages to debugger

### PR DESCRIPTION
**Pull request by blagoev**
related to https://github.com/NativeScript/android-runtime/pull/333

### CODE REVIEW

**Comment by blagoev** [comment]
issue https://github.com/NativeScript/android-runtime/issues/145

**Comment by hshristov** [comment]
Why don't you put your code in `logMessage` method?

**Comment by vakrilov** [comment]
run ci

**Comment by enchev** [comment]
:+1:

**Comment by hshristov** [comment]
:+1:

**Pull request merged**
