### PR TITLE
Fixed typo in ImageSource function: getTargetFromat -> getTargetFormat

### PR DESCRIPTION
**Pull request by steinerj**
Dear friend, we, the rest of the NativeScript community thank you for your
contribution! Because we want to present a really nice, readable changelog with each
release, please provide the following information:

### Create a meaningful title
Please, ensure your title is less than 50 characters and starts with a capital
letter. We strive to follow the guidelines in the
[How to Write a Git Commit Message] (http://chris.beams.io/posts/git-commit/)
article for PR titles.

### Does your commit message include the wording below to reference a specific issue in this repo?
Fixes/Implements #[Issue Number].

### Does your pull request have [unit tests](https://github.com/NativeScript/NativeScript/blob/master/running-tests.md)?
If not, why?
If not, please tell us why tests are not included, and list all steps needed to test your pull request manually.

### CODE REVIEW

**Comment by enchev** [comment]
Hey @steinerj,

Please sign our CLA before we can merge your pull request!

Thanks

**Comment by steinerj** [comment]
I did. Dunno why the bot is not updating. Maybe bc I inline edited the file...

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Pull request merged**
