### PR TITLE
fix(http): ensure httpcontent.toFile() creates intermediate directories

### PR DESCRIPTION
**Pull request by gezn**
When using the response.content.toFile the dir for the file should be created it not exists instead of throwing an error

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [x] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
https://github.com/NativeScript/NativeScript/issues/3870

## What is the new behavior?
https://github.com/NativeScript/NativeScript/issues/3870
as described on the issue, in the new behavior it just tries to create the dir in case it doesn't exists before writing the file

Fixes #[3870].

 
BREAKING CHANGES:

no breaking changes 

this is my first contribution

### CODE REVIEW

**Comment by radeva** [comment]
Thanks @gezn for taking part in the contributors contest and making your first contribution! 
The team is now a bit busy around the [release of 5.0](https://github.com/NativeScript/NativeScript/issues/6384). Have in mind that it might take a bit more time to review and get back to you with comments.

**Comment by vakrilov** [comment]
test

**Comment by vakrilov** [comment]
Hey @gezn,
We disable all the tests that are doing remote requests, because they were flaky and sometimes fail, because of networking reasons rather than bugs :)
We will check what's the status and update you if we expect anything else from your side.

**Comment by gezn** [comment]
thanks for the quick answer @vakrilov

**Comment by radeva** [comment]
Hi @gezn ,

Congratulations on being one of the winners in the {N} First-time contributors contest! 

You can claim your prize by contacting us at nativescriptwinners[at]progress.com not later than Nov 30th 2018 . Make sure you send us the following info: 
👉Your full name 
👉Your email 
👉Your country or residence 

Best regards,
The NativeScript Team

**Comment by dtopuzov** [comment]
CI reports failing test.

iOS:
```
Test: HTTP.test_request_responseContentToFileFromUrlShouldReturnCorrectFileAndCreateDirPathIfNecesary FAILED: result from to file should be greater than 0 in size2018-11-27 13:20:24.797815+0200 0x10a02c   Default     0x0                  56585  tests: (NativeScript) CONSOLE INFO file:///app/tns_modules/tns-core-modules/trace/trace.js:160:29: Test: Tests EOF!
```

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
test

**Pull request merged**
